mindmap
  root(("pa-speakers"))
    "型号数: 67"
    "型号列表"
      "ds-kac3400"
      "ds-kac3800"
      "ds-kac3a20"
      "ds-kac6300-c"
      "ds-kac6600-c"
      "ds-kac6600-cg"
      "ds-kac6a20-c"
      "ds-kac6a20-cg"
      "ds-kal1100-m"
      "ds-kal1101-m"
      "ds-kal1102-m"
      "ds-kal2060-m"
      "ds-kal2100-m"
      "ds-kal2101-m"
      "ds-kal2102-m"
      "ds-kal2200-m"
      "ds-kal2hg1-s"
      "ds-kal4300-m"
      "其余 49 个型号"
    "主要差异字段"
      "一般规范 > 尺寸(mm)"
      "其他参数 > 输出功率"
      "系统功能 > 音频编码及码率"
      "系统外设 > 报警"
      "系统外设 > 网口"
      "系统外设 > 音频输出"
      "系统外设 > 音频输入"
      "一般规范 > 产品尺寸"
      "一般规范 > 电源"
      "音频输出 > 额定功率"