mindmap
  root(("Distribution-of-access-controller"))
    "所属大类: Access-Control-Device"
    "子类: Exclusive-Distribution-Product"
    "型号数: 24"
    "型号列表"
      "c01"
      "c02"
      "c04"
      "ds-k2801"
      "DS-K2801"
      "ds-k2801-xb"
      "ds-k2801-xf"
      "ds-k2801t"
      "其余 16 个型号"
    "暂无规格对比数据"