mindmap
  root(("Access-Control-Terminal"))
    "型号数: 15"
    "型号列表"
      "DS-K1T8003EF"
      "DS-K1T8003F"
      "DS-K1T8003MF"
      "DS-K1T8004EF"
      "DS-K1T8004MF"
      "DS-K1T801E"
      "DS-K1T801M"
      "DS-K1T802E"
      "DS-K1T802M"
      "ds-k1t804a"
      "ds-k1t804b"
      "ds-k1t806"
      "ds-k2m081"
      "k11"
      "k12"