mindmap
  root(("pa-processers"))
    "型号数: 20"
    "型号列表"
      "ds-kba3500"
      "ds-kba3b00"
      "ds-kba6002"
      "ds-kba6002-g"
      "ds-kba6120"
      "ds-kba6122"
      "ds-kba6122-g"
      "ds-kba6240"
      "ds-kba6242"
      "ds-kba6360"
      "ds-kba6362"
      "ds-kba6400-2"
      "ds-kba6402-2"
      "ds-kba6650"
      "ds-kba6652"
      "ds-kba6652-g"
      "ds-kba6800-2"
      "ds-kba6802-2"
      "其余 2 个型号"