mindmap
  root(("Card-Reader"))
    "型号数: 16"
    "型号列表"
      "ds-k1801a"
      "DS-K1801E"
      "DS-K1801EK"
      "DS-K1801M"
      "DS-K1801MK"
      "ds-k1802a"
      "DS-K1802E"
      "DS-K1802EK"
      "DS-K1802M"
      "DS-K1802MK"
      "ds-k1803a"
      "DS-K1803MF"
      "DS-K1806M"
      "ds-k1808a"
      "ds-k1809m"
      "r10"