mindmap
  root(("S000001100"))
    "所属大类: Access-Control-Device"
    "子类: Electric-Lock"
    "型号数: 4"
    "型号列表"
      "ds-k4h250edc"
      "ds-k4h250esc"
      "ds-k4h250pdc"
      "ds-k4h250ps-uhk"
    "暂无规格对比数据"