mindmap
  root(("access-control-terminal"))
    "所属大类: Access-Control-Device"
    "子类: traditional-access-control"
    "型号数: 9"
    "型号列表"
      "ds-k1t105a"
      "ds-k1t201a"
      "ds-k1t203mbfw"
      "ds-k1t203mbw"
      "ds-k1t502mbfw"
      "ds-k1t502mbfw-c"
      "ds-k1t502mbw"
      "ds-k1t502mbw-c"
      "其余 1 个型号"
    "暂无规格对比数据"