mindmap
  root(("smart-turnstile-components"))
    "所属大类: Access-Control-Device"
    "子类: smart-access-control"
    "型号数: 4"
    "型号列表"
      "ds-k5604b-z"
      "ds-k5670"
      "ds-k5671"
      "ds-k5671b"
    "暂无规格对比数据"