mindmap
  root(("microphone"))
    "所属大类: audio-sensing-products"
    "子类: audio"
    "型号数: 9"
    "型号列表"
      "ds-2fp1020-b"
      "ds-2fp1021"
      "ds-2fp2121"
      "ds-2fp4020-t"
      "ds-2fp550-dm"
      "ds-2mc2006ne-t"
      "ds-2mc4032np-t"
      "ds-52aq204"
      "其余 1 个型号"
    "暂无规格对比数据"