mindmap
  root(("pa-input-terminals"))
    "所属大类: audio-sensing-products"
    "子类: audio"
    "型号数: 6"
    "型号列表"
      "ds-kbi3d00"
      "ds-kbi3f01"
      "ds-kbi3g00"
      "ds-kbi3h02"
      "ds-kbi3h11"
      "ds-kbi3t01"
    "暂无规格对比数据"