mindmap
  root(("S000016659"))
    "型号数: 8"
    "型号列表"
      "ds-k4e100"
      "ds-k4e101"
      "ds-k4h250edc"
      "ds-k4h250esc"
      "ds-k4h250pdc"
      "ds-k4h250pdc-lz"
      "ds-k4h250ps-uhk"
      "ds-k4t100c"