mindmap
  root(("smart-access-control-terminal"))
    "型号数: 18"
    "型号列表"
      "ds-k1t6-gs3"
      "ds-k1t6-gs4"
      "ds-k1t610"
      "ds-k1t6240"
      "ds-k1t640"
      "ds-k1t641"
      "ds-k1t641a"
      "ds-k1t642"
      "ds-k1t670"
      "ds-k1t671b"
      "ds-k1t672"
      "ds-k1t673"
      "ds-k1t680"
      "ds-k1t681"
      "ds-k1t690"
      "ds-k1t691"
      "ds-k1t740"
      "ds-k5671b"