mindmap
  root(("smart-access-control-terminal"))
    "所属大类: Access-Control-Device"
    "子类: smart-access-control"
    "型号数: 18"
    "型号列表"
      "ds-k1t6-gs3"
      "ds-k1t6-gs4"
      "ds-k1t610"
      "ds-k1t6240"
      "ds-k1t640"
      "ds-k1t641"
      "ds-k1t641a"
      "ds-k1t642"
      "其余 10 个型号"
    "暂无规格对比数据"