mindmap
  root(("pa-processers"))
    "所属大类: audio-sensing-products"
    "子类: audio"
    "型号数: 20"
    "型号列表"
      "ds-kba3500"
      "ds-kba3b00"
      "ds-kba6002"
      "ds-kba6002-g"
      "ds-kba6120"
      "ds-kba6122"
      "ds-kba6122-g"
      "ds-kba6240"
      "其余 12 个型号"
    "暂无规格对比数据"