mindmap
  root(("S000016639"))
    "型号数: 33"
    "型号列表"
      "ds-k1f180a-d8e"
      "ds-k1f181-f"
      "ds-k1zf71"
      "ds-k1zf72"
      "ds-k4h258-lz"
      "ds-k4h258-u"
      "ds-k4h258d"
      "ds-k4h258ds"
      "ds-k4h258s"
      "ds-k4h258sn"
      "ds-k4h258ss"
      "ds-k4t108"
      "ds-k4t108-u1"
      "ds-k4t108g"
      "ds-k4t108w"
      "ds-k7m08ic-a"
      "ds-k7m08ic-sa"
      "ds-kab3-01h"
      "其余 15 个型号"