mindmap
  root(("Distribution-of-access-controller"))
    "型号数: 24"
    "型号列表"
      "c01"
      "c02"
      "c04"
      "ds-k2801"
      "DS-K2801"
      "ds-k2801-xb"
      "ds-k2801-xf"
      "ds-k2801t"
      "DS-K2801T"
      "ds-k2802"
      "DS-K2802"
      "ds-k2802-xb"
      "ds-k2802-xf"
      "ds-k2802t"
      "DS-K2802T"
      "ds-k2804"
      "DS-K2804"
      "ds-k2804-xb"
      "其余 6 个型号"