mindmap
  root(("pro-audio-input-terminal"))
    "所属大类: audio-sensing-products"
    "子类: audio"
    "型号数: 5"
    "型号列表"
      "ds-2fp8021"
      "ds-53mc200-w-b"
      "ds-kbi2g03-w"
      "ds-qa2i01-u1"
      "ds-qaig14"
    "暂无规格对比数据"