mindmap
  root(("gas-monitoring-series"))
    "所属大类: audio-sensing-products"
    "子类: spectral-camera"
    "型号数: 7"
    "型号列表"
      "ds-2ma6108-200m-ch4"
      "ds-2ma9188-w-bt"
      "ds-2xe9423f-izhrs-tdl50-c2h4"
      "ds-2xe9423f-izhrs-tdl50-co"
      "ds-2xe9423f-izhrs-tdl50-nh3"
      "ds-2xe94405f-izhrs-ms"
      "ds-2xe9440f-izhrs-tdl100"
    "暂无规格对比数据"