mindmap
  root(("Smart-Face-Recognition-Terminal"))
    "型号数: 31"
    "型号列表"
      "a10"
      "a11"
      "a12"
      "d10"
      "d13"
      "DS-K1A330"
      "ds-k1t320"
      "DS-K1T331"
      "ds-k1t331w-d"
      "DS-K1T341"
      "DS-K1T341B"
      "ds-k1t342m"
      "ds-k1t343m"
      "ds-k1t345m"
      "ds-k1t345m-3xf"
      "ds-k1t346m"
      "ds-k1t346m-3xf"
      "DS-K1T6Q-F40"
      "其余 13 个型号"