mindmap
  root(("S000016639"))
    "所属大类: Access-Control-Device"
    "子类: Exclusive-Distribution-Product"
    "型号数: 33"
    "型号列表"
      "ds-k1f180a-d8e"
      "ds-k1f181-f"
      "ds-k1zf71"
      "ds-k1zf72"
      "ds-k4h258-lz"
      "ds-k4h258-u"
      "ds-k4h258d"
      "ds-k4h258ds"
      "其余 25 个型号"
    "暂无规格对比数据"