mindmap
  root(("Access-Control-Terminal"))
    "所属大类: Access-Control-Device"
    "子类: Exclusive-Distribution-Product"
    "型号数: 15"
    "型号列表"
      "DS-K1T8003EF"
      "DS-K1T8003F"
      "DS-K1T8003MF"
      "DS-K1T8004EF"
      "DS-K1T8004MF"
      "DS-K1T801E"
      "DS-K1T801M"
      "DS-K1T802E"
      "其余 7 个型号"
    "暂无规格对比数据"