mindmap
  root(("network-keyboard"))
    "所属大类: Control-Products"
    "子类: keyboard-series"
    "型号数: 4"
    "型号列表"
      "ds-1100k-b"
      "ds-1105k"
      "ds-1200k"
      "ds-1600k-b"
    "暂无规格对比数据"