mindmap
  root(("ultra-hd-decoder"))
    "所属大类: Control-Products"
    "子类: Decoder"
    "型号数: 6"
    "型号列表"
      "ds-6a01ud"
      "ds-6a04ud"
      "ds-6a08ud"
      "ds-6a10ud"
      "ds-6a12ud"
      "ds-6a16ud"
    "暂无规格对比数据"