mindmap
  root(("S000005383"))
    "型号数: 16"
    "型号列表"
      "ds-d4025fo-cki"
      "ds-d4030fo-cki"
      "ds-d4040fo-cki"
      "ds-d4050fo-cki"
      "ds-d4060fo-cki"
      "ds-d4080fo-cki"
      "ds-d40a0fo-cki"
      "ds-d4225cx-5bp"
      "ds-d4230cx-5bp"
      "ds-d4239cd-1aab"
      "ds-d4240cx-5bp"
      "ds-d4248cd-1aab"
      "ds-d4250cx-5bp"
      "ds-d4260cx-5bp"
      "ds-d4280cx-5bp"
      "ds-d42a0cx-5bp"