mindmap
  root(("S000011220"))
    "型号数: 7"
    "型号列表"
      "ds-ck20fi"
      "ds-ck25fi"
      "ds-ck30fi"
      "ds-d4015fi-csmh"
      "ds-d4018fi-csmh"
      "ds-d4020fi-csmh"
      "ds-d4025fi-csmh"