mindmap
  root(("multicopter-drones"))
    "型号数: 4"
    "型号列表"
      "MX4060B%E5%A5%97%E8%A3%85A"
      "MX4090A%E5%A5%97%E8%A3%85F"
      "MX6120A%E5%A5%97%E8%A3%85F"
      "MX6150B%E5%A5%97%E8%A3%85F"