mindmap
  root(("dedicated-monitor"))
    "型号数: 33"
    "型号列表"
      "ds-d5022fc-n"
      "ds-d5022fl-b"
      "ds-d5022fl-s"
      "ds-d5024fc-n"
      "ds-d5027fc-c"
      "ds-d5027fc-n"
      "ds-d5027uc"
      "ds-d5032fc-b"
      "ds-d5032fc-c"
      "ds-d5032fl-a"
      "ds-d5032fl-d"
      "ds-d5032fl-s"
      "ds-d5032fq-a"
      "ds-d5032uc"
      "ds-d5043fl-d"
      "ds-d5043fl-s"
      "ds-d5043uc-a"
      "ds-d5043uc-a-f"
      "其余 15 个型号"