mindmap
  root(("S000011220"))
    "所属大类: Display-Product"
    "子类: s000011139"
    "型号数: 7"
    "型号列表"
      "ds-ck20fi"
      "ds-ck25fi"
      "ds-ck30fi"
      "ds-d4015fi-csmh"
      "ds-d4018fi-csmh"
      "ds-d4020fi-csmh"
      "ds-d4025fi-csmh"
    "暂无规格对比数据"