mindmap
  root(("gimbal"))
    "型号数: 10"
    "型号列表"
      "at1010c"
      "at1025a"
      "at2010a"
      "at3030a"
      "at3030c"
      "at4040a"
      "at6005a"
      "g3ml0617d"
      "g3v0223s"
      "g3v0837a"