mindmap
  root(("S000009959"))
    "型号数: 9"
    "型号列表"
      "ydbz-0-b-hkyd-100"
      "ydbz-0-b-hkyd-100p"
      "ydbz-0-b-hkyd-160"
      "ydbz-0-b-hkyd-200"
      "ydbz-0-b-hkyd-250"
      "ydbz-0-b-hkyd-310"
      "ydbz-0-c-hkyd-160"
      "ydbz-0-c-hkyd-200"
      "ydbz-0-c-hkyd-310"