mindmap
  root(("mirror-series-lcd-videowall"))
    "型号数: 21"
    "型号列表"
      "ds-d2046nl-e-y"
      "ds-d2046nl-f-y"
      "ds-d2046nl-t-t"
      "ds-d2049nl-b"
      "ds-d2049nl-b-y"
      "ds-d2055nh-b-g"
      "ds-d2055nh-b-y"
      "ds-d2055nh-e-g"
      "ds-d2055nh-e-t"
      "ds-d2055nh-f-g"
      "ds-d2055nh-f-y"
      "ds-d2055nh-f-ym"
      "ds-d2055nl-b-g"
      "ds-d2055nl-b-y"
      "ds-d2055nl-e-g"
      "ds-d2055nl-e-t"
      "ds-d2055nl-e-y"
      "ds-d2055nl-f-g"
      "其余 3 个型号"