mindmap
  root(("ming-series-lcd-video-wall"))
    "型号数: 9"
    "型号列表"
      "ds-d2a461hu"
      "ds-d2a461le"
      "ds-d2a461lr"
      "ds-d2a461lt"
      "ds-d2a491lu"
      "ds-d2a551le"
      "ds-d2a551lr"
      "ds-d2a551lt"
      "ds-d2a551lu"