mindmap
  root(("S000015784"))
    "型号数: 12"
    "型号列表"
      "ds-tcp100-e"
      "ds-tcp300-e"
      "ds-tcp330-e"
      "ds-tcp506-ep"
      "ds-tds110"
      "ds-tds210"
      "ds-tpw332"
      "ds-tpw343"
      "ds-tvb200"
      "ds-tvg100"
      "ds-tvl121"
      "m000006985"