mindmap
  root(("roadside-parking-camera-series"))
    "所属大类: entrance-and-exit-parking"
    "子类: roadside-parking"
    "型号数: 12"
    "型号列表"
      "ds-tcl200-er"
      "ds-tcl200-es"
      "ds-tcl201"
      "ds-tcl202-e"
      "ds-tcl220-er"
      "ids-tcr206-e"
      "ids-tcr800-g"
      "ids-tcr803-g"
      "其余 4 个型号"
    "暂无规格对比数据"