mindmap
  root(("S000015784"))
    "所属大类: entrance-and-exit-parking"
    "子类: parking-guidance"
    "型号数: 12"
    "型号列表"
      "ds-tcp100-e"
      "ds-tcp300-e"
      "ds-tcp330-e"
      "ds-tcp506-ep"
      "ds-tds110"
      "ds-tds210"
      "ds-tpw332"
      "ds-tpw343"
      "其余 4 个型号"
    "暂无规格对比数据"