mindmap
  root(("Security"))
    "型号数: 110"
    "型号列表"
      "1"
      "10"
      "100"
      "101"
      "102"
      "103"
      "104"
      "105"
      "106"
      "107"
      "108"
      "109"
      "11"
      "110"
      "111"
      "112"
      "113"
      "114"
      "其余 92 个型号"