mindmap
  root(("S000016222"))
    "所属大类: entrance-and-exit-parking"
    "子类: entrance-exit-management-and-control"
    "型号数: 4"
    "型号列表"
      "ds-tvl211-4"
      "ds-tvl221"
      "ds-tvl224"
      "ds-tvl238-8"
    "暂无规格对比数据"