mindmap
  root(("Smart"))
    "所属大类: Exclusive-Products"
    "子类: products"
    "型号数: 43"
    "型号列表"
      "1"
      "10"
      "11"
      "12"
      "16"
      "17"
      "18"
      "19"
      "其余 35 个型号"
    "暂无规格对比数据"