mindmap
  root(("roadside-parking-camera-series"))
    "型号数: 12"
    "型号列表"
      "ds-tcl200-er"
      "ds-tcl200-es"
      "ds-tcl201"
      "ds-tcl202-e"
      "ds-tcl220-er"
      "ids-tcr206-e"
      "ids-tcr800-g"
      "ids-tcr803-g"
      "m000051415"
      "m000054851"
      "m000061101"
      "m000066513"