mindmap
  root(("Explosion-proof"))
    "型号数: 56"
    "型号列表"
      "1"
      "10"
      "11"
      "12"
      "13"
      "14"
      "15"
      "16"
      "17"
      "18"
      "19"
      "2"
      "20"
      "21"
      "22"
      "23"
      "24"
      "25"
      "其余 38 个型号"