mindmap
  root(("S000015782"))
    "所属大类: entrance-and-exit-parking"
    "子类: entrance-exit-management-and-control"
    "型号数: 3"
    "型号列表"
      "ds-tmc405-eh-r-l"
      "ds-tmc407-eh"
      "ds-tmc417-eh-r-l"
    "暂无规格对比数据"