mindmap
  root(("ACS"))
    "所属大类: Exclusive-Products"
    "子类: products"
    "型号数: 78"
    "型号列表"
      "1"
      "10"
      "11"
      "12"
      "13"
      "14"
      "15"
      "16"
      "其余 70 个型号"
    "暂无规格对比数据"