mindmap
  root(("Security"))
    "所属大类: Exclusive-Products"
    "子类: products"
    "型号数: 110"
    "型号列表"
      "1"
      "10"
      "100"
      "101"
      "102"
      "103"
      "104"
      "105"
      "其余 102 个型号"
    "暂无规格对比数据"