mindmap
  root(("video-fusion-series"))
    "所属大类: Fire-Protection"
    "子类: Distributed-Fire-Protection"
    "型号数: 5"
    "型号列表"
      "np-v1g-t10-4mm"
      "np-v1g-t20-4mm"
      "np-v1g-t40-4mm"
      "np-v1w"
      "np-v2y-p"
    "暂无规格对比数据"