mindmap
  root(("8-Series-Smart-Camera"))
    "型号数: 108"
    "型号列表"
      "ds-2cd3646wda-pwz"
      "ds-2cd3t47wda-pw"
      "ds-2cd3t86wda-pw"
      "ds-2cd6b25fwd-izs-120fps"
      "ds-2cd6b25fwd-zs"
      "ds-2cd6b45fwd-izs-60fps"
      "ds-2cd6b45fwd-zs"
      "ds-2cd6b55fwd-p-l-t1"
      "ds-2cd8287f-s-is-b"
      "ds-2cd8287f-s-zs"
      "ds-2cd8287f-s-zs-b"
      "ds-2cd8287f-t-zs"
      "DS-2CD83C6F-MET-SH-GLT"
      "ds-2cd8546-syk-lczj"
      "ds-2cd8546-syk-ldm"
      "ds-2cd8546-syk-llvi"
      "ds-2cd8546e-syk-c2"
      "ds-2cd8546f-syk-c4"
      "其余 90 个型号"
    "主要差异字段"
      "图像 > 图像设置"
      "接口 > 复位"
      "接口 > 接口类型"
      "接口 > 网络"
      "摄像机 > P/N制"
      "图像 > 图像增强"
      "一般规范 > 存储温湿度"
      "一般规范 > 带包装重量"
      "一般规范 > 设备重量"
      "一般规范 > 包装尺寸"