mindmap
  root(("S000009939"))
    "型号数: 8"
    "型号列表"
      "dt-hk10j-gx-b"
      "gb-hk-2601"
      "gb-hk-2602"
      "gb-hk-2603"
      "gt-hk11j-n-b"
      "gty-hk-2501"
      "gty-hk11c-n-b"
      "gty-hk21c-g"