mindmap
  root(("2-Series-Smart-Camera"))
    "型号数: 63"
    "型号列表"
      "ds-2cd2126f-d-wda1-is"
      "ds-2cd2146f-d-wda1-is"
      "ds-2cd2326-d-wda4-l"
      "ds-2cd2326f-d-wda3-xs"
      "ds-2cd2326f-d-wda4-ls"
      "ds-2cd2345fv3-is-yw"
      "ds-2cd2346-d-wda4-l"
      "ds-2cd2346f-d-wda3-xs"
      "ds-2cd2346f-d-wda4-ls"
      "ds-2cd2356ef-d-wda3-is"
      "ds-2cd2386fwda4-ls"
      "ds-2cd2526fwda2-its-dt"
      "ds-2cd2526fwda2-its-dtf"
      "ds-2cd2526fwda2-its3-dt"
      "ds-2cd2546fwda2-its-dt"
      "ds-2cd2546fwda2-its-dtf"
      "ds-2cd2546fwda2-its3-dt"
      "ds-2cd2626f-d-wda3-lzs"
      "其余 45 个型号"