mindmap
  root(("7-Series-Smart-Camera"))
    "型号数: 28"
    "型号列表"
      "ds-2cd7047ewd-a-jm-nmfc-d"
      "ds-2cd7047ewd-e2-i-x-jm-nmfc-d"
      "ds-2cd7047fwd-e2-i-x-jm-d"
      "ds-2cd7048fwd-e2-xz-c"
      "ds-2cd7147ewdv2-izs-dn"
      "ds-2cd7147fwdv2-iz-s-jm-d"
      "ds-2cd7147hwdv2-izs-jm-c"
      "ds-2cd7187hwdv2-izs-jm-c"
      "ds-2cd7247hwd-a-gl-g-nmfc-jm-c"
      "ds-2cd7247hwd-e2-x-z-gl-g-nmfc-jm-c"
      "ds-2cd7287hwd-a-gl-g-nmfc-jm-c"
      "ds-2cd7287hwd-e2-x-z-gl-g-nmfc-jm-c"
      "ds-2cd7647hwd-x-z-s-g-jm-zj-c"
      "ds-2cd7687hwd-x-z-s-g-jm-zj-c"
      "ds-2cd7a47ewd-i-x-z-s-zj-jm-nmfc-d"
      "ds-2cd7a47fwd-i-x-z-s-nmfc-jm-zj-d"
      "ds-2cd7a47fwd-sc-z-t2"
      "ds-2cd7a47fwdv3-xzs-zj-jm-nmfc"
      "其余 10 个型号"