mindmap
  root(("mine-and-coal-safety-series-product"))
    "型号数: 9"
    "型号列表"
      "kba127-b-8245fwd-xzs"
      "kba18-c-8346fwd-i-l-z-b"
      "kba18-d-8346fwd-i-l-zs-b"
      "kba18-i-8342-i-l-s"
      "kba7-4-a-6e45-xzsw"
      "kba7-4-b-6e45-xzs"
      "kjj127-a-3t0310"
      "ljy127"
      "ljy127-a"