mindmap
  root(("Explosion-Proof-Bullet-Camera"))
    "型号数: 63"
    "型号列表"
      "ds-2db3220-cx-s6-b"
      "ds-2db3220b-cx-s6-b"
      "ds-2db3220i-cx-s6-b"
      "ds-2db3425-cx-s6-b"
      "ds-2db3425i-cx-s6-b"
      "ds-2db4223-cx-t5"
      "ds-2db4223i-cx-t5"
      "ds-2db4237i-cwx-t5f"
      "ds-2xe3020wd-dx"
      "ds-2xe3025fwd-cx"
      "ds-2xe3027fwd-cl"
      "DS-2XE3027FWD-LIZ"
      "ds-2xe3029fwd-dxz"
      "ds-2xe3040wd-dx"
      "ds-2xe3045fwd-cx"
      "DS-2XE3046FWD-I"
      "ds-2xe3047fwd-cl"
      "DS-2XE3047FWD-LIZ"
      "其余 45 个型号"