mindmap
  root(("DE-Series"))
    "型号数: 77"
    "型号列表"
      "ds-1685zj"
      "ds-1686zj-g"
      "ds-2de2q120ly-t-gl2"
      "ds-2de2q140ly-t-gl2"
      "ds-2de3c120m-de"
      "ds-2de3c140m-de"
      "ds-2de3q120mx-t-glse-ph03-xm"
      "ds-2de3q120my-t-glse-b"
      "ds-2de3q140my-t-glse-smbg-b"
      "ds-2de3q140my-t-glse-xm-c"
      "ds-2de5223w-s6-c"
      "ds-2de5232w-a-s6-c"
      "ds-2de5232w-a3-s6-c"
      "ds-2de5423w-s6"
      "ds-2de6423mwr-s6"
      "ds-2de6c223mw-d-glt-dg-b"
      "ds-2de6c240mw-d-glt-dg-b"
      "ds-2de6c423mw-d-glt-dg-b"
      "其余 59 个型号"
    "主要差异字段"
      "云台 > 水平范围"
      "云台 > 水平速度"
      "云台 > 守望功能"
      "基础参数 > 宽动态"
      "基础参数 > 日夜转换模式"
      "云台 > 垂直速度"
      "云台 > 巡航扫描"
      "一般规范 > 尺寸"
      "一般规范 > 供电方式"
      "视频 > 最大图像尺寸"