mindmap
  root(("Accessories"))
    "型号数: 15"
    "型号列表"
      "hk-jx-1283"
      "hk-jx-1285"
      "hk-jx-1286"
      "hk-jx-1287"
      "hk-ld-1265"
      "hk-ld-1266"
      "hk-ld-1267"
      "hk-ld-1268"
      "hk-ld-1269"
      "hk-ld-1270"
      "MM38-12"
      "MS17-12"
      "MS24-12"
      "MS24-12L"
      "MS5-12"