mindmap
  root(("Distributed-Series"))
    "所属大类: Front-End-Product"
    "子类: Fixed-Camera"
    "型号数: 198"
    "型号列表"
      "ds-2cd1225-d-la"
      "ds-2cd1245-d-la"
      "ds-2cd1325-d-v2-la"
      "ds-2cd1335-d-v2-la"
      "ds-2cd1345-d-v2-la"
      "ds-2cd1q335-lt"
      "ds-2cd1q445-lt"
      "ds-2cd1t25-d-la"
      "其余 190 个型号"
    "对比概要"
      "已对比 25 / 198 个型号"
      "共发现 40 个差异字段"
    "主要差异"
      "一般规范 / 电流及功耗: DC：12 V，0.7 A，最大功耗：8.5 W / 非-T型号：DC：12 V，0.5 A，最大功耗：6 W-T型号：DC：12 V，0.58 A，最大功耗：7 W / DC：12 V，0.63 A，最大功耗：7.5 W"
      "视频 / 主码流帧率分辨率: 50Hz：25 fps（1920 × 1080，1280 × 720） / 50 Hz：25 fps（1920 × 1080，1280 × 720） / 50 Hz：25 fps（2560 × 1440，1920 × 1080，1280 × 720）"
      "音频 / 音频压缩码率: 64 Kbps（G.711ulaw）/64 Kbps（G.711alaw）/16 Kbps（G.722.1）/16 Kbps（G.726）/32~160 Kbps（MP2L2） / 64 Kbps（G.711）/16 Kbps（G.722.1）/16 Kbps（G.726）/32~160 Kbps（MP2L2） / 64 Kbps（G.711ulaw/G.711alaw）/16 Kbps（G.722.1）/16 Kbps（G.726）/32~160 Kbps（MP2L2）/16~64 Kbps（AAC-LC）"
      "一般规范 / 供电方式: DC：12 V ± 25%，支持防反接保护 / DC：12 V ± 25% ，支持防反接保护 / DC：12 V ± 25%，支持防反接保护*设备出厂配备电源适配器"
      "视频 / 视频压缩标准: 主码流：H.265/H.264子码流：H.265/H.264 / 主码流，子码流：H.265/H.264 / H.265;H.264"
      "视频 / 子码流帧率分辨率: 50 Hz：25 fps（640 × 360） / 50 Hz：25 fps（640 × 360，320 × 240） / 50 Hz：25 fps（768 × 432）"