mindmap
  root(("2-Series-Camera"))
    "型号数: 153"
    "型号列表"
      "ds-2cd2125ef-d-v2-i-s"
      "ds-2cd2125f-d-v2-i-s"
      "ds-2cd2126f-d-wdv3-i-s"
      "ds-2cd2146f-d-wdv4-i-s"
      "ds-2cd2225cd-lglse-t"
      "ds-2cd2225xm-lhgl2t-c22s80"
      "ds-2cd2245cd-lglse-t"
      "ds-2cd2245xm-lgl2-t"
      "ds-2cd2245xm-lhgl2t-c22s80"
      "ds-2cd2245xm-lhglset-ch20s80"
      "ds-2cd2325-d-i"
      "ds-2cd2325-f-d-v3-i-s"
      "ds-2cd2325cv4-l"
      "ds-2cd2325e-d-i"
      "ds-2cd2325e-d-v3-i"
      "ds-2cd2325ef-d-v3-i-s"
      "ds-2cd2326-f-d-wdv3-i-s"
      "ds-2cd2326fdwd-i-st"
      "其余 135 个型号"
    "主要差异字段"
      "视频 > 视频压缩标准"
      "补光 > 补光灯类型"
      "事件 > Smart事件"
      "镜头 > 镜头尺寸接口"
      "一般规范 > 供电方式"
      "摄像机 > 传感器类型"