mindmap
  root(("Specialty-PTZ"))
    "所属大类: Front-End-Product"
    "子类: PTZ-Camera"
    "型号数: 17"
    "型号列表"
      "ds-2df3c401-wl"
      "ds-2df6c404mx-d-glt-gn-dg"
      "ds-2df6c404mx-p10s18g"
      "ds-2df8c4-mx-cp"
      "ds-2hz4b11"
      "ds-2sk6c144bx-it-c0f1"
      "ds-2sk8c144imx-so"
      "ds-2sk8c144imx-wl"
      "其余 9 个型号"
    "暂无规格对比数据"