mindmap
  root(("S000000539"))
    "所属大类: Front-End-Product"
    "子类: PTZ-Camera"
    "型号数: 79"
    "型号列表"
      "ds-2df8432nx-afw-tl"
      "ds-2df8440ix-a-vr"
      "ds-2df8c425mx-a-5g"
      "ds-2df8c425mxr-ab-t5-b"
      "ds-2df8c432ix-a-vr-b"
      "ds-2df8c432mx-a-5g"
      "ds-2df8c432mxr-ab-t5-b"
      "ds-2df8c432mxs"
      "其余 71 个型号"
    "暂无规格对比数据"