mindmap
  root(("Fixed-Analog-Camera"))
    "所属大类: Front-End-Product"
    "子类: Analog-Camera"
    "型号数: 20"
    "型号列表"
      "ds-2cc52d1t-it3"
      "DS-2CE15A2P-VFIR3"
      "DS-2CE16C0T-IT3-5"
      "DS-2CE16C3T-IT3-5"
      "DS-2CE16C5T-IT3"
      "DS-2CE16C5T-IT5"
      "ds-2ce16d1t-it3-5"
      "DS-2CE16D7T-L"
      "其余 12 个型号"
    "暂无规格对比数据"