mindmap
  root(("Anti-CorrosionBallMachine"))
    "型号数: 15"
    "型号列表"
      "ds-2df5225mxr-dy"
      "ds-2df5225mxr-dy-glt-dg"
      "ds-2df5432mxr-dy"
      "ds-2df8c225mxr-ay"
      "ds-2df8c425bx-ay"
      "ds-2df8c425mx-ay"
      "ds-2df8c440mx-ay"
      "ds-2xc6122fwd-is-c"
      "ids-2df8432ix-y-t5"
      "ids-2df8432ixr-y-t5"
      "ids-2df8440i-xr-y-t5"
      "ids-2df8440i5x-y-t5"
      "ids-2df8440ix-y-t5"
      "ids-2df8440ixr-y-t5"
      "ids-2dt6425x-t5"