mindmap
  root(("S000009504"))
    "所属大类: Front-End-Product"
    "子类: s000009479"
    "型号数: 6"
    "型号列表"
      "ds-2rt20-v16l-c-737"
      "ds-2rt20-v16l-c-767"
      "ds-2rt20-v20l-c-767"
      "ds-2rt20s-v16l-c-737"
      "ds-2rt20sp-v16l-c-737"
      "ds-2rt20sp-v16l-c-767"
    "暂无规格对比数据"