mindmap
  root(("PTZ-Series"))
    "型号数: 69"
    "型号列表"
      "ds-2de2204iw-s6"
      "ds-2de2204iw-xm-s6"
      "ds-2de2402iw-s6"
      "ds-2de2402iw-xm-s6"
      "ds-2de3204sw-t5"
      "ds-2de3204w-t5"
      "ds-2de3404sw-t5"
      "ds-2de3404w-t5"
      "ds-2de3a20iw-xm-s6"
      "ds-2pt1c20iw-c8-s7"
      "ds-2pt1c20iw-d-b"
      "ds-2pt1c40iw-c8-s7"
      "ds-2pt1c40iw-d"
      "ds-2pt1c40iw-s7"
      "ds-2pt2122mw"
      "ds-2pt2144mw"
      "ds-2pt2a20bw"
      "ds-2pt2a20iw"
      "其余 51 个型号"
    "主要差异字段"
      "接口 > 网络接口"
      "视频 > 视频压缩标准"
      "基础参数 > 快门"
      "基础参数 > 日夜转换模式"
      "视频 > 主码流帧率分辨率"
      "视频 > 子码流帧率分辨率"
      "一般规范 > 尺寸"
      "音频 > 音频压缩码率"
      "接口 > SD卡扩展"
      "视频 > 最大图像尺寸"