mindmap
  root(("Specialty-PTZ"))
    "型号数: 17"
    "型号列表"
      "ds-2df3c401-wl"
      "ds-2df6c404mx-d-glt-gn-dg"
      "ds-2df6c404mx-p10s18g"
      "ds-2df8c4-mx-cp"
      "ds-2hz4b11"
      "ds-2sk6c144bx-it-c0f1"
      "ds-2sk8c144imx-so"
      "ds-2sk8c144imx-wl"
      "ds-2sk8c144inx-lr13"
      "ds-ygsswz01"
      "ids-2df8c432mx-afw-sk-sp-t5"
      "ids-2df8c435mhs-t3"
      "ids-2df8c440mx-afw-sk-sp-t5"
      "ids-2vs435-t5"
      "ids-2vs845-f835h-t5"
      "ids-2vt882-d840"
      "ids-egd0288-b"