mindmap
  root(("Explosion-Proof-Positioning-System"))
    "型号数: 12"
    "型号列表"
      "ds-2dc4225i-dwx"
      "ds-2dc4425i-dwx"
      "ds-2dy7432i-cwx-t5-316l"
      "ds-2dy9220iw-cwx"
      "ds-2dy9230iw-cwx"
      "ds-2dy9230iw-cwx-s6-316l-yf"
      "ds-2dy9230iw-cwx-s6-yf"
      "ids-2dy9237i-cwx-t5f"
      "ids-2dy9437i-cwx-t5f"
      "ids-2dy9437i-cwx-t5f-316l"
      "ids-2dy9837i-cwx-t5f"
      "ids-2dy9837i-cwx-t5f-316l"