mindmap
  root(("5-Series-Camera"))
    "型号数: 7"
    "型号列表"
      "ds-2cd5024efwd-a-nmfc"
      "ds-2cd5025ewd-a"
      "ds-2cd5125ewdv3-i-z-s-jm-cvbs"
      "ds-2cd5145ewdv3-i-z-s-jm-cvbs"
      "DS-2CD5A24EFWD-IZ-S-ZJ-F"
      "ds-2cd5a67ewdv3-iz-s-jm-cvbs-zj"
      "ds-2cd5a87ewdv3-iz-s-jm-cvbs-zj"