mindmap
  root(("Linkage-System"))
    "所属大类: Front-End-Product"
    "子类: PTZ-Camera"
    "型号数: 21"
    "型号列表"
      "ds-2sk8c144imx"
      "ds-2sk8c144imx-d-25c0-t5"
      "ds-2sk8c144imx-d-32c4-t5"
      "ds-2sk8c144imx-d-40c4-t5"
      "ds-2sk8c144imx-d-ar-5g"
      "ds-2sk8c144imxr"
      "ds-2sk8c144mh"
      "ds-2sk8c144mh-d-25c0-t5"
      "其余 13 个型号"
    "暂无规格对比数据"