mindmap
  root(("Exclusive-Distribution"))
    "型号数: 59"
    "型号列表"
      "DS-2CD3T26FDWD-L-L8-GLE"
      "DS-2CD3T26FDWDA3-L-L8-SGLE"
      "DS-2CD3T46FDWD-L-L8-GLE"
      "ds-2dc2204iw-s6"
      "ds-2dc2402iw-s6"
      "ds-2dc2c20my"
      "ds-2dc2c40my"
      "DS-2DC2D20IW-C0-S6"
      "DS-2DC2D40IW-C0-S6"
      "ds-2dc3326iz"
      "ds-2dc3a20iw-s6"
      "ds-2dc3a40iw-s6"
      "DS-2DC4120IW-D-B"
      "ds-2dc4120iw-s6-c"
      "ds-2dc4212iw-d"
      "DS-2DC4220-W-D-B"
      "ds-2dc4223iw-s6-c"
      "ds-2dc4412iw-d"
      "其余 41 个型号"