mindmap
  root(("Explosion-Proof-Bullet-Camera"))
    "所属大类: Front-End-Product"
    "子类: Explosion-Proof-Camera"
    "型号数: 63"
    "型号列表"
      "ds-2db3220-cx-s6-b"
      "ds-2db3220b-cx-s6-b"
      "ds-2db3220i-cx-s6-b"
      "ds-2db3425-cx-s6-b"
      "ds-2db3425i-cx-s6-b"
      "ds-2db4223-cx-t5"
      "ds-2db4223i-cx-t5"
      "ds-2db4237i-cwx-t5f"
      "其余 55 个型号"
    "暂无规格对比数据"