mindmap
  root(("gas-detector-series"))
    "所属大类: Fire-Protection"
    "子类: intelligent-fire-protection"
    "型号数: 5"
    "型号列表"
      "jm-hk100-n"
      "jt-hk40c-n"
      "jt-hk50b-g"
      "jy-hk40c-n"
      "jy-hk50b-g"
    "暂无规格对比数据"