mindmap
  root(("Linkage-System"))
    "型号数: 21"
    "型号列表"
      "ds-2sk8c144imx"
      "ds-2sk8c144imx-d-25c0-t5"
      "ds-2sk8c144imx-d-32c4-t5"
      "ds-2sk8c144imx-d-40c4-t5"
      "ds-2sk8c144imx-d-ar-5g"
      "ds-2sk8c144imxr"
      "ds-2sk8c144mh"
      "ds-2sk8c144mh-d-25c0-t5"
      "ds-2sk8c144mh-d-sp-glt-dg"
      "ds-2sk8c184imx"
      "ds-2sk8c184imxs"
      "ds-2sk8c244imx"
      "ds-2sk8c244imxr"
      "ds-2sk8c244mh"
      "ds-2sk8c246imx"
      "ds-2sk8c246imx-d-ar-zs"
      "ds-2sk8c246imxr"
      "ds-2sk8c246imxs"
      "其余 3 个型号"