mindmap
  root(("emergency-lighting-and-evacuation-indicator-system"))
    "型号数: 42"
    "型号列表"
      "hk-bljc-1leI05w-6132"
      "hk-bljc-1leI05w-6134"
      "hk-bljc-1leI05w-6136"
      "hk-bljc-1leI05w-6138"
      "hk-bljc-1leII05w-6113"
      "hk-bljc-1lreI05w-6131"
      "hk-bljc-1lreI05w-6133"
      "hk-bljc-1lreI05w-6135"
      "hk-bljc-1lreI05w-6137"
      "hk-bljc-1lreII05w-6111"
      "hk-bljc-1lroe-0-5w-616x"
      "hk-bljc-1lroe-1w-6192-ip"
      "hk-bljc-1lroe-1w-6195-ex"
      "hk-bljc-1oe-0-5w-6114"
      "hk-bljc-1oe-2w-6117"
      "hk-bljc-1oe-2w-6118"
      "hk-bljc-1oeII05w-6115"
      "hk-bljc-1oeII05w-6116"
      "其余 24 个型号"