mindmap
  root(("2-Series-Smart-Camera"))
    "所属大类: Front-End-Product"
    "子类: Fixed-Camera"
    "型号数: 63"
    "型号列表"
      "ds-2cd2126f-d-wda1-is"
      "ds-2cd2146f-d-wda1-is"
      "ds-2cd2326-d-wda4-l"
      "ds-2cd2326f-d-wda3-xs"
      "ds-2cd2326f-d-wda4-ls"
      "ds-2cd2345fv3-is-yw"
      "ds-2cd2346-d-wda4-l"
      "ds-2cd2346f-d-wda3-xs"
      "其余 55 个型号"
    "暂无规格对比数据"