mindmap
  root(("fire-protection-and-video-surveillance-series"))
    "型号数: 10"
    "型号列表"
      "hf-fvw201"
      "jtt-u-hk142-p"
      "jtt-u-hk142-p-ex"
      "np-fa100"
      "np-fvr112"
      "np-fvr212"
      "np-fvr213"
      "np-fvw200"
      "np-fvy200"
      "np-fvy300-4g"