mindmap
  root(("specialized-cameras"))
    "型号数: 20"
    "型号列表"
      "ds-2xc3026-l"
      "ds-2xc3026-lr"
      "ds-2xc3046-l"
      "ds-2xc3046-lr"
      "ds-2xc7025"
      "ds-2xc7045"
      "ds-2xc7225fwd-xhz-r-s"
      "ds-2xc7245fwd-xhz-r-s"
      "ds-2xc7285fwd-xhz-r-s"
      "ds-2xc8045fwd-lz-t0-yc"
      "ds-2xc8247fwd-x-zs-t4"
      "ds-2xs6a25-isgl-ch20s40"
      "ds-2xs6a25-isgl-ch40s80"
      "ds-2xs6a85-lsg-cm20s45"
      "ds-2xs6ad25-lsg-cm2s4"
      "ds-2xs6ad47-lsg-cm2s4"
      "ds-2xs6ae47-lsg-cm3s4-b"
      "ds-2xs6e43-ls-g-w-c-1-2"
      "其余 2 个型号"