mindmap
  root(("Positioning-System-Lite"))
    "型号数: 10"
    "型号列表"
      "ds-2dy5223bw-a-bo-s6"
      "ds-2dy5223iw-a-s6"
      "ds-2dy5232bw-s6"
      "ds-2dy5232iw-s6"
      "ids-2dy5240ixr-t5"
      "ids-2dy5425bxr-t5"
      "ids-2dy5425ixr-t5"
      "ids-2dy5432bxr-t5"
      "ids-2dy5432ixr-a-bo-t5"
      "ids-2dy5432ixr-t5"