mindmap
  root(("Distributed-Series"))
    "型号数: 198"
    "型号列表"
      "ds-2cd1225-d-la"
      "ds-2cd1245-d-la"
      "ds-2cd1325-d-v2-la"
      "ds-2cd1335-d-v2-la"
      "ds-2cd1345-d-v2-la"
      "ds-2cd1q335-lt"
      "ds-2cd1q445-lt"
      "ds-2cd1t25-d-la"
      "ds-2cd1t35-d-la"
      "ds-2cd1t45-d-la"
      "ds-2cd3126f-d-wdv3-i-s"
      "ds-2cd3325-d-i-h"
      "ds-2cd3326-d-wda4-l"
      "ds-2cd3326-d-wdv3-i"
      "ds-2cd3326f-d-wda3-i-s"
      "ds-2cd3326fwda4-ls"
      "ds-2cd3326fwdv3-i-s"
      "ds-2cd3326wdv3-lz"
      "其余 180 个型号"
    "主要差异字段"
      "一般规范 > 电流及功耗"
      "视频 > 主码流帧率分辨率"
      "音频 > 音频压缩码率"
      "一般规范 > 供电方式"
      "视频 > 视频压缩标准"
      "视频 > 子码流帧率分辨率"
      "音频 > 音频压缩标准"
      "视频 > 视频压缩码率"
      "一般规范 > 带包装重量"
      "镜头 > 焦距&视场角"