mindmap
  root(("Anti-CorrosionBallMachine"))
    "所属大类: Front-End-Product"
    "子类: Anti-Corrosion-Camera"
    "型号数: 15"
    "型号列表"
      "ds-2df5225mxr-dy"
      "ds-2df5225mxr-dy-glt-dg"
      "ds-2df5432mxr-dy"
      "ds-2df8c225mxr-ay"
      "ds-2df8c425bx-ay"
      "ds-2df8c425mx-ay"
      "ds-2df8c440mx-ay"
      "ds-2xc6122fwd-is-c"
      "其余 7 个型号"
    "暂无规格对比数据"