mindmap
  root(("7-Series-Smart-Camera"))
    "所属大类: Front-End-Product"
    "子类: Fixed-Camera"
    "型号数: 28"
    "型号列表"
      "ds-2cd7047ewd-a-jm-nmfc-d"
      "ds-2cd7047ewd-e2-i-x-jm-nmfc-d"
      "ds-2cd7047fwd-e2-i-x-jm-d"
      "ds-2cd7048fwd-e2-xz-c"
      "ds-2cd7147ewdv2-izs-dn"
      "ds-2cd7147fwdv2-iz-s-jm-d"
      "ds-2cd7147hwdv2-izs-jm-c"
      "ds-2cd7187hwdv2-izs-jm-c"
      "其余 20 个型号"
    "暂无规格对比数据"