mindmap
  root(("S000017619"))
    "型号数: 25"
    "型号列表"
      "ds-2cd7328dwd-x-s-jm-b"
      "ds-2cd73427dwd-l-s-jm"
      "ds-2cd7348dwd-x-s-jm-b"
      "ds-2cd7a427ewd-xz-s-jm-c"
      "ds-2cd7a427fwd-xz-s-jm-b"
      "ds-2cd7a428fwd-xz-s-jm-b"
      "ds-2cd7a447ewd-xz-s-jm-c"
      "ds-2cd7c447mwd-xz-g-jm-1050-c"
      "ds-2cd7c487mwd-s-xz-g-jm-1050-c"
      "ds-2cd7c844mwd-xzsg-c"
      "ds-2cd7c847mwd-xz-sw-g-jm-1050-c"
      "ds-2cd7c887mwd-s-ar-8-56-4-b"
      "ds-2cd7c887mwd-s-xz-g-jm-0856-4-c"
      "ds-2cd7c887mwd-s-xz-g-jm-1050-c"
      "ds-2cd7c888mwd-s-xz-g-jm-c"
      "ds-2cd7t28dwd-x-s-jm-b"
      "ds-2cd7t427dwd-l-s-jm"
      "ds-2cd7t48dwd-x-s-jm-b"
      "其余 7 个型号"