mindmap
  root(("5-series-smart-camera"))
    "型号数: 23"
    "型号列表"
      "ds-2cd5027efwd-a-b"
      "ds-2cd5032efwd-a-d"
      "ds-2cd5047efwd-a-jm-b"
      "ds-2cd5047efwd-e2-i-l-jm-b"
      "ds-2cd5125efwdv3-i-z-s-jm-cvbs"
      "ds-2cd5132efwdv2-i-z-s-d"
      "ds-2cd5145efwdv3-i-z-s-jm-cvbs"
      "ds-2cd5147efwdv2-izy-s-b"
      "ds-2cd5827efwd-iz-s-b"
      "ds-2cd5a12fwd-iz-s-zj-f"
      "ds-2cd5a25efwdv3-iz-s-jm-cvbs"
      "ds-2cd5a27efwd-i-l-z-s-zj-b"
      "ds-2cd5a32efwd-iz-s-zj-d"
      "ds-2cd5a45efwd-s-l-s"
      "ds-2cd5a47efwd-i-l-z-s-jm-zj-b"
      "ds-2cd5a47efwdv2-iz-s"
      "ds-2cd5a4xyz-ls"
      "ds-2cd5a87efwd-s-l-s"
      "其余 5 个型号"