mindmap
  root(("S000000539"))
    "型号数: 79"
    "型号列表"
      "ds-2df8432nx-afw-tl"
      "ds-2df8440ix-a-vr"
      "ds-2df8c425mx-a-5g"
      "ds-2df8c425mxr-ab-t5-b"
      "ds-2df8c432ix-a-vr-b"
      "ds-2df8c432mx-a-5g"
      "ds-2df8c432mxr-ab-t5-b"
      "ds-2df8c432mxs"
      "ds-2df8c440i5xs-al"
      "ds-2df8c440ix-a-vr"
      "ds-2df8c440ixs-a-jmc"
      "ds-2df8c440mx-a-5g"
      "ds-2df8c825mx-a-5g"
      "ds-2df8c832mx-a-5g"
      "ds-2df8c840i5xs-al"
      "ds-2df8c840mx-a-5g"
      "ds-2df8s426mx-a-f1"
      "ds-2df8s426mxr-a-f1"
      "其余 61 个型号"