mindmap
  root(("Exclusive-Distribution"))
    "所属大类: Front-End-Product"
    "子类: PTZ-Camera"
    "型号数: 59"
    "型号列表"
      "DS-2CD3T26FDWD-L-L8-GLE"
      "DS-2CD3T26FDWDA3-L-L8-SGLE"
      "DS-2CD3T46FDWD-L-L8-GLE"
      "ds-2dc2204iw-s6"
      "ds-2dc2402iw-s6"
      "ds-2dc2c20my"
      "ds-2dc2c40my"
      "DS-2DC2D20IW-C0-S6"
      "其余 51 个型号"
    "暂无规格对比数据"