mindmap
  root(("Positioning-System"))
    "所属大类: Front-End-Product"
    "子类: Positioning-System"
    "型号数: 8"
    "型号列表"
      "ids-2dy9240ix-t5"
      "ids-2dy9253i-x-t5"
      "ids-2dy9253x-t5"
      "ids-2dy9432ix-t5"
      "ids-2dy9440i-x-t5"
      "ids-2dy9840i-x-a-t5"
      "ids-2dy9c212"
      "ids-2dy9c412"
    "暂无规格对比数据"