mindmap
  root(("fire-protection-and-video-surveillance-series"))
    "所属大类: Fire-Protection"
    "子类: intelligent-fire-protection"
    "型号数: 10"
    "型号列表"
      "hf-fvw201"
      "jtt-u-hk142-p"
      "jtt-u-hk142-p-ex"
      "np-fa100"
      "np-fvr112"
      "np-fvr212"
      "np-fvr213"
      "np-fvw200"
      "其余 2 个型号"
    "暂无规格对比数据"