mindmap
  root(("S000008119"))
    "型号数: 12"
    "型号列表"
      "hk-dc-3201"
      "hk-df-3101"
      "hk-df-3121"
      "hk-dk-3001"
      "hk-gf-3605"
      "hk-gk-3501"
      "hk-gy-3703"
      "hk-gy-3713"
      "hk-gy-3723"
      "wy-bg5-2e-3w"
      "wy-xd5-4e-3w"
      "wy-xd5-5e-3w"