mindmap
  root(("S000007981"))
    "所属大类: Front-End-Product"
    "子类: s000007899"
    "型号数: 3"
    "型号列表"
      "ds-2xe901p-tdl50"
      "ds-2xe9423f-izhrs-tdl50"
      "ds-2xe9440f-izhrs-tdl100"
    "暂无规格对比数据"