mindmap
  root(("specialized-cameras"))
    "所属大类: Front-End-Product"
    "子类: Fixed-Camera"
    "型号数: 20"
    "型号列表"
      "ds-2xc3026-l"
      "ds-2xc3026-lr"
      "ds-2xc3046-l"
      "ds-2xc3046-lr"
      "ds-2xc7025"
      "ds-2xc7045"
      "ds-2xc7225fwd-xhz-r-s"
      "ds-2xc7245fwd-xhz-r-s"
      "其余 12 个型号"
    "暂无规格对比数据"