mindmap
  root(("5-series-smart-camera"))
    "所属大类: Front-End-Product"
    "子类: Fixed-Camera"
    "型号数: 23"
    "型号列表"
      "ds-2cd5027efwd-a-b"
      "ds-2cd5032efwd-a-d"
      "ds-2cd5047efwd-a-jm-b"
      "ds-2cd5047efwd-e2-i-l-jm-b"
      "ds-2cd5125efwdv3-i-z-s-jm-cvbs"
      "ds-2cd5132efwdv2-i-z-s-d"
      "ds-2cd5145efwdv3-i-z-s-jm-cvbs"
      "ds-2cd5147efwdv2-izy-s-b"
      "其余 15 个型号"
    "暂无规格对比数据"