mindmap
  root(("S000000983"))
    "型号数: 7"
    "型号列表"
      "ds-2xc6427f-l-s"
      "ds-2xc6447f-l-s"
      "ds-2xc7025"
      "ds-2xc7045"
      "ds-2xc7225fwd-xhz-r-s"
      "ds-2xc7245fwd-xhz-r-s"
      "ds-2xc7285fwd-xhz-r-s"