mindmap
  root(("fourth-generation-panoramic-ptz-camera"))
    "型号数: 11"
    "型号列表"
      "ids-2dp0818zixs-p5"
      "ids-2dp1618zixs-p5"
      "ids-2dp1636zixs-p5"
      "ids-2dp2427zixs"
      "ids-2dp3218zixs"
      "ids-2dp3218zixs-p4"
      "ids-2dp3236zixs-p5"
      "ids-2dp6436zixs"
      "ids-2vpd12-p5"
      "ids-2vpe13"
      "ids-2vpf14-p5"