mindmap
  root(("2-Series-Camera"))
    "所属大类: Front-End-Product"
    "子类: Fixed-Camera"
    "型号数: 153"
    "型号列表"
      "ds-2cd2125ef-d-v2-i-s"
      "ds-2cd2125f-d-v2-i-s"
      "ds-2cd2126f-d-wdv3-i-s"
      "ds-2cd2146f-d-wdv4-i-s"
      "ds-2cd2225cd-lglse-t"
      "ds-2cd2225xm-lhgl2t-c22s80"
      "ds-2cd2245cd-lglse-t"
      "ds-2cd2245xm-lgl2-t"
      "其余 145 个型号"
    "对比概要"
      "已对比 25 / 153 个型号"
      "共发现 6 个差异字段"
    "主要差异"
      "视频 / 视频压缩标准: 主码流：H.265/H.264子码流：H.265/H.264/MJPEG / 主码流：H.265/H.264子码流：H.265/H.264/MJPEG第三码流：H.265/H.264"
      "补光 / 补光灯类型: 红外灯 / 白光灯，红外灯 / 支持白光，红外补光"
      "事件 / Smart事件: 场景变更侦测，区域入侵侦测，越界侦测，进入区域侦测，离开区域侦测，物品遗留侦测，物品拿取侦测，徘徊侦测，停车侦测，人员聚集侦测，快速移动侦测；-S型号支持：音频异常侦测，音频抖升侦测，音频抖降侦测 / 场景变更侦测，虚焦侦测，区域入侵侦测，越界侦测，进入区域侦测，离开区域侦测，物品遗留侦测，物品拿取侦测，徘徊侦测，停车侦测，人员聚集侦测，快速移动侦测，音频异常侦测，音频抖升侦测，音频抖降侦测注：音频报警依赖外设 / 场景变更侦测，虚焦侦测，区域入侵侦测，越界侦测，进入区域侦测，离开区域侦测，物品遗留侦测，物品拿取侦测，徘徊侦测，停车侦测，人员聚集侦测，快速移动侦测；-S型号支持：音频异常侦测，音频抖升侦测，音频抖降侦测"
      "镜头 / 镜头尺寸接口: M12 / M16"
      "一般规范 / 供电方式: DC：12 V ± 25%，支持防反接保护PoE：802.3af，Class 3*DWD型号不支持PoE / DC：12 V ± 25%，支持防反接保护PoE：802.3af，Class 3 / DC：12 V ± 25%，支持防反接保护"
      "摄像机 / 传感器类型: 1/3\" Progressive Scan CMOS / 1/2.7\" Progressive Scan CMOS"