mindmap
  root(("6-Series-Specialized-Camera"))
    "型号数: 13"
    "型号列表"
      "ds-2cd2d45dwd-m-c"
      "ds-2cd6345ewd-i-v"
      "ds-2cd6365f-h-ihvs-d"
      "ds-2cd6365fv2-hc-i-v-h-s"
      "ds-2cd63c5f-h-ihvs-d"
      "ds-2cd6425fwd-f-22-c"
      "ds-2cd6445fwd-c1-c"
      "ds-2cd6445fwd-f-c1"
      "ds-2cd6445fwd-l-20-22-30-c"
      "ds-2cd6822de-s-w"
      "ds-2cd6b45-d-wd-m-u"
      "ds-2cd6d22de-s-w"
      "ds-2cd6d42-d-fwd-i-s-k"