mindmap
  root(("S000000434"))
    "型号数: 10"
    "型号列表"
      "ds-65vc0200"
      "ds-65vc0300u"
      "ds-65vc0400"
      "ds-65vcp1100m-s"
      "ds-65vta2400-t-a"
      "ds-d5acam100b"
      "ds-d5acam140b"
      "ds-d5acam150b"
      "ds-d5acam160b"
      "ds-d5acam200b"