mindmap
  root(("paperless-system-a"))
    "所属大类: Interactive-Tablet"
    "子类: paperless-system"
    "型号数: 8"
    "型号列表"
      "ds-65pl0007-mp"
      "ds-65pl0010-ac"
      "ds-65pl0010-ah"
      "ds-65pl0010-as"
      "ds-65pl0015-t"
      "ds-65pl0015-ta"
      "ds-65pl0017-t"
      "ds-65pl0017-ta"
    "暂无规格对比数据"