mindmap
  root(("S000012559"))
    "所属大类: Interactive-Tablet"
    "子类: paperless-system"
    "型号数: 5"
    "型号列表"
      "ds-65pl0010-c"
      "ds-65pl0010-cl"
      "ds-65pl0100-s"
      "ds-65pl0100-ys"
      "ds-65pl1000-ca"
    "暂无规格对比数据"