mindmap
  root(("LCD-interactive-yablet"))
    "所属大类: Interactive-Tablet"
    "子类: LCD-Interactive-Tablet"
    "型号数: 12"
    "型号列表"
      "ds-d5c55rb-d"
      "ds-d5c65rb-d"
      "ds-d5c75rb-d"
      "ds-d5c86rb-d"
      "ds-d5c98rb-d"
      "ds-d5d100rb-c"
      "ds-d5d110rb-b"
      "ds-d5d65rb-c"
      "其余 4 个型号"
    "暂无规格对比数据"