mindmap
  root(("LCD-interactive-yablet"))
    "型号数: 12"
    "型号列表"
      "ds-d5c55rb-d"
      "ds-d5c65rb-d"
      "ds-d5c75rb-d"
      "ds-d5c86rb-d"
      "ds-d5c98rb-d"
      "ds-d5d100rb-c"
      "ds-d5d110rb-b"
      "ds-d5d65rb-c"
      "ds-d5d75rb-c"
      "ds-d5d86rb-c"
      "ds-d5t86nb-a"
      "ds-d5t98nb-a"