mindmap
  root(("S000002157"))
    "所属大类: Interactive-Tablet"
    "子类: classroom-sharing"
    "型号数: 4"
    "型号列表"
      "ds-d6122th-b-c"
      "ds-d6122th-c-c"
      "ds-d6122th-c-t"
      "ds-d6122tl-b-c"
    "暂无规格对比数据"