mindmap
  root(("auxiliary-bracket"))
    "型号数: 28"
    "型号列表"
      "ds-d5abkd2b"
      "ds-d5abkd2d"
      "ds-d5abkf1b-55"
      "ds-d5abkf1b-65"
      "ds-d5abkf1b-75"
      "ds-d5abkf1b-86"
      "ds-d5abkf1b-98"
      "ds-d5abkh1b"
      "ds-d5abkh2d-l"
      "ds-d5abkw1b-214"
      "ds-d5abky2b-110"
      "ds-d5abky2b-138"
      "ds-d5abky2b-165"
      "ds-d5abky2b-s"
      "ds-d5abky3b-108"
      "ds-d5abky3b-135"
      "ds-d5abky3b-162"
      "ds-d5abky3d-s"
      "其余 10 个型号"