mindmap
  root(("outdoor-information-release-series"))
    "所属大类: Interactive-Tablet"
    "子类: information-release-series"
    "型号数: 10"
    "型号列表"
      "ds-d6043co-b-s"
      "ds-d6043fo-b-s"
      "ds-d6049co-b-s"
      "ds-d6049fo-b-s"
      "ds-d6055co-b-s"
      "ds-d6055fo-b-s"
      "ds-d6065co-b-s"
      "ds-d6065fo-b-s"
      "其余 2 个型号"
    "暂无规格对比数据"