mindmap
  root(("outdoor-information-release-series"))
    "型号数: 10"
    "型号列表"
      "ds-d6043co-b-s"
      "ds-d6043fo-b-s"
      "ds-d6049co-b-s"
      "ds-d6049fo-b-s"
      "ds-d6055co-b-s"
      "ds-d6055fo-b-s"
      "ds-d6065co-b-s"
      "ds-d6065fo-b-s"
      "ds-d6075co-b-s"
      "ds-d6075fo-b-s"