mindmap
  root(("android-digital-signage-display"))
    "型号数: 24"
    "型号列表"
      "ds-d6022fl-b"
      "ds-d6022tl-b"
      "ds-d6032fl-b"
      "ds-d6032fn-b"
      "ds-d6043cl-b-s"
      "ds-d6043tl-b-s"
      "ds-d6043ul-b-s"
      "ds-d6043un-b"
      "ds-d6049cl-b-s"
      "ds-d6049fl-b-s"
      "ds-d6049tl-b-s"
      "ds-d6055cl-b-s"
      "ds-d6055dl-b-s"
      "ds-d6055tl-b-s"
      "ds-d6055ul-b-s"
      "ds-d6065cl-b-s"
      "ds-d6065fl-b-s"
      "ds-d6065tl-b-s"
      "其余 6 个型号"