mindmap
  root(("android-digital-signage-display"))
    "所属大类: Interactive-Tablet"
    "子类: information-release-series"
    "型号数: 24"
    "型号列表"
      "ds-d6022fl-b"
      "ds-d6022tl-b"
      "ds-d6032fl-b"
      "ds-d6032fn-b"
      "ds-d6043cl-b-s"
      "ds-d6043tl-b-s"
      "ds-d6043ul-b-s"
      "ds-d6043un-b"
      "其余 16 个型号"
    "暂无规格对比数据"