mindmap
  root(("mcu"))
    "所属大类: Interactive-Tablet"
    "子类: video-conference-series"
    "型号数: 9"
    "型号列表"
      "ds-65vm00128-g"
      "ds-65vs0000s"
      "ds-65vt0020-d"
      "ds-65vta2400"
      "ds-65vta2401"
      "ds-65vta5604"
      "ds-65vtd0113"
      "ds-65vtd0113w"
      "其余 1 个型号"
    "暂无规格对比数据"