mindmap
  root(("Tri-Proof-Portable-Terminal"))
    "型号数: 20"
    "型号列表"
      "ds-mcw80w-e"
      "DS-MDH003"
      "ds-mdp003"
      "ds-mdp004"
      "ds-mdt005-5g"
      "ds-mdt006"
      "ds-mdt102"
      "ds-mdt200"
      "ds-mdt201"
      "ds-mh1b30-58"
      "ds-mh1b30-80"
      "ds-msh100"
      "ds-tri900-h6"
      "ds-trm900-h2"
      "ds-trm900-h8"
      "m000049050"
      "m000053090"
      "m000062760"
      "其余 2 个型号"