mindmap
  root(("Industrial-Wearable-Camera"))
    "型号数: 18"
    "型号列表"
      "ds-mcc206"
      "ds-mcc20d"
      "ds-mcc216"
      "ds-mcc21d"
      "ds-mch208"
      "ds-mch418"
      "ds-mcw4a5"
      "DS-MDS0A1"
      "ds-mh1011"
      "ds-mh1712"
      "ds-mlh110"
      "dsj-hikf1a1-d"
      "dsj-hikm1a1"
      "dsj-hikn1a1-c"
      "dsj-hikx1a1"
      "zcs-hikh2"
      "zcs-hikt1"
      "zcs-hikt2"