mindmap
  root(("Mobile-and-Portable-Monitoring"))
    "型号数: 8"
    "型号列表"
      "ids-mcd202-b-ex"
      "ids-mcd202-e"
      "ids-mcd20m"
      "ids-mcd212"
      "ids-mcd242"
      "ids-mcd402-e"
      "m000054131"
      "m000066706"