mindmap
  root(("industrial-switch"))
    "型号数: 18"
    "型号列表"
      "ds-3t0105"
      "ds-3t0108-b"
      "ds-3t0306"
      "ds-3t0310"
      "ds-3t1310-b"
      "ds-3t1310hp"
      "ds-3t1510f"
      "ds-3t1510hp"
      "ds-3t1512"
      "ds-3t1520"
      "ds-3t2506p"
      "ds-3t2512-b"
      "ds-3t2512p"
      "ds-3t2516tf"
      "ds-3t2524tf"
      "ds-3t2724"
      "ds-3t3528"
      "ds-3t3728"