mindmap
  root(("industry-wireless-bridge"))
    "型号数: 15"
    "型号列表"
      "ds-3wf-g1000"
      "ds-3wf01s-5ac-g-b"
      "ds-3wf01s-5ac-m-b"
      "ds-3wf01s-5acg-m-b"
      "ds-3wf03c"
      "ds-3wf03p-5ac"
      "ds-3wf03s-5ac-g-b"
      "ds-3wf03s-5ac-m-b"
      "ds-3wf05a-5ac"
      "ds-3wf05c-5ac"
      "ds-3wf0bc-2nt"
      "ds-3wf0bc-2nt-b"
      "ds-3wf0ec-5act-r"
      "ds-3wf10a-5ac"
      "ds-3wf20a-5ac"