mindmap
  root(("distribution-wireless-network-bridge"))
    "型号数: 9"
    "型号列表"
      "ds-3wf01c-2ne-d"
      "ds-3wf01s-5ace-m"
      "ds-3wf03c-5ace-dl"
      "ds-3wf03s-5ace-m"
      "ds-3wf0ac-2ne"
      "ds-3wf0bc-2nte"
      "ds-3wf0ec-5acte-r"
      "ds-3wf0es-5ace-g"
      "ds-3wf0es-5ace-h"