mindmap
  root(("switch"))
    "型号数: 17"
    "型号列表"
      "ds-3e0100-s"
      "ds-3e0500-s"
      "ds-3e0500p-s"
      "ds-3e0524tf"
      "ds-3e1500-s"
      "ds-3e1500p-s"
      "ds-3e1500sp-s"
      "ds-3e2500-h"
      "ds-3e2500p"
      "ds-3e2500p-h"
      "ds-3e2500p-s"
      "ds-3e2700-h"
      "ds-3e3500-h"
      "ds-3e3700-h"
      "ds-3e3756tf"
      "ds-3e3900-h"
      "ds-3e7603"