mindmap
  root(("switch"))
    "所属大类: network-product"
    "子类: switch-and-routing-product"
    "型号数: 17"
    "型号列表"
      "ds-3e0100-s"
      "ds-3e0500-s"
      "ds-3e0500p-s"
      "ds-3e0524tf"
      "ds-3e1500-s"
      "ds-3e1500p-s"
      "ds-3e1500sp-s"
      "ds-3e2500-h"
      "其余 9 个型号"
    "暂无规格对比数据"