mindmap
  root(("Industrial-Optic-Transceiver"))
    "所属大类: network-product"
    "子类: optical-network-products"
    "型号数: 6"
    "型号列表"
      "ds-3d01r-a-fc"
      "ds-3d01tp-a-sc"
      "ds-3d08t-a-fc"
      "ds-3d201t-a-fc"
      "ds-3d201tp-a-sc"
      "ds-3k02-p1"
    "暂无规格对比数据"