mindmap
  root(("distribution-switch"))
    "型号数: 57"
    "型号列表"
      "ds-3e0100d-e"
      "ds-3e0100p-e"
      "ds-3e0100sp-e"
      "ds-3e0105-e"
      "ds-3e0105d-e-v2"
      "ds-3e0105p-e-m"
      "ds-3e0106p-e"
      "ds-3e0108-e-b"
      "ds-3e0108d-e-v2"
      "ds-3e0109p-e-c"
      "ds-3e0109p-e-m"
      "ds-3e0109sp-e"
      "ds-3e0110sp-e"
      "ds-3e0116-e"
      "ds-3e0124-e"
      "ds-3e0300-e"
      "ds-3e0300hp-e"
      "ds-3e0300p-e"
      "其余 39 个型号"