mindmap
  root(("distribution-optic-transceiver"))
    "所属大类: network-product"
    "子类: optical-network-products"
    "型号数: 5"
    "型号列表"
      "ds-3d01-ae-df-sc"
      "ds-3d01r-20e-sc"
      "ds-3d01t-20e-sc"
      "ds-3d501r-3e-sc"
      "ds-3d501t-3e-sc"
    "暂无规格对比数据"