mindmap
  root(("Passive-optical-network-products"))
    "型号数: 15"
    "型号列表"
      "ds-3gt01-08"
      "ds-3gt01-16"
      "ds-3gt6800-12xf"
      "ds-3gt6800-16gp-4xf"
      "ds-3gt6800-mpu"
      "ds-3gt6800-pwr1300a"
      "ds-3gt6804"
      "ds-3gt6808"
      "ds-3gu1-sfp"
      "ds-3gu104"
      "ds-3gu104p"
      "ds-3gu108"
      "ds-3gu108p"
      "hk-sfp-1-25-2-5g-b"
      "hk-sfp-1-25-2-5g-c"