mindmap
  root(("industry-wireless-bridge"))
    "所属大类: network-product"
    "子类: wireless-transmission-product"
    "型号数: 15"
    "型号列表"
      "ds-3wf-g1000"
      "ds-3wf01s-5ac-g-b"
      "ds-3wf01s-5ac-m-b"
      "ds-3wf01s-5acg-m-b"
      "ds-3wf03c"
      "ds-3wf03p-5ac"
      "ds-3wf03s-5ac-g-b"
      "ds-3wf03s-5ac-m-b"
      "其余 7 个型号"
    "暂无规格对比数据"