mindmap
  root((中文))
    前端产品
      防爆网络摄像机
        防爆球机
        防爆筒机
        防爆云台
        矿用煤安产品系列
      固定网络摄像机
        2系列通用网络摄像机
        2系列智能网络摄像机
        5系列通用网络摄像机
        5系列智能网络摄像机
        6系列专用网络摄像机
        7系列智能网络摄像机
        8系列智能网络摄像机
        经销系列
        专用网络摄像机
      球型网络摄像机
        行业智能球机
        鹰眼系列