mindmap
  root(("S000017726"))
    "所属大类: on-board"
    "子类: s000017723"
    "型号数: 5"
    "型号列表"
      "sti-drdr250-h1a"
      "sti-drdr600-h1a"
      "sti-xmec0-h1a"
      "stj-dobr80-h1a"
      "stj80-1"
    "暂无规格对比数据"