mindmap
  root(("S000017725"))
    "型号数: 9"
    "型号列表"
      "sti-dcsir100-h1b"
      "sti-dcsir30-h1b"
      "sti-dhtir50-h1a"
      "sti-dsir50-h2b"
      "sti-dsir50-h2c-t"
      "sti-dsir50-h2c-t-ao"
      "sti-hsir110-h1a"
      "sti-hsir110-h2a"
      "sti-hsir70-h1a"