mindmap
  root(("S000017724"))
    "所属大类: on-board"
    "子类: s000017723"
    "型号数: 8"
    "型号列表"
      "sti-dllmr15-h1a-6t85a03-3j"
      "sti-dllmr8-h1a-6t85a03-3j"
      "sti-dllmr8-h1a-6t85a03s-3j"
      "sti-dlmr150-h1a-3t150a03cw-1a"
      "sti-dlmr150-h1a-3t250a25f-1e"
      "sti-dlmr30-h1a-8t150a16-1j"
      "sti-dlmr30-h1a-8t85a03f-1j"
      "sti1-4h"
    "暂无规格对比数据"