mindmap
  root(("中文"))
    "Access-Control-Device"
      "Access-Control-Terminal"
      "Access-Controller-Product"
      "Elevator-Control-Product"
      "Exclusive-Distribution-Product"
      "hundure"
      "MinMoe"
      "payment-terminal1"
      "person-and-credential-verification-terminal"
    "audio-sensing-products"
      "audio"
      "fiber-optic-sensing"
      "spatial-Iocation-perception"
      "spectral-camera"
    "Control-Products"
      "Decoder"
      "distributed-control-system"
      "integrated-video-system"
      "keyboard-series"
      "LED-screen"
      "send-controller-series"
      "video-wall-controller"
    "Data-Center"
      "AI-server"
      "cloud-computing-server"
      "General-Server"
    "Display-Product"
      "commercial-display-solution-for-exhibitions"
      "digital-information-pulish-screen"
      "energy-saving-cold-led-display-solution"
      "LCD-Monitor"
      "lcd-video-wall"
      "LED-Display"
      "LED-screen"
    "drone-products"
      "drones"
      "udf"
    "entrance-and-exit-parking"
      "digital-parking-alongside"
      "entrance-exit-management-and-control"
      "entrance-nonpublic"
      "parking-guidance"
      "parking-guidance-reverse"
      "roadside-parking"
    "Exclusive-Products"
    "Fire-Protection"
      "Conventional-Fire-Protection"
      "intelligent-fire-protection"
    "Front-End-Product"
      "Analog-Camera"
      "Anti-Corrosion-Camera"
      "elevator-electric-car-monitoring-solution"
      "Explosion-Proof-Camera"
      "Fixed-Camera"
      "gar"
      "hikvision-solar-powered-camera"
      "intelligent-detection-plan-for-object-thrown-from-building"
    "Interactive-Tablet"
      "classroom-information-release-screen-series"
      "classroom-sharing"
      "information-release-series"
      "LCD-Interactive-Tablet"
      "paperless-system"
      "video-conference-series"
    "mobile-product"
      "advanced-driver-assistance-system"
      "intelligent-public-transport"
      "mdvr-mnvr-accessories"
      "mobile-analog-camera"
      "mobile-industry-recorder"
      "mobile-network-camera"
      "mobile-surveillance-terminal"