mindmap
  root(("video-station"))
    "所属大类: pc-products"
    "子类: pc"
    "型号数: 11"
    "型号列表"
      "ds-axb132p-ss-video"
      "ds-axb142p-ss-video"
      "ds-axf112p-ss"
      "ds-axf113p-ss"
      "ds-axf122p-ss"
      "ds-axf132p-ss"
      "ds-axf141p-ss"
      "ds-axf142p-ss"
      "其余 3 个型号"
    "暂无规格对比数据"