mindmap
  root(("hybrid-control-panel-expander"))
    "所属大类: Security-Control-Device"
    "子类: Intrusion-Alarm-Device"
    "型号数: 9"
    "型号列表"
      "ds-rc501t"
      "ds-rha64-w4m"
      "ds-rk1-lrt"
      "ds-rm01-no"
      "ds-rm02-n"
      "ds-rm02-n2"
      "ds-rm08-n"
      "ds-rma-rswr"
      "其余 1 个型号"
    "暂无规格对比数据"