mindmap
  root(("Panic-Alarm-Station"))
    "型号数: 6"
    "型号列表"
      "ds-pdpc12p2f-ir-4g"
      "ds-pdpc12p2f-wl-4g"
      "ds-rdpc12p2f-ir-4g"
      "ds-rdpc12p2f-wl-4g"
      "ds-rdpc15p2f-ir-4g"
      "ds-rdpc15p2f-wl-4g"