mindmap
  root(("S000000791"))
    "所属大类: SmartTransportation"
    "子类: s000000789"
    "型号数: 8"
    "型号列表"
      "ds-tac100-g-3-1"
      "ds-tac100-srp-5-1"
      "ds-tac101-g-3-1"
      "ds-tac101-p-3-1"
      "ds-tac101-srg-n-6-1"
      "ds-tac102-p-8-1-2"
      "ds-tac200-p-8-1-2"
      "ds-tac201-p-8-1-5"
    "暂无规格对比数据"