mindmap
  root(("S000000788"))
    "所属大类: SmartTransportation"
    "子类: Light-Supplement-Product"
    "型号数: 5"
    "型号列表"
      "cxbg-1-1-ps-a-3b-i-cxbg-2-h-2-mc-a-3b-i"
      "cxbg-1-1-ps-a-ds-tl2000a"
      "cxbg-2-1-ps-a-3b-cxbg-2-2-mc-a-3b"
      "m000036612"
      "m000039166"
    "暂无规格对比数据"