mindmap
  root(("S000002892"))
    "型号数: 8"
    "型号列表"
      "-fbg-g1-sp01"
      "-fbq-2-320-sp00"
      "-fbt-sp02"
      "isd-as100k2c-l"
      "isd-as100k2c-lp"
      "isd-sl200t"
      "isd-sl300h"
      "isd-sl300t"