mindmap
  root(("S000007466"))
    "所属大类: SmartTransportation"
    "子类: s000007455"
    "型号数: 8"
    "型号列表"
      "cstxp-2-220-g-ld-1"
      "cstxp-2-24-g-ld-1"
      "cstxp-2-a2-d-ls-1"
      "cstxp-2-d2-d-ls-1"
      "yjp-ld-hs-lzdz"
      "yjp-ld-hs-lzdz-tyn"
      "yjp-ld-hs-lzdz-zl"
      "yjp-ld-hs-lzdz-zl-tyn"
    "暂无规格对比数据"