mindmap
  root(("Wired-Detector"))
    "型号数: 45"
    "型号列表"
      "ds-1t228n-b"
      "ds-1t610n-xyz"
      "ds-1t710n"
      "ds-1t720n"
      "ds-1t720n-b"
      "ds-pdbg8-pr"
      "ds-pdc10am-vg3"
      "ds-pdc15-eg2"
      "ds-pdc5nc-eg2"
      "ds-pdcl12-eg2"
      "ds-pdcl12dt-eg2"
      "ds-pdd12-eg2"
      "ds-pdd12p-eg2"
      "ds-pdd15am-eg2"
      "ds-pdeb-br"
      "DS-PDEB-PR"
      "ds-pdmc-pr"
      "ds-pdoc6dt"
      "其余 27 个型号"