mindmap
  root(("S000007453"))
    "型号数: 9"
    "型号列表"
      "ids-tcs44p-r-yzmq-led"
      "ids-tcs90p-fjdc-lcd-v2"
      "ids-tcsf0p-rl-jgjs-200mw"
      "ids-tcsf0p-rl-jgjsjx-200mw"
      "yjp280-l16032-p10-ls-xs-cs"
      "yjp280-l16032-p10-ls-xs-cs-tyn"
      "ytr300-3-2926-p-900ap-2"
      "ytr300-3-2926-p-900ap-2-nl"
      "ytr300-3-2926-p-9202apr-2"