mindmap
  root(("industrial-acoustic-detectors"))
    "所属大类: s000009379"
    "子类: s000009380"
    "型号数: 5"
    "型号列表"
      "ds-2mc1001-v"
      "ds-2mc1001-w"
      "ids-2mc4104np-i"
      "ids-2mc5164npo-t"
      "ids-2mc5164npwo-t"
    "暂无规格对比数据"