mindmap
  root(("Security-System-Accessory"))
    "所属大类: Security-Control-Device"
    "子类: Intrusion-Alarm-Device"
    "型号数: 14"
    "型号列表"
      "DS-29K00-Y"
      "ds-pm657"
      "ds-pma-cmk"
      "DS-RK-L"
      "DS-RK-LRT"
      "ds-rk1-cm"
      "ds-rk1-lrt"
      "DS-RS1-B"
      "其余 6 个型号"
    "暂无规格对比数据"