mindmap
  root(("Wireless-Detector"))
    "型号数: 33"
    "型号列表"
      "ds-pdtt15am-lm-wb"
      "ds-rd1-pm-w"
      "ds-rd2-d10p-w"
      "ds-rd2-p10p-w"
      "ds-rd2-p15c-w"
      "DS-RD2-P15C-W"
      "ds-rd401b1-wb"
      "ds-rd401bg8-wb"
      "ds-rd401c10amx-wb"
      "ds-rd401c15-wb"
      "ds-rd401cl12-wb"
      "ds-rd401dt12-wb"
      "ds-rd401dtc10amx-wb"
      "ds-rd401mc-wb"
      "ds-rd401mck-wb"
      "ds-rd401p15-wb"
      "ds-rd401pbg12-wb"
      "ds-rd401pc12-wb"
      "其余 15 个型号"