mindmap
  root(("human-vehicle-verification-machine"))
    "型号数: 10"
    "型号列表"
      "isd-sac6211-b"
      "isd-sac6211m"
      "isd-sac8011"
      "isd-sac8011d"
      "isd-sac8211-b"
      "isd-sac8211m"
      "isd-sai6311"
      "isd-sai6311f"
      "isd-sai8311"
      "isd-sai8311f"