mindmap
  root(("intelligent-security-inspection-machine-products"))
    "型号数: 21"
    "型号列表"
      "isd-sc100100d-4cv"
      "isd-sc100100d-h4cv"
      "isd-sc100100s-h4cv"
      "isd-sc140100s-vh"
      "isd-sc140100s-vht"
      "isd-sc140100s-vm"
      "isd-sc140100s-vmt"
      "isd-sc4233s-2cvt"
      "isd-sc5030s-1cv"
      "isd-sc6550d-4cv"
      "isd-sc6550d-h4cv"
      "isd-sc6550s-4cv"
      "isd-sc6550s-h4cv"
      "isd-sg100100d"
      "isd-sg100100s"
      "isd-sg5030d-2cv"
      "isd-sg5030s"
      "isd-sg5030sa"
      "其余 3 个型号"