mindmap
  root(("S000008342"))
    "型号数: 8"
    "型号列表"
      "ds-ah72024r-s"
      "ds-ah72036r-s"
      "ds-ah72048r-s"
      "ds-ah83024d-s"
      "ds-ah83024s-s"
      "ds-ah83036s-s"
      "ds-ah83048d-s"
      "ds-ah83048s-s"