mindmap
  root(("Security-Control-Panel-and-Expander"))
    "型号数: 16"
    "型号列表"
      "ds-19a08-bn"
      "ds-19a08-f"
      "ds-19a16-bn"
      "ds-29a08-bn"
      "ds-29a16-bn"
      "DS-29M04-RO"
      "DS-29M08-RO"
      "ds-po-kp"
      "ds-ra08-c-k2"
      "DS-RM08-RS0"
      "DS-RMA-RSWR0"
      "DS-RSA-DD"
      "m000006585"
      "m000006588"
      "m000011820"
      "m000011843"