mindmap
  root(("S000001589"))
    "所属大类: s000001555"
    "子类: s000001574"
    "型号数: 7"
    "型号列表"
      "ds-zcfis2-x-ls"
      "ds-zfllm3-x-ls"
      "ds-zflls2-x-ls"
      "ds-zfsss2-x-ls"
      "ds-zfwlm3-x-pv"
      "ds-zfwls2-x-pv"
      "ds-zfwss2-x-pv"
    "暂无规格对比数据"