mindmap
  root(("Security-System-Accessory"))
    "型号数: 14"
    "型号列表"
      "DS-29K00-Y"
      "ds-pm657"
      "ds-pma-cmk"
      "DS-RK-L"
      "DS-RK-LRT"
      "ds-rk1-cm"
      "ds-rk1-lrt"
      "DS-RS1-B"
      "DS-RS1-R"
      "ds-rs201-r"
      "m000010635"
      "m000011868"
      "m000043895"
      "m000048458"