mindmap
  root(("Wireless-Security-Control-Panel-and-Expander"))
    "型号数: 19"
    "型号列表"
      "ds-19k00-y"
      "ds-29k00-y"
      "ds-pm-wo8"
      "ds-pwa32-h"
      "ds-rk401t-wb"
      "ds-rm-wi1"
      "DS-RM-WI1"
      "ds-rm-wo2"
      "DS-RM-WO2"
      "ds-rm-wo8"
      "DS-RM-WO8"
      "ds-rm401r1h-wb"
      "ds-rm401z1-wb"
      "ds-rr401-wb"
      "ds-rs401-wb"
      "ds-rsg-wi"
      "ds-rsg-wo"
      "m000006686"
      "其余 1 个型号"