mindmap
  root(("S000017000"))
    "型号数: 5"
    "型号列表"
      "ids-tcs44p-r-yzmq-led"
      "ids-tcs90p-fjdc-lcd-v2"
      "ids-tcsf0p-rl-jgjs-200mw"
      "yjp280-l16032-p10-ls-xs-cs"
      "yjp280-l16032-p10-ls-xs-cs-tyn"