mindmap
  root(("Bus-Security-Control-Panel-and-Expander"))
    "型号数: 16"
    "型号列表"
      "ds-19a08-01bn"
      "ds-19m01-br"
      "ds-19m01-so"
      "ds-19m01-zs"
      "ds-19m02-zs"
      "ds-19m04-no-t"
      "ds-19m08-zs"
      "ds-19m32-no"
      "ds-29a08-01bn"
      "ds-29m01-br"
      "ds-29m01-so"
      "DS-29M01-ZS0"
      "DS-29M02-ZS0"
      "ds-29m04-no-t"
      "DS-29M08-ZS0"
      "ds-29m32-no"