mindmap
  root(("S000000566"))
    "型号数: 10"
    "型号列表"
      "ds-as71024r"
      "ds-as71036r"
      "ds-as71048r"
      "ds-as72016r"
      "ds-as72024r"
      "ds-as72036r"
      "ds-as72048r"
      "ds-as80624s"
      "ds-as81016s"
      "ds-as81024d"