mindmap
  root(("ip-receiver"))
    "所属大类: Security-Control-Device"
    "子类: Intrusion-Alarm-Device"
    "型号数: 4"
    "型号列表"
      "ds-rcm1-ip"
      "ds-rk1-cm"
      "ds-rna08-m"
      "m000048113"
    "暂无规格对比数据"