mindmap
  root(("thermography-turret-camera"))
    "所属大类: Thermal"
    "子类: thermography"
    "型号数: 3"
    "型号列表"
      "hm-td1228t-2-qa"
      "hm-td1228t-3-qa"
      "hm-td1228t-7-qa"
    "暂无规格对比数据"