mindmap
  root(("Swing-Barrier"))
    "所属大类: Turnstile"
    "子类: general-flap-barrier"
    "型号数: 13"
    "型号列表"
      "ds-k3b121l"
      "ds-k3b220lw"
      "ds-k3b221l"
      "ds-k3b411s"
      "ds-k3b421l"
      "ds-k3b423"
      "ds-k3b501s"
      "ds-k3b501sc"
      "其余 5 个型号"
    "暂无规格对比数据"