mindmap
  root(("speed-dome-camera"))
    "型号数: 6"
    "型号列表"
      "ds-2td4228-xx-s2"
      "ds-2td4238-xx-s2"
      "ds-2td4837-50c4-w-ar"
      "ds-2td4867-50c4-w-ar"
      "hm-td4137-50-w"
      "hm-td4167-50-w"