mindmap
  root(("thermography-bullet-camera1"))
    "所属大类: Thermal"
    "子类: thermography"
    "型号数: 10"
    "型号列表"
      "ds-2td55xxt-xx-v2"
      "ds-2td55xxt-xx-w"
      "ds-2td6237t-25h4l-w"
      "ds-2td6237t-50h4l-w"
      "ds-2td6267t-25h4l-w"
      "ds-2td6267t-50h4l-w"
      "hm-td56xxt-xx-w"
      "hm-td5737t-4-w"
      "其余 2 个型号"
    "暂无规格对比数据"