mindmap
  root(("thermography-bullet-camera1"))
    "型号数: 10"
    "型号列表"
      "ds-2td55xxt-xx-v2"
      "ds-2td55xxt-xx-w"
      "ds-2td6237t-25h4l-w"
      "ds-2td6237t-50h4l-w"
      "ds-2td6267t-25h4l-w"
      "ds-2td6267t-50h4l-w"
      "hm-td56xxt-xx-w"
      "hm-td5737t-4-w"
      "hm-td5737t-7-w"
      "hm-td5767t-7-w"