mindmap
  root(("swing-barrier"))
    "所属大类: Turnstile"
    "子类: smart-turnstile"
    "型号数: 6"
    "型号列表"
      "ds-k3b631t"
      "ds-k3b961t"
      "ds-k6b221tm"
      "ds-k6b223tm"
      "ds-k6b421tm"
      "ds-k6b423tm"
    "暂无规格对比数据"