mindmap
  root(("online-body-temperature-screening-camera"))
    "所属大类: Thermal"
    "子类: temperature-screening"
    "型号数: 3"
    "型号列表"
      "ds-2td2637b-10-p"
      "ds-2td2637b-15-p"
      "ds-b2617-xx-pa"
    "暂无规格对比数据"