mindmap
  root(("S000008220"))
    "所属大类: Thermal"
    "子类: thermography"
    "型号数: 6"
    "型号列表"
      "ds-2td55xxt-xx-w"
      "ds-2td6237t-25h4l-w"
      "ds-2td6237t-50h4l-w"
      "ds-2td6267t-25h4l-w"
      "ds-2td6267t-50h4l-w"
      "ds-2td62xxt-xxh2l"
    "暂无规格对比数据"