mindmap
  root(("pt-camera"))
    "型号数: 11"
    "型号列表"
      "ds-2td45x8-xxa4-w"
      "ds-2td9167-190zxxx-wxxx"
      "ds-2td95c8-190zxxx-w"
      "ds-2td966a-750zxxx"
      "ds-2td9867-180ze2f"
      "hm-td6237-50c4l-w"
      "hm-td6267-100c4l-w"
      "hm-td6267-25c4l-w"
      "hm-td6338-50c4-t2-glt"
      "hm-td6368-50c4-t2-glt"
      "hm-td81x7-xxe2xx-w1"