mindmap
  root(("S000000692"))
    "型号数: 11"
    "型号列表"
      "ds-2ts16-35vi-w"
      "ds-2ts16-50vi-w"
      "hm-ts03-25xf-w"
      "hm-ts03-35xf-w"
      "hm-ts06-35xf-w"
      "hm-ts23-35qg-wlv"
      "hm-ts23-35qg-wv"
      "hm-ts26-50qg-wlv"
      "hm-ts53-50qg-wlve"
      "hm-ts56-50qg-wlve"
      "hm-ts56-75qg-wlve"