mindmap
  root(("bullet-camera"))
    "型号数: 9"
    "型号列表"
      "ds-2td2137-35-p"
      "ds-2td2167-7-p"
      "ds-2td2608-1-qa"
      "ds-2td2608-2-qa-fp"
      "hm-td2617-3-qa"
      "hm-td2617-6-qa"
      "hm-td2628-3-qa"
      "hm-td2638-25-t1"
      "hm-tx3840-25-t1"