mindmap
  root(("handheld-temperature-screening-camera"))
    "所属大类: Thermal"
    "子类: thermography"
    "型号数: 9"
    "型号列表"
      "ds-2tp21-6avf-w"
      "ds-2tp22-7qf-w"
      "ds-2tp23-10vf-w-b"
      "ds-2tp74-25svf-w"
      "ds-2tp76-25svf-w"
      "hm-tp31-3auf"
      "hm-tp41-3aqf-w"
      "hm-tp42-3aqf-w"
      "其余 1 个型号"
    "暂无规格对比数据"