mindmap
  root(("picture-cloud-storage"))
    "型号数: 7"
    "型号列表"
      "ds-a72024rh-icvs"
      "ds-a72024rh-icvs-iot"
      "ds-a72036rh-cvs"
      "ds-a72036rh-icvs"
      "ds-a72036rh-icvs-iot"
      "ds-a72048rh-icvs"
      "ds-a72048rh-icvs-iot"