mindmap
  root(("S000009340"))
    "所属大类: Video-Recorder"
    "子类: DeepinMind"
    "型号数: 4"
    "型号列表"
      "ids-8600nx-i9-s-at-v40"
      "ids-8600nx-i9-s-at-v40-vt"
      "ids-9600nx-i16r-s-at-v40"
      "ids-9600nx-i8r-s-at-v40"
    "暂无规格对比数据"