mindmap
  root(("Special-NVR"))
    "型号数: 31"
    "型号列表"
      "ds-7600n-g2-4p-v2"
      "ds-7600n-g2-glt-v2"
      "ds-7600n-g2-v2"
      "ds-7600n-k1-glt-v2"
      "ds-7600n-k1-xp-glt-v2"
      "ds-7600n-k2-glt-v2"
      "ds-7600n-k2-xn-glt-v2"
      "ds-7600n-k2-xp-glt-v2"
      "ds-7700n-k4-glt-v2"
      "ds-7700n-k4-xp-glt-v2"
      "ds-7800n-f1-ssd"
      "ds-7800n-f1-w"
      "ds-7800n-f1-w-a"
      "ds-7800n-f1-xp-4g"
      "ds-7800n-f1-xp-ssd"
      "DS-7800N-K1-GLT"
      "DS-7800N-K1-XP-GLT"
      "ds-7800n-q1-4g"
      "其余 13 个型号"