mindmap
  root(("XVR"))
    "所属大类: Video-Recorder"
    "子类: Digital-hard-disk-recorder"
    "型号数: 29"
    "型号列表"
      "ds-7100hgh-f1-n"
      "ds-7100hgh-k1"
      "ds-7200hgh-sh-"
      "ds-7200hgh-sh1"
      "ds-7200hgh-snh-"
      "ds-7200hqh-sh-"
      "ds-7200hqh-sh2"
      "ds-7300hgh-sh-"
      "其余 21 个型号"
    "暂无规格对比数据"