mindmap
  root(("Distribute-NVR"))
    "所属大类: Video-Recorder"
    "子类: Network-hard-disk-recorder"
    "型号数: 101"
    "型号列表"
      "DS-7100N-F1-B"
      "ds-7100n-f1-c"
      "ds-7100n-f1-e"
      "DS-7100N-F1-xP-B"
      "DS-7100N-F1-xP-C"
      "ds-7100n-f1-xp-e"
      "DS-7100N-SN-C-B0"
      "ds-7100n-sn-d"
      "其余 93 个型号"
    "对比概要"
      "已对比 25 / 101 个型号"
      "共发现 40 个差异字段"
    "主要差异"
      "外部接口 / USB接口: 1个，1个USB 2.0（后） / 1个USB2.0（前置），1个USB2.0 （后置） / 3个，1个USB 3.0（后），2个USB 2.0（前）"
      "外部接口 / 网络接口: 1个，RJ45 10M/100M/1000M自适应以太网口 / 2个，RJ45 10M/100M/1000M自适应以太网口 / 1个，RJ45 10M/100M自适应以太网口"
      "系统参数 / 录像分辨率: 8MP/6MP/5MP/4MP/3MP/1080p/UXGA/720p/VGA/4CIF/DCIF/2CIF/CIF/QCIF / 8MP/7MP/6MP/5MP/4MP/3MP/1080p/UXGA/720p/VGA/4CIF/DCIF/2CIF/CIF/QCIF / 6MP/5MP/4MP/3MP/1080p/UXGA/720p/VGA/4CIF/DCIF/2CIF/CIF/QCIF"
      "系统参数 / 视频接入路数: 8 / 16 / 4;16;8"
      "视频参数 / VGA输出: 1路VGA，分辨率: 1920*1080/60Hz，1280*1024/60Hz，1280*720/60Hz，1024*768/60Hz注：VGA与HDMI独立异源输出 / 1路VGA，分辨率: 1920*1080/60Hz，1600×1200/60Hz，1280*1024/60Hz，1280*720/60Hz / 1路VGA，分辨率: 1920*1080/60Hz，1280*1024/60Hz，1280*720/60Hz，1024*768/60Hz注：辅口与主口异源输出"
      "系统参数 / 网络输入带宽: 80Mbps / 160Mbps / 40Mbps"