mindmap
  root(("Financial-NVR"))
    "所属大类: Video-Recorder"
    "子类: Industry-Host"
    "型号数: 6"
    "型号列表"
      "DS-8100AHQL-K4"
      "ds-8600anl-k4-4p"
      "ds-irt24s"
      "ids-6700nx-a-v2"
      "iDS-8104AHQXL-K4"
      "ids-8600nx-i8-a-v2-"
    "暂无规格对比数据"