mindmap
  root(("S000010539"))
    "型号数: 8"
    "型号列表"
      "ivms-4000a-s1"
      "ivms-4000a-s1-ac"
      "ivms-4000a-s1-client"
      "ivms-4000a-s1-h"
      "ivms-4000a-s1-lite"
      "ivms-4000a-s2-pro"
      "ivms-4000b-s1-lite"
      "ivms-4000b-s2-pro"