mindmap
  root(("general-cloud-storage"))
    "所属大类: Video-Recorder"
    "子类: cloud-storage-products"
    "型号数: 9"
    "型号列表"
      "ds-a71024r-cvs-iot"
      "ds-a71024r-icvs"
      "ds-a71024r-icvs-iot"
      "ds-a71036r-cvs-iot"
      "ds-a71036r-icvs"
      "ds-a71036r-icvs-iot"
      "ds-a71048r-cvs-iot"
      "ds-a71048r-icvs"
      "其余 1 个型号"
    "暂无规格对比数据"