mindmap
  root(("Indoor-Station"))
    "所属大类: Video-Intercom"
    "子类: Building-Intercom"
    "型号数: 17"
    "型号列表"
      "ds-kh3220-l"
      "ds-kh6000-a"
      "ds-kh6320-c1"
      "ds-kh6350-a1"
      "ds-kh6350-c1"
      "ds-kh6350-c2"
      "ds-kh8540-a1"
      "ds-kh8540-c1"
      "其余 9 个型号"
    "暂无规格对比数据"