mindmap
  root(("S000004218"))
    "所属大类: Video-Recorder"
    "子类: Industry-Host"
    "型号数: 6"
    "型号列表"
      "ds-8100shfhl-k4r"
      "ds-8100thfhl-k4"
      "ds-96spn00l-i2"
      "ds-nb8600snt-e"
      "ds-nb9000s"
      "ds-nb9600snt-d"
    "暂无规格对比数据"