mindmap
  root(("Panic-Alarm-Station"))
    "所属大类: Video-Intercom"
    "子类: Emergency-Alarm"
    "型号数: 25"
    "型号列表"
      "ds-pea103-1"
      "ds-pea103-2"
      "ds-pea103-s1"
      "ds-pea103-s2"
      "m000008750"
      "m000008751"
      "m000008758"
      "m000011258"
      "其余 17 个型号"
    "暂无规格对比数据"