mindmap
  root(("Eco-NVR"))
    "型号数: 8"
    "型号列表"
      "ds-7600n-e1-v3"
      "ds-7600n-e1-xp-v3"
      "ds-7600n-e2-v3"
      "ds-7600n-e2-xp-v3"
      "ds-7700n-e4-16p-v3"
      "ds-7700n-e4-8p-v3"
      "ds-7700n-e4-v3"
      "ds-8600n-e8-v3"