mindmap
  root(("Distribute-NVR"))
    "型号数: 101"
    "型号列表"
      "DS-7100N-F1-B"
      "ds-7100n-f1-c"
      "ds-7100n-f1-e"
      "DS-7100N-F1-xP-B"
      "DS-7100N-F1-xP-C"
      "ds-7100n-f1-xp-e"
      "DS-7100N-SN-C-B0"
      "ds-7100n-sn-d"
      "ds-7800n-f1-b"
      "ds-7800n-f1-c"
      "ds-7800n-f1-d"
      "DS-7800N-F1-xP-B"
      "ds-7800n-f1-xp-c"
      "ds-7800n-f1-xp-d"
      "ds-7800n-g1"
      "ds-7800n-g1-xp"
      "DS-7800N-K1-C-D"
      "DS-7800N-K1-xN-D"
      "其余 83 个型号"
    "主要差异字段"
      "外部接口 > USB接口"
      "外部接口 > 网络接口"
      "系统参数 > 录像分辨率"
      "系统参数 > 视频接入路数"
      "视频参数 > VGA输出"
      "系统参数 > 网络输入带宽"
      "一般规范 > 功耗（不含硬盘）"
      "一般规范 > 重量（不含硬盘）"
      "视频参数 > 视频解码格式"
      "视频参数 > HDMI输出"