mindmap
  root(("Ultra-NVR"))
    "所属大类: Video-Recorder"
    "子类: Network-hard-disk-recorder"
    "型号数: 7"
    "型号列表"
      "ds-96000n-h16r"
      "ds-96000n-h20r"
      "ds-96000n-h24r"
      "ds-96000n-h30r"
      "ds-9600n-i12r-v3"
      "ds-9600n-i16r-v3"
      "ds-9600n-i8r-v3-b"
    "暂无规格对比数据"