mindmap
  root(("Outer-Door-Terminal"))
    "所属大类: Video-Intercom"
    "子类: Building-Intercom"
    "型号数: 18"
    "型号列表"
      "ds-kabd9403"
      "ds-kd3002"
      "ds-kd9203-1"
      "ds-kd9213"
      "ds-kd9403-a1"
      "ds-kd9413-a1"
      "ds-kd9423"
      "ds-kd9603-1"
      "其余 10 个型号"
    "暂无规格对比数据"