mindmap
  root(("General-NVR"))
    "型号数: 19"
    "型号列表"
      "ds-7600nx-i3-8k"
      "ds-7600nx-k1-4p-v3"
      "ds-7600nx-k1-8p-v3"
      "ds-7600nx-k1-v3"
      "ds-7600nx-k2-16p-v3"
      "ds-7600nx-k2-8p-v3"
      "ds-7600nx-k2-v3"
      "ds-7700nx-i4-v2"
      "ds-7700nx-i5-8k"
      "ds-7700nx-k5-16p-v2"
      "ds-7700nx-k5-8p-v2"
      "ds-7700nx-k5-v2"
      "ds-8600n-i16-v3-b"
      "ds-8600n-i9-v3"
      "ds-8600n-k8-v2"
      "ds-8600nx-i16-8k"
      "ds-8600nx-i8-v2"
      "ds-8600nx-i9-8k"
      "其余 1 个型号"