mindmap
  root(("Outer-Door-Terminal"))
    "型号数: 18"
    "型号列表"
      "ds-kabd9403"
      "ds-kd3002"
      "ds-kd9203-1"
      "ds-kd9213"
      "ds-kd9403-a1"
      "ds-kd9413-a1"
      "ds-kd9423"
      "ds-kd9603-1"
      "DS-KD9613-A1"
      "ds-kd9613-afb1"
      "ds-kd9623-f"
      "ds-kd9633-a1"
      "ds-kd9643-af1"
      "ds-kd9653"
      "ds-kd9803-f"
      "ds-kv6113-p1"
      "ds-kv8133-m"
      "ds-kv8233-m"