mindmap
  root(("general-intelligent-3x"))
    "型号数: 7"
    "型号列表"
      "ids-8600nx-i9-x-v40"
      "ids-96000nx-i16-v3"
      "ids-96000nx-i16-v30"
      "ids-96000nx-i24-v30"
      "iDS-9600NX-I16-S"
      "ids-9600nx-i16r-x-v40"
      "ids-9600nx-i8r-x-v40"