mindmap
  root(("S000009580"))
    "所属大类: Video-Recorder"
    "子类: s000009499"
    "型号数: 4"
    "型号列表"
      "ds-b81-hr0000"
      "ds-b81-hr0000-fg"
      "ds-b81-rtj"
      "ds-b85-mb0000"
    "暂无规格对比数据"