mindmap
  root(("Junction"))
    "Models: 55"
    "Models"
      "DS-1240ZJ"
      "DS-1259ZJ"
      "DS-1260ZJ"
      "ds-1260zj-y"
      "ds-1260zj-y-black-"
      "DS-1280ZJ-BQ30"
      "ds-1280zj-de7"
      "DS-1280ZJ-DM18"
      "ds-1280zj-dm18-black-"
      "DS-1280ZJ-DM21"
      "ds-1280zj-dm21-black-"
      "DS-1280ZJ-DM22"
      "DS-1280ZJ-DM25"
      "DS-1280ZJ-DM25-M1-"
      "DS-1280ZJ-DM45"
      "ds-1280zj-dm46"
      "ds-1280zj-dm46-black-"
      "ds-1280zj-dm46-y"
      "37 more models"