mindmap
  root(("Amplifier"))
    "Models: 13"
    "Models"
      "ds-qae0a120g1-vb6"
      "ds-qae0a240g1-vb6"
      "ds-qae0a40g1w-rb"
      "ds-qae0a60g1-vb"
      "ds-qae1a40g1-vb"
      "ds-qae1a80g1-vb"
      "ds-qae1a80g1-vb--b-"
      "ds-qae1a80g1-vb-st"
      "ds-qae1dg1"
      "ds-qaz1a1000g1-vb4"
      "ds-qaz1a1000g1-vb4-b-"
      "ds-qaz1a500g1-vb2"
      "ds-qaz1a500g1-vb2-b-"