mindmap
  root(("Housing"))
    "Models: 12"
    "Models"
      "DS-1330HZ"
      "DS-1331HZ-C"
      "DS-1331HZ-CE"
      "DS-1331HZ-CI"
      "ds-1331hz-cz"
      "DS-1331HZ-H"
      "DS-1331HZ-HI"
      "DS-1331HZ-HW"
      "DS-1331HZ-R"
      "DS-1331HZ-W"
      "ds-1332hz"
      "DS-1340HZ"