mindmap
  root(("Pro Speakers"))
    "Models: 20"
    "Models"
      "ds-qaps1r160-18du"
      "ds-qaps1r20-8"
      "ds-qaps1r30-10"
      "ds-qaps1r40-12"
      "ds-qaps1r40-12r"
      "ds-qaps1r50-15"
      "ds-qaps1r50-15u"
      "ds-qaps1r80-18u"
      "ds-qaps4r15-2"
      "ds-qaps4r20-4"
      "ds-qaps4r20e-4n"
      "ds-qaps4r30-4"
      "ds-qaps4r30e-4n"
      "ds-qaps4r40-4"
      "ds-qaps4u20-2"
      "ds-qaps6r6-6"
      "ds-qaps6r6-6p"
      "ds-qapsjr20-4"
      "2 more models"