mindmap
  root(("Common Accessory"))
    "Category: Alarm Products"
    "Subcategory: Intrusion Accessory"
    "Models: 15"
    "Models"
      "ds-pa-battery"
      "ds-pc201n"
      "ds-pma-d"
      "ds-pt-m1"
      "ds-pt-m1-europe-black"
      "ds-pt031"
      "ds-pt061"
      "ds-pt071-s"
      "7 more models"
    "No specification comparison yet"