mindmap
  root(("Ultra Series"))
    "Models: 11"
    "Models"
      "DS-K2700"
      "ds-k2701x"
      "ds-k2701x-p-"
      "ds-k2702wx-e1"
      "ds-k2702wx-e1-p-"
      "ds-k2702x"
      "ds-k2702x-p-"
      "ds-k2704x"
      "ds-k2704x-p-"
      "ds-k2708x"
      "DS-K27M"