mindmap
  root(("Pro Series"))
    "Models: 8"
    "Models"
      "DS-K4E100"
      "ds-k4g100"
      "DS-K4H250"
      "ds-k4h250-lz"
      "ds-k4h250d"
      "DS-K4H450"
      "DS-K4H450-LZ"
      "DS-K4T100"