mindmap
  root(("Value Series"))
    "Models: 71"
    "Models"
      "ds-k1a340fwx"
      "ds-k1a340fx"
      "ds-k1a340wx"
      "ds-k1a340x"
      "ds-k1t320efwx"
      "ds-k1t320efwx-b"
      "ds-k1t320efx"
      "ds-k1t320ewx"
      "ds-k1t320ex"
      "ds-k1t320mfwx"
      "ds-k1t320mfwx-b"
      "ds-k1t320mfx"
      "ds-k1t320mwx"
      "ds-k1t320mx"
      "ds-k1t321efwx"
      "ds-k1t321efwx-b"
      "ds-k1t321efx"
      "ds-k1t321ewx"
      "53 more models"