mindmap
  root(("Entrance Accessories"))
    "Models: 10"
    "Models"
      "ds-tmg002-5"
      "ds-tmg002-6l"
      "ds-tmg012-a1"
      "ds-tmg013-5"
      "ds-tmg022"
      "ds-tmg023"
      "ds-tmg110"
      "ds-tmg120--anpr-"
      "ds-tmg120--barrier-"
      "Tmg080 3"