mindmap
  root(("Detector Accessory"))
    "Category: Alarm Products"
    "Subcategory: Intrusion Accessory"
    "Models: 29"
    "Models"
      "ds-pdb-ex-adapter"
      "ds-pdb-ex-fixedbracket"
      "ds-pdb-ex-lbkt"
      "ds-pdb-ex-lbktw"
      "ds-pdb-ex-sbkt"
      "ds-pdb-ex-shelter"
      "ds-pdb-ex-wallbracket"
      "ds-pdb-in-ceilingbracket"
      "21 more models"
    "No specification comparison yet"