mindmap
  root(("General Wired Detectors"))
    "Models: 22"
    "Models"
      "ds-pd1-eb"
      "ds-pd1-eb-pf"
      "ds-pd1-mc-rs"
      "ds-pd1-mc-ws"
      "ds-pd701dt18am"
      "ds-pdbg8-eg2"
      "ds-pdbgts"
      "ds-pdc10am-vg3"
      "ds-pdc10dm-vg3"
      "ds-pdc15-eg2-b-"
      "ds-pdc5nc-eg2"
      "ds-pdcl12-eg2"
      "ds-pdcl12dt-eg2"
      "ds-pdd12p-eg2"
      "ds-pdd15am-eg2"
      "ds-pdp18-eg2-b-"
      "ds-pdpg12p-eg2"
      "ds-pdsk-p"
      "4 more models"