mindmap
  root(("Ax Home"))
    "Models: 16"
    "Models"
      "ds-pa201p-16wb"
      "ds-pa201p-16we"
      "ds-pa201p-32wb"
      "ds-pa201pg-16wb"
      "ds-pa201pg-16we"
      "ds-pa201pg-32wb"
      "ds-pa201pg-32we"
      "ds-pa201pg-kit-16we"
      "ds-pa201ps-16wb"
      "ds-pa201ps-16we"
      "ds-pa201ps-32wb"
      "ds-pd201mc-wa"
      "ds-pd201pc10-we"
      "ds-ps201-wb"
      "ds-ps201-we"
      "How To Videos"