mindmap
  root(("Pro Series"))
    "Models: 13"
    "Models"
      "ds-k1t105ae"
      "ds-k1t105am"
      "ds-k1t502dbwx"
      "ds-k1t502dbwx-ce1"
      "ds-k1t502dbwx-cqr"
      "ds-k1t502dbwx-cqre1"
      "ds-k1t502dbwx-e1"
      "ds-k1t502dbwx-qr"
      "ds-k1t502dbwx-qre1"
      "ds-k1t807ebwx-qre1"
      "ds-k1t807ex-e1"
      "ds-k1t807mbwx-qre1"
      "ds-k1t807mx-e1"