mindmap
  root(("Value Series"))
    "Models: 10"
    "Models"
      "ds-k1a8503ef"
      "ds-k1a8503ef-b"
      "ds-k1a8503f"
      "ds-k1a8503f-b"
      "ds-k1a8503mf"
      "ds-k1a8503mf-b"
      "ds-k1t8003ef"
      "ds-k1t8003f"
      "ds-k1t8003mf"
      "ds-k1t805mbfwx"