mindmap
  root(("Pro Series"))
    "Models: 28"
    "Models"
      "DS-K1101"
      "DS-K1102"
      "ds-k1102a"
      "DS-K1103"
      "DS-K1104"
      "ds-k1105edb"
      "ds-k1105edkb"
      "ds-k1105edkb-qr"
      "ds-k1105emb"
      "ds-k1105emkb"
      "ds-k1105emkb-qr"
      "DS-K1107"
      "ds-k1107ae"
      "ds-k1107aek"
      "ds-k1107am"
      "ds-k1107amk"
      "ds-k1108"
      "ds-k1108a"
      "10 more models"