mindmap
  root(("Bracket"))
    "Models: 236"
    "Models"
      "ds-1214-zj-fh--p"
      "DS-1214ZJ"
      "DS-1214ZJ-T"
      "DS-1227ZJ"
      "DS-1227ZJ-DM26"
      "DS-1227ZJ-DM32"
      "DS-1227ZJ-DM37"
      "ds-1227zj-dm42"
      "ds-1227zj-dm44"
      "DS-1227ZJ-P1"
      "DS-1227ZJ-PT6"
      "DS-1232ZJ"
      "DS-1232ZJ-P"
      "DS-1232ZJ-T"
      "DS-1232ZJ-TP"
      "DS-1233ZJ"
      "DS-1241ZJ"
      "DS-1249ZJ"
      "218 more models"
    "Top diff fields"
      "Parameters > Dimension"
      "Parameters > Material"
      "Parameters > Appearance"
      "Parameters > Description"
      "Parameters > Range of Application"