mindmap
  root(("Detector Accessory"))
    "Models: 15"
    "Models"
      "ds-pdb-ex-lbkt"
      "ds-pdb-ex-lbktw"
      "ds-pdb-ex-sbkt"
      "ds-pdb-in-ubkt1"
      "ds-pdb-in-ubkt2"
      "ds-pdb-in-wristband"
      "ds-pdb-mc-adapter"
      "ds-pdb-mc-brown"
      "ds-pdb-mc-brown-b-"
      "ds-pdb-mck-brown-b-"
      "ds-pdb-mcs-adapter"
      "ds-pdb-mcs-brown"
      "ds-pdp-ex-es1"
      "ds-pdp-in-cr123a"
      "ds-pt1001-o"