mindmap
  root(("Public Address And Voice Alarm System"))
    "Models: 11"
    "Models"
      "ds-qae0120g1r-en"
      "ds-qae0a360g1-v6-en"
      "ds-qae0a360g1-v6-enb"
      "ds-qae0a360g1-v6-enex"
      "ds-qae0a450g1-v-en"
      "ds-qae0a450g1-v-enb"
      "ds-qae0mp0g1-en"
      "ds-qae0mp0g1-enex"
      "ds-qaeolm-en"
      "ds-qaeols-en"
      "ds-qasignal-en"