mindmap
  root(("Ultra Series"))
    "Models: 25"
    "Models"
      "ds-k1t607tef"
      "ds-k1t671tm-3xf-"
      "ds-k1t671tmfw"
      "ds-k1t671tmw"
      "ds-k1t672e"
      "ds-k1t672m"
      "ds-k1t672mw"
      "ds-k1t673tdgx"
      "ds-k1t673tdwx"
      "ds-k1t673tdwx-e1"
      "ds-k1t673tdwx-proe1"
      "ds-k1t673tdx"
      "ds-k1t673tdx-e1"
      "ds-k1t680d-e1"
      "ds-k1t680df-e1"
      "ds-k1t680dfg"
      "ds-k1t680dfw"
      "ds-k1t680dg"
      "7 more models"