mindmap
  root(("Brackets"))
    "Models: 14"
    "Models"
      "ds-kab323-b1"
      "ds-kab323-s1"
      "ds-kab323-w1"
      "ds-kab344-s1"
      "ds-kab34x-s1"
      "ds-kab502-s2"
      "ds-kab6-d1"
      "ds-kab6-w1"
      "ds-kab6-zu1"
      "ds-kab6-zu2"
      "ds-kab6-zu3"
      "ds-kab671-b"
      "ds-kab671-s"
      "ds-kab673-s1"