mindmap
  root(("Pro Series"))
    "Models: 18"
    "Models"
      "DS-K2210"
      "ds-k2220x"
      "ds-k2220x-p-"
      "ds-k2601"
      "ds-k2601-g"
      "ds-k2601t--main-board-"
      "ds-k2602-g"
      "ds-k2602t"
      "ds-k2602t--main-board-"
      "ds-k2604-g"
      "ds-k2604t--main-board-"
      "ds-k2621x"
      "ds-k2621x-p-"
      "ds-k2622x"
      "ds-k2622x-p-"
      "ds-k2624x"
      "ds-k2624x-p-"
      "DS-K2M0016A"