mindmap
  root(("Detector Accessory"))
    "Category: Alarm Products"
    "Subcategory: Intrusion Accessory"
    "Models: 15"
    "Models"
      "ds-pdb-ex-lbkt"
      "ds-pdb-ex-lbktw"
      "ds-pdb-ex-sbkt"
      "ds-pdb-in-ubkt1"
      "ds-pdb-in-ubkt2"
      "ds-pdb-in-wristband"
      "ds-pdb-mc-adapter"
      "ds-pdb-mc-brown"
      "7 more models"
    "No specification comparison yet"