mindmap
  root(("Public Address"))
    "Models: 6"
    "Models"
      "ds-2fp2021-ow"
      "ds-qaz1307g1-e"
      "ds-qaz1307g1t-e"
      "ds-qaz1310g1t-e"
      "ds-qaz1310g1t-ey"
      "ds-qaz1325g1t"