mindmap
  root(("Ax Hybrid Pro"))
    "Models: 18"
    "Models"
      "Ax Hybrid Pro Device Compatibility List"
      "ds-pdpc12p-eg2"
      "ds-pha48-ep-b-"
      "ds-pha64-kit-wb-b-"
      "ds-pha64-kit-we-b-"
      "ds-pha64-lp-b-"
      "ds-pk1-lrt-hwb"
      "ds-pk1-lrt-hwe"
      "ds-pm1-i8o2-h"
      "ds-pm1-o4h-h"
      "ds-pm1-o4l-h"
      "ds-pm1-rt-hwb"
      "ds-pm1-rt-hwe"
      "ds-pm2-g"
      "ds-pm2-p"
      "ds-pm2-s-au-"
      "ds-pm2-s-eu-"
      "How To Videos"