mindmap
  root(("Brackets"))
    "Models: 24"
    "Models"
      "ds-kab10-d"
      "ds-kab11-d"
      "ds-kabd8003-rs1-s"
      "ds-kabd8003-rs2-s"
      "ds-kabd8003-rs3"
      "ds-kabd8003-rs3-s"
      "ds-kabd9203-rs"
      "ds-kabd9633-rs"
      "ds-kabh8380-g"
      "ds-kabh8380-t"
      "ds-kabh9510-t"
      "ds-kabv24-a"
      "ds-kabv6113-rs"
      "ds-kabv6114-rs"
      "ds-kabv6133-g-surface"
      "ds-kabv6133-rs"
      "ds-kabv9503-rs"
      "ds-kd-acf1-s"
      "6 more models"