mindmap
  root(("Others"))
    "Models: 12"
    "Models"
      "ds-1619zj-b--p-y"
      "ds-1619zj-b--y"
      "ds-1674zj"
      "ds-1674zj-p"
      "ds-1674zj-p-y"
      "ds-1674zj-y"
      "ds-2fdi51-ow-a"
      "ds-2fsch20"
      "ds-2fsch30"
      "ds-2hz9sdf37g-y"
      "ds-sbox-01"
      "ds-sbox-03"