mindmap
  root(("Network Speaker"))
    "Models: 34"
    "Models"
      "ds-qaz0110g1-s"
      "ds-qaz0120g1r-s"
      "ds-qaz0203g1-s"
      "ds-qaz0206g1-s"
      "ds-qaz0606g1-s"
      "ds-qaz0610g1-s"
      "ds-qaz1110g1-b"
      "ds-qaz1110g1r-be"
      "ds-qaz1120g1-b"
      "ds-qaz1120g1r-b"
      "ds-qaz1203g1-be"
      "ds-qaz1206g1-be"
      "ds-qaz1307g1-e"
      "ds-qaz1307g1-e-c-"
      "ds-qaz1307g1t-e"
      "ds-qaz1307g1t-e-c-"
      "ds-qaz1310g1t-e"
      "ds-qaz1310g1t-ey"
      "16 more models"