mindmap
  root(("Power Adapter"))
    "Models: 13"
    "Models"
      "ds-2fa1205-c8-eur-"
      "ds-2fa1205-c8-mex-"
      "ds-2fa1205-c8-phi-"
      "ds-2fa1205-c8-uk-"
      "ds-2fa1205-d8-eur-"
      "ds-2fa1205-d8-uk-"
      "ds-2fa1225-c4-eur-"
      "ds-2fa1225-c4-mex-"
      "ds-2fa1225-c4-phi-"
      "ds-2fa1225-c4-uk-"
      "ds-2fa1225-d4-eur-"
      "ds-2fa1225-d4-uk-"
      "ds-2pa1201-wrd"