mindmap
  root(("Decoders"))
    "Models: 9"
    "Models"
      "ds-6901udi-c-"
      "ds-6904udi-c-"
      "ds-6908udi-c-"
      "ds-6910udi-c-"
      "ds-6912udi-c-"
      "ds-6916udi-c-"
      "ds-6920udi-u-c-"
      "ds-6924udi-u-c-"
      "ds-6932udi-u-c-"