mindmap
  root((Pro Series))
    Model Differences
      Camera > Image Sensor
      Camera > Min. Illumination
      General > Camera Dimension
      General > Camera Weight
      General > Power Supply
      Lens > FOV
      Video > Main Stream
      Video > Max. Resolution
    Models
      DS-2CD2125FHWD-I(S)
      DS-2CD2145FWD-I(S)
      DS-2CD2165G0-I(S)