mindmap
  root(("1080P Lite"))
    "Models: 17"
    "Models"
      "Dvr 104g M1 T"
      "Dvr 108g M1"
      "Dvr 108g M1 T"
      "Dvr 116g M1"
      "Dvr 116g M1 T"
      "Dvr 204g M1"
      "Dvr 204g M1 T"
      "Dvr 208g M1"
      "Dvr 208g M1 T"
      "Dvr 216g M1"
      "Dvr 216g M1 T"
      "Dvr 232g M2"
      "Dvr E04g D"
      "Dvr E04g E"
      "Dvr E08g B"
      "Dvr E08g D"
      "Dvr E16g B"