mindmap
  root(("1080P"))
    "Models: 67"
    "Models"
      "Thc B120 C"
      "Thc B120 M"
      "Thc B120 Mpirl"
      "Thc B120 Ms"
      "Thc B120 Pc"
      "Thc B120 Pic"
      "Thc B120 Ps"
      "Thc B123 M"
      "Thc B127 Lmc"
      "Thc B127 Lms"
      "Thc B127 Lpc"
      "Thc B127 Lps"
      "Thc B127 Lpts"
      "Thc B127 Lts"
      "Thc B127 Ms"
      "Thc B127 P"
      "Thc B129 Lps"
      "Thc B129 Lpts"
      "49 more models"