mindmap
  root(("Value Camera"))
    "Models: 154"
    "Models"
      "Ipc B120ha"
      "Ipc B120ha Lu"
      "Ipc B120ha Luf Sl"
      "Ipc B121h M"
      "Ipc B129h"
      "Ipc B129ha"
      "Ipc B129ha Lu"
      "Ipc B129ha Luf S L Rb"
      "Ipc B129haa Lu F Sl Srb"
      "Ipc B140h M"
      "Ipc B140ha"
      "Ipc B140ha Lu"
      "Ipc B140ha Luf Sl"
      "Ipc B140hap Luf Sl"
      "Ipc B149h"
      "Ipc B149ha"
      "Ipc B149ha Lu"
      "Ipc B149ha Luf S L Rb"
      "136 more models"
    "Top diff fields"
      "Lens > Focal Length & FOV"
      "General > Power"
      "General > With Package Weight"
      "Approval > EMC"
      "Event > Linkage"
      "Approval > Safety"
      "Network > API"
      "Network > Protocols"
      "Camera > Image Sensor"
      "Network > Web Browser"