mindmap
  root(("Value NVR"))
    "Models: 39"
    "Models"
      "Nvr 104h D"
      "Nvr 104h D 4p"
      "Nvr 104mh C"
      "Nvr 104mh C 4p"
      "Nvr 104mh C 4p B"
      "Nvr 104mh C 4p E"
      "Nvr 104mh C E"
      "Nvr 104mh D"
      "Nvr 104mh D 4p"
      "Nvr 104mh K"
      "Nvr 104mh K 4p"
      "Nvr 108 B 8p"
      "Nvr 108h D"
      "Nvr 108h D 8p"
      "Nvr 108mh C"
      "Nvr 108mh C 8p"
      "Nvr 108mh C 8p E"
      "Nvr 108mh C E"
      "21 more models"