mindmap
  root(("3k"))
    "Models: 21"
    "Models"
      "Thc B157 Lms"
      "Thc B157 Lps"
      "Thc B157 Lpts"
      "Thc B157 Lts"
      "Thc B159 Lms"
      "Thc B159 Lps"
      "Thc B159 Ms"
      "Thc B257 Lms"
      "Thc B257 Lts"
      "Thc B259 Lms"
      "Thc B259 Ms"
      "Thc T157 Lms"
      "Thc T157 Lps"
      "Thc T157 Ptlts"
      "Thc T159 Lms"
      "Thc T159 Lps"
      "Thc T159 Ms"
      "Thc T257 Lms"
      "3 more models"