mindmap
  root(("4MP"))
    "Models: 9"
    "Models"
      "DVR 204U K1"
      "Dvr 204u M1"
      "Dvr 204u M1 T"
      "DVR 208U K1"
      "Dvr 208u M1"
      "Dvr 208u M1 T"
      "DVR 216U K2"
      "Dvr 216u M1 T"
      "Dvr 216u M2"