mindmap
  root(("Network Dome HiLook Series"))
    "Models: 11"
    "Models"
      "Ptz N2204i De3"
      "PTZ N2404I DE3"
      "Ptz N2c200c De"
      "PTZ N4215 DE3"
      "PTZ N4215I DE"
      "PTZ N4225I DE"
      "Ptz N4415 De3"
      "Ptz N4425i De"
      "Ptz N5225i A"
      "Ptz N5225i De"
      "Ptz N5425i De"