mindmap
  root(("1080P"))
    "Models: 10"
    "Models"
      "Dvr 204q M1"
      "Dvr 204q M1 T"
      "Dvr 208q M1"
      "Dvr 208q M1 T"
      "Dvr 216q M1"
      "Dvr 216q M1 T"
      "Dvr 216q M2"
      "Dvr E04q B"
      "Dvr E04q D"
      "Dvr E08q B"