mindmap
  root(("4MP"))
    "Models: 13"
    "Models"
      "Thc B140 M"
      "Thc B140 P"
      "Thc B150 M"
      "Thc B150 P"
      "Thc B240"
      "Thc B240 M"
      "Thc B340 Vf"
      "Thc T140 M"
      "Thc T140 P"
      "Thc T150 M"
      "Thc T150 P"
      "Thc T240 M"
      "Thc T340 Vf"