mindmap
  root(("Wi Fi KIT"))
    "Models: 6"
    "Models"
      "Ik 4142b Mh W"
      "Iks 2042bh Ph W"
      "Iks 2042bph Ph W"
      "Iks 2042bth Ph W"
      "Iks 2044bph Ph W"
      "Iks 2044bth Ph W"