mindmap
  root(("Urban Road Anpr Cameras"))
    "Models: 7"
    "Models"
      "ids-tcm403-b"
      "ids-tcm403-bi"
      "ids-tcm403-gir"
      "ids-tcm403-gr"
      "ids-tcm441-fir"
      "ids-tcm803-h"
      "ids-tcm803-hi"