mindmap
  root(("Anti Corrosion Series"))
    "Category: IP Products"
    "Subcategory: Explosion Proof Anti Corrosion Series"
    "Models: 46"
    "Models"
      "ds-2dt5432mwg-t--pa-"
      "ds-2dt5432mwg-t-4g--pa-"
      "ds-2dt6232x-aely-t5-"
      "ds-2dt6425x-aely-t5-"
      "ds-2dt8c442mxg-elwt"
      "ds-2dt8c442mxg-lwt"
      "ds-2dt8c842mxg-elwt"
      "ds-2st4c420mwg-e-14-pa-"
      "38 more models"
    "No specification comparison yet"