mindmap
  root(("Pro Series"))
    "Models: 92"
    "Models"
      "ds-7604ni-q1"
      "ds-7604ni-q1-4p"
      "ds-7604ni-q1-4p-e-"
      "ds-7604ni-q1-e-"
      "ds-7604nxi-k1"
      "ds-7604nxi-k1-4p"
      "ds-7604nxi-k1-4p-d-"
      "ds-7604nxi-k1-4p-e-"
      "ds-7604nxi-k1-4puhk-d-"
      "ds-7604nxi-k1-d-"
      "ds-7604nxi-k1-e-"
      "ds-7608ni-i2"
      "ds-7608ni-i2-8p"
      "ds-7608ni-q1"
      "ds-7608ni-q1-8p"
      "ds-7608ni-q1-8p-e-"
      "ds-7608ni-q1-e-"
      "ds-7608ni-q2"
      "74 more models"