mindmap
  root(("Value Series"))
    "Models: 10"
    "Models"
      "ds-7104ni-q1"
      "ds-7104ni-q1-4p"
      "ds-7104ni-q1-4p-m"
      "ds-7104ni-q1-m"
      "ds-7108ni-q1"
      "ds-7108ni-q1-8p"
      "ds-7108ni-q1-8p-m"
      "ds-7108ni-q1-m"
      "ds-7604ni-k1-w"
      "ds-7608ni-k1-w"