mindmap
  root(("Pro Series EasyIP"))
    "Category: IP Products"
    "Subcategory: Network Cameras"
    "Models: 504"
    "Models"
      "Ds 2cd2127g2 Su"
      "ds-2cd1343g2-i-uf-"
      "ds-2cd20123g2-li-u-y"
      "ds-2cd20123g2-liuy-s-l--rb-"
      "ds-2cd20126g3-i-u-y"
      "ds-2cd20126g3-iuy-s-l--rb-"
      "ds-2cd20166g3-i-u-y"
      "ds-2cd20166g3-iuy-s-l--rb-"
      "496 more models"
    "Comparison Summary"
      "24 / 489 models compared"
      "40 differing fields found"
    "Key Differences"
      "Camera / Min. Illumination: Color: 0.0005 Lux @ (F1.0, AGC ON) / Color: 0.005 Lux @ (F1.6, AGC ON),0 Lux with light / Color: 0.0008 Lux @ (F1.6, AGC ON),B/W: 0 Lux with IR"
      "Video / Main Stream: 50 Hz: 25 fps (1920 × 1080, 1280 × 720) 60 Hz: 30 fps (1920 × 1080, 1280 × 720) / 50Hz： 20fps(4608 × 2592) 25fps(3840 × 2160, 2688 × 1520, 1920 × 1080, 1280 × 720) 60Hz： 20fps(4608 × 2592) 30fps(3840 × 2160, 2688 × 1520, 1920 × 1080, 1280 × 720) / 50 Hz: 12.5 fps (4608 × 3456) 20 fps (4608 × 2592) 25 fps (3840 × 2160, 3200 × 1800, 2688 × 1520, 1920 × 1080, 1280 × 720) 60 Hz: 15 fps (4608 × 3456) 20 fps (4608 × 2592) 30 fps (3840 × 2160, 3200 × 1800, 2688 × 1520, 1920 × 1080, 1280 × 720)"
      "Event / Smart Event: Line crossing detection, intrusion detection, region entrance detection, region exiting detection (support alarm triggering by specified target types (human and vehicle)) Scene change detection / Scene change detection / Line crossing detection, intrusion detection"
      "Network / Web Browser: Plug-in required live view: IE 10, IE 11 Plug-in free live view: Chrome 57.0+, Firefox 52.0+ Local service: Chrome 57.0+, Firefox 52.0+ / Plug-in free live view: Chrome 80+, Firefox 80+, Edge 89+, Local service: Chrome 80+, Firefox 80+, Edge 89+ / Plug-in required live view: IE 10+ Plug-in free live view: Chrome 57.0+, Firefox 52.0+ Local service: Chrome 57.0+, Firefox 52.0+"
      "Video / Video Compression: Main stream: H.265/H.264/H.265+/H.264+ Sub-stream: H.265/H.264/MJPEG Third stream: H.265/H.264 *Third stream is supported under certain settings. / Main stream: H.265/H.264/H.264+/H.265+, Sub-stream: H.265/H.264/MJPEG, Third stream: H.265/H.264, *Third stream is supported under certain settings. / Main stream: H.265/H.264/H.264+/H.265+, Sub-stream: H.265/H.264/MJPEG, Third stream: H.265/H.264"
      "Network / API: Open Network Video Interface (Profile S, Profile G), ISAPI, SDK / ONVIF (Profile S, Profile G, Profile T),ISAPI,SDK,ISUP / Open Network Video Interface, ISAPI"