mindmap
  root(("Special Series"))
    "Models: 61"
    "Models"
      "ds-2df3c400scg-d--4g---wl15-wl40--f1-"
      "ds-2df7c432mxg1--w-r"
      "ds-2df7c432mxg1--w-r-4g"
      "ds-2df7c432mxg1-wrp-4g"
      "ds-2df7c442ixg1-elwyp"
      "ds-2df7c842ixg1-elwyp"
      "ds-2df8c435mhg1-elwyp"
      "ds-2dv6c425mxg-elw"
      "ds-2dv6c425mxg-elw-4g"
      "ds-2dv6c425mxg-elwy"
      "ds-2dv6c425mxg-elwy-4g"
      "ds-2dy3220iw-de"
      "ds-2dy3220iw-de-s6-"
      "ds-2dy3220iw-de4"
      "ds-2dy3220iw-de4-s6-"
      "ds-2dy3320iw-de"
      "ds-2dy3320iw-de4"
      "ds-2dy3420iw-de-s6-"
      "43 more models"