mindmap
  root(("DeepinView Series"))
    "Models: 138"
    "Models"
      "Explore More Deepinview Cameras"
      "ids-2cd5347g2-v-xs"
      "ids-2cd5347g2-xs"
      "ids-2cd5387g2-v-xs"
      "ids-2cd5387g2-xs"
      "ids-2cd5546g2-xz-h-s-y-"
      "ids-2cd5586g2-xz-h-s-y-"
      "ids-2cd5a46g2-inzhsy"
      "ids-2cd5a46g2-v-xz-h-s-y-"
      "ids-2cd5a46g2-xz-h-s-y-"
      "ids-2cd5a86g2-v-xz-h-s-y-"
      "ids-2cd5a86g2-xz-h-s-y-"
      "ids-2cd5d47g2-v-xs"
      "ids-2cd5d47g2-xs"
      "ids-2cd5d87g2-v-xs"
      "ids-2cd5d87g2-xs"
      "ids-2cd5t47g2-v-x-h-s-y-"
      "ids-2cd5t47g2-x-h-s-y-"
      "120 more models"