mindmap
  root(("Wi Fi Series"))
    "Models: 58"
    "Models"
      "ds-2cd1023g2-liduf-4g-sl"
      "ds-2cd1043g2-liduf-4g-sl"
      "ds-2cd2021g1-idw"
      "ds-2cd2041g1-idw"
      "ds-2cd2051g1-idw"
      "DS-2CD2121G1-IDW"
      "ds-2cd2141g1-idw"
      "ds-2cd2421g0-i-d-w"
      "ds-2cd2423g0-iw"
      "ds-2cd2423g2-iw--w-"
      "ds-2cd2425fwd-iw"
      "ds-2cd2455fwd-iw"
      "ds-2cd2463g0-iw"
      "ds-2cfs04-4g"
      "ds-2cfsp4-4g"
      "ds-2cfsp8-d-4g"
      "ds-2cfw02--eu-"
      "ds-2cfw04--eu-"
      "40 more models"