mindmap
  root(("Ultra Series"))
    "Models: 246"
    "Models"
      "ds-2df5225x-ae3"
      "ds-2df5225x-ae3-t3-"
      "ds-2df5225x-ae3-t5-"
      "ds-2df5225x-ael"
      "ds-2df5225x-ael-t3-"
      "ds-2df5232x-ae3-t3-"
      "ds-2df5232x-ae3-t5-"
      "ds-2df5232x-ael"
      "ds-2df5232x-ael-t3-"
      "ds-2df5232x-ael-t5-"
      "ds-2df6225x-ael"
      "ds-2df6225x-ael-t3-"
      "ds-2df6a225iwg1-el"
      "ds-2df6a225x-ael"
      "ds-2df6a225x-ael-t3-"
      "ds-2df6a225x-ael-t5-"
      "ds-2df6a236x-ael"
      "ds-2df6a236x-ael-t3-"
      "228 more models"
    "Top diff fields"
      "Lens > Focal Length"
      "Lens > FOV"
      "Lens > Zoom Speed"
      "PTZ > Movement Range (Tilt)"
      "PTZ > Pan Speed"
      "PTZ > Park Action"
      "PTZ > Tilt Speed"
      "PTZ > PTZ Status Display"
      "PTZ > 3D Positioning"
      "PTZ > Movement Range (Pan)"