mindmap
  root(("Panoramic Series"))
    "Models: 38"
    "Models"
      "ds-2cd3956g2-is-u-"
      "ds-2cd6365g1-ivs"
      "ds-2cd6365g1-s-rc"
      "ds-2cd6395g1e-ivs"
      "ds-2cd63c5g1-ivs"
      "ds-2cd63c5g1-s-rc"
      "ds-2cd6924g0-ihs--nfc-"
      "ds-2cd6924g0-ihs-c-"
      "ds-2cd6944g0-ihs--nfc"
      "ds-2cd6944g0-ihs-c-"
      "ds-2cd6944g1-ihs-u-y"
      "ds-2cd6951g2-is"
      "ds-2cd6982g0-u"
      "ds-2cd6982g0-wu-4g"
      "DS-2CD6984G0-IH-S--AC---NFC-"
      "ds-2cd6984g1-ihs-u-y--nfc-"
      "ds-2cd6984g1-vr-u-nfc"
      "DS-2CD6D24FWD--I--Z--H--S---NFC-"
      "20 more models"