mindmap
  root(("Ultra Series"))
    "Models: 69"
    "Models"
      "ds-7608ni-m2"
      "ds-7608ni-m2-8p"
      "ds-7616ni-m2"
      "ds-7616ni-m2-16p"
      "ds-7708ni-m4-8p"
      "ds-7716ni-m4"
      "ds-7716ni-m4-16p"
      "ds-7732ni-m4"
      "ds-7732ni-m4-16p"
      "ds-7732ni-m4-24p"
      "ds-7764ni-m4"
      "DS-8616NI-K8"
      "DS-8632NI-K8"
      "ds-96064ni-i16"
      "ds-9608ni-i8"
      "ds-96128ni-h16r"
      "ds-96128ni-h24r"
      "ds-96128ni-h24r-lcd"
      "51 more models"