mindmap
  root(("Deepinmind Edge"))
    "Models: 89"
    "Models"
      "ids-6708nxi-i-8f-b-"
      "ids-6708nxi-i-fa"
      "ids-6708nxi-m1-x"
      "ids-6708nxi-s"
      "ids-6716nxi-i-16s-b-"
      "ids-6716nxi-i-s"
      "ids-6716nxi-m1-ai-b-"
      "ids-6716nxi-m1-x"
      "ids-6716nxi-p1"
      "ids-6716nxi-s"
      "ids-6732nxi-m1-ai-b-"
      "ids-7608nxi-i2-8f"
      "ids-7608nxi-i2-8p-8f"
      "ids-7608nxi-i2-8p-x"
      "ids-7608nxi-i2-x"
      "ids-7608nxi-m2-8p-x"
      "ids-7608nxi-m2-x"
      "ids-7608nxi-p2"
      "71 more models"