mindmap
  root(("Value Series"))
    "Models: 22"
    "Models"
      "ds-2de2a204iw-de3-s6-"
      "ds-2de2a204iw-de3-w-s6-"
      "ds-2de2a204iwg1-e"
      "ds-2de2a204iwg1-e-w"
      "ds-2de2a404iw-de3-s6-"
      "ds-2de2a404iw-de3-w-s6-"
      "ds-2de2a404iwg1-e"
      "ds-2de2a404iwg1-e-w"
      "ds-2de2a604iwg1-e"
      "ds-2de2a604iwg1-e-w"
      "ds-2de2c400mw-de-s7-"
      "ds-2de3204w-de-t5-"
      "ds-2de3a400bw-de-t5-"
      "ds-2de3a404iw-de-s6-"
      "ds-2de3a404iw-de-w-s6-"
      "ds-2de3a404iwg-e-w"
      "ds-2se3c204mwg-4g-12"
      "ds-2se3c204mwg-e-12"
      "4 more models"