mindmap
  root(("Pro Series"))
    "Models: 128"
    "Models"
      "ds-2de4215iw-de"
      "ds-2de4215iw-de-s5-"
      "ds-2de4215iw-de-s6-"
      "ds-2de4215iw-de-t5-"
      "ds-2de4215iwg-e"
      "ds-2de4215iwg1-e"
      "ds-2de4215w-de"
      "ds-2de4225iw-de"
      "ds-2de4225iw-de-s5-"
      "ds-2de4225iw-de-s6-"
      "ds-2de4225iw-de-t5-"
      "ds-2de4225iwg-e"
      "ds-2de4225iwg1-e"
      "ds-2de4225w-de"
      "ds-2de4225w-de-s6-"
      "ds-2de4225w-de3"
      "ds-2de4225w-de3-s6-"
      "ds-2de4225wg-e3"
      "110 more models"