mindmap
  root(("Ultra Series SmartIP"))
    "Category: IP Products"
    "Subcategory: Network Cameras"
    "Models: 390"
    "Models"
      "ds-2cd30167g3-liu-sl-y-"
      "ds-2cd30167g3-liu-y-"
      "ds-2cd3021g3-liuf"
      "ds-2cd3021g3e-liu"
      "ds-2cd3023g2-iu"
      "ds-2cd3023g2-liu"
      "ds-2cd3023g2-liu-sl"
      "ds-2cd3026g2-is"
      "382 more models"
    "Comparison Summary"
      "23 / 321 models compared"
      "40 differing fields found"
    "Key Differences"
      "General / With Package Weight: Approx. 825 g (1.8 lb.) / Approx. 715 g (1.6 lb.) / Approx. 755 g (1.7 lb.)"
      "Camera / Min. Illumination: Color: 0.0008 Lux @ (F1.6, AGC ON),0 Lux with light / Color: 0.005 Lux @ (F1.6, AGC ON),0 Lux with light / Color: 0.005 Lux @ (F1.6, AGC ON)"
      "DORI / DORI: 2.8 mm: D: 117 m, O: 46 m, R: 23 m, I: 11 m 4 mm: D: 148 m, O: 59 m, R: 29 m, I: 14 m 6 mm: D: 236 m, O: 93 m, R: 47 m, I: 23 m / 2.8 mm, D: 40 m, O: 16 m, R: 8 m, I: 4 m 4 mm, D: 56 m, O: 22 m, R: 11 m, I: 5 m 6 mm, D: 85 m, O: 33 m, R: 17 m, I: 8 m / 2.8 mm: D: 47 m, O: 18 m, R: 9 m, I: 4 m 4 mm: D: 51 m, O: 20 m, R: 10 m, I: 5 m 6 mm: D: 78 m, O: 31 m, R: 15 m, I: 7 m"
      "Lens / Focal Length & FOV: 2.8 mm, horizontal FOV 94.5°, vertical FOV 69.9°, diagonal FOV 123.2° 4 mm, horizontal FOV 73.3°, vertical FOV 54.7°, diagonal FOV 94° 6 mm, horizontal FOV 47.1°, vertical FOV 35°, diagonal FOV 60.5° / 2.8 mm, horizontal FOV 112°, vertical FOV 61°, diagonal FOV 132° 4 mm, horizontal FOV 91°, vertical FOV 46°, diagonal FOV 110° 6 mm, horizontal FOV 56°, vertical FOV 30°, diagonal FOV 65° / 2.8 mm, horizontal FOV 109°, vertical FOV 55°, diagonal FOV 138° 4 mm, horizontal FOV 94°, vertical FOV 49°, diagonal FOV 113° 6 mm, horizontal FOV 57°, vertical FOV 32°, diagonal FOV 66°"
      "Event / Smart Event: Scene change detection, audio exception detection, defocus detection / Unattended baggage detection, object removal detection, loitering detection, people gathering detection, fast moving detection, parking detection,video quality diagnosis / Unattended baggage detection, object removal detection, scene change detection, audio exception detection, video quality diagnosis"
      "Video / Main Stream: 50 Hz: 12.5 fps（4608 × 3456） 20 fps (4608 × 2592) 25 fps (3840 × 2160, 3200 × 1800, 2688 × 1520, 1920 × 1080, 1280 × 720) 60 Hz: 15 fps（4608 × 3456） 20 fps (4608 × 2592) 30 fps (3840 × 2160, 3200 × 1800, 2688 × 1520, 1920 × 1080, 1280 × 720) / 50 Hz: 12.5 fps (4608 × 3456) 20 fps (4608 × 2592) 25 fps (3840 × 2160, 3200 × 1800, 2688 × 1520, 1920 × 1080, 1280 × 720) 60 Hz: 15 fps (4608 × 3456) 20 fps (4608 × 2592) 30 fps (3840 × 2160, 3200 × 1800, 2688 × 1520, 1920 × 1080, 1280 × 720) / 50 Hz: 25 fps (1920 × 1080, 1280 × 720) 60 Hz: 30 fps (1920 × 1080, 1280 × 720)"