mindmap
  root(("Vms Servers"))
    "Models: 10"
    "Models"
      "Hikcentral P Ver Hw1d 300"
      "Hikcentral P Ver Hw1d 64"
      "Hikcentral P Ver Hw2d 300"
      "Hikcentral P Ver Hw2d 64"
      "Hikcentral P Vet Hw5 32"
      "Hikcentral P Vet Hw7 32"
      "Hikcentral P Vss Base Hw 300ch B"
      "Hikcentral P Vss Base Hw 64ch B"
      "Hikcentral Workstation Hw5l 32ch C"
      "Hikcentral Workstation Hw7l 32ch C"