mindmap
  root(("Wi Fi KIT"))
    "Models: 22"
    "Models"
      "Nk42w0h 1t E"
      "Nk44w0h 1t E"
      "Nk44w0h E"
      "Nk44w1h 1t E"
      "Nk44w1h E"
      "Nk842w0h E"
      "Nk842wbh"
      "Nk844w0h 1t E"
      "Nk844w0h E"
      "Nk844w1h 1t E"
      "Nk844w1h E"
      "Nk844wbh"
      "Nk844wdh"
      "Nks422w02h"
      "Nks422w03h"
      "Nks422w0h"
      "Nks422wbh"
      "Nks422wbph"
      "4 more models"