mindmap
  root(("Accessories"))
    "Models: 66"
    "Models"
      "ds-1258zj-l-428cpy"
      "ds-1269zj-p-y"
      "ds-1280zj-dm55-428cpy"
      "ds-1280zj-dm55-b--428cpy"
      "ds-1284zj-m"
      "ds-1284zj-m-ac3-os-"
      "ds-1293zj-p-y"
      "ds-1677zj-xs-1-0--c2-"
      "ds-1677zj-xs-1-0-dy-"
      "ds-1690zj-x"
      "ds-1691zj-x"
      "ds-1693zj-x"
      "ds-1694zj-x"
      "ds-1695zj-x"
      "ds-1696zj-x"
      "ds-1696zj-x-ac-os-"
      "ds-1697zj-x"
      "ds-1697zj-x-ac-os-"
      "48 more models"