mindmap
  root(("Value Series"))
    "Models: 152"
    "Models"
      "ds-2cd1023g0-iuf"
      "ds-2cd1023g0e-i"
      "ds-2cd1023g2-liu-f-"
      "ds-2cd1023g2-liuf-sl"
      "ds-2cd1027g2-l-uf-"
      "ds-2cd1027g2h-liu-f-"
      "ds-2cd1027g2h-liuf-s-l--rb-"
      "ds-2cd1027g3-liu-f---sl---srb-"
      "ds-2cd1043g0-i-uf-"
      "ds-2cd1043g2-i-uf-"
      "ds-2cd1043g2-liu-f-"
      "ds-2cd1043g2-liuf-sl"
      "ds-2cd1047g2-l-uf-"
      "ds-2cd1047g2h-liu-f-"
      "ds-2cd1047g2h-liuf-s-l--rb-"
      "ds-2cd1047g3-liu-f---sl---srb-"
      "ds-2cd1047g3h-liu-f---sl---srb-"
      "ds-2cd1053g0-i-uf-"
      "134 more models"