mindmap
  root(("General Purpose Server"))
    "Models: 38"
    "Models"
      "ds-vd22d-d-hw15e"
      "ds-vd22d-d-hw2"
      "ds-vd22d-d-hw2e"
      "ds-vd22d-d-hw3e"
      "ds-vd22d-d-hw40e"
      "ds-vd22d-d-hw48e"
      "ds-vd22d-d-hw50e"
      "ds-vd22d-d-hw6e"
      "ds-vd22d-d-hw7e"
      "ds-vd22d-d-hw9e"
      "ds-ve11-r-hw1"
      "ds-ve11-r-hw2"
      "ds-ve11-r-hw2e"
      "ds-ve11-r-hw3"
      "ds-ve11-r-hw3e"
      "ds-ve11-r-hw5"
      "ds-ve11-r-hw5e"
      "ds-ve41-t-hw3"
      "20 more models"