mindmap
  root(("Anti Corrosion Series"))
    "Models: 46"
    "Models"
      "ds-2dt5432mwg-t--pa-"
      "ds-2dt5432mwg-t-4g--pa-"
      "ds-2dt6232x-aely-t5-"
      "ds-2dt6425x-aely-t5-"
      "ds-2dt8c442mxg-elwt"
      "ds-2dt8c442mxg-lwt"
      "ds-2dt8c842mxg-elwt"
      "ds-2st4c420mwg-e-14-pa-"
      "ds-2st5c425mwg-e-w--26-pa-"
      "ds-2st5c432mwg-e-w--26-pa-"
      "ds-2st5c432mwg-ew-4g-14-pa-"
      "ds-2xc3146g0h-li-s--u---pa-"
      "ds-2xc3146g0h-lisu-sl--pa-"
      "ds-2xc3186g0h-li-s--u---pa-"
      "ds-2xc3186g0h-lisu-sl--pa-"
      "ds-2xc3346g0h-li-s--u---pa-"
      "ds-2xc3346g0h-lisu-sl--pa-"
      "ds-2xc3386g0h-li-s--u---pa-"
      "28 more models"