mindmap
  root(("Value Series"))
    "Category: IP Products"
    "Subcategory: Network Cameras"
    "Models: 191"
    "Models"
      "ds-2cd1021-i"
      "ds-2cd1021g2-iu"
      "ds-2cd1021g2-liu-f-"
      "ds-2cd1023g0-iuf"
      "ds-2cd1023g0e-i"
      "ds-2cd1023g2-liu-f-"
      "ds-2cd1023g2-liu-sl-brazil"
      "ds-2cd1023g2-liuf-sl"
      "183 more models"
    "No specification comparison yet"