mindmap
  root(("Ultra Series SmartIP"))
    "Models: 321"
    "Models"
      "ds-2cd30167g3-liu-sl-y-"
      "ds-2cd30167g3-liu-y-"
      "ds-2cd3023g2-iu"
      "ds-2cd3023g2-liu"
      "ds-2cd3023g2-liu-sl"
      "ds-2cd3027g2-ls"
      "ds-2cd3043g2-iu"
      "ds-2cd3043g2-liu"
      "ds-2cd3043g2-liu-sl"
      "ds-2cd3046g2-is"
      "ds-2cd3046g2-iu-sl"
      "ds-2cd3046g2h-li-u-"
      "ds-2cd3046g2h-liu-sl"
      "ds-2cd3046g3-iu-sl-y-"
      "ds-2cd3046g3-iu-y-"
      "ds-2cd3046g3-liu-y-"
      "ds-2cd3046g3-liu-y--sl"
      "ds-2cd3047g2-ls"
      "303 more models"
    "Top diff fields"
      "General > With Package Weight"
      "Camera > Min. Illumination"
      "DORI > DORI"
      "Lens > Focal Length & FOV"
      "Event > Smart Event"
      "Video > Main Stream"
      "Network > API"
      "Approval > EMC"
      "Camera > Image Sensor"
      "Network > Protocols"