mindmap
  root(("Special Series"))
    "Models: 32"
    "Models"
      "ds-7102ni-s1-w"
      "ds-7104ni-k1-w-m"
      "ds-7104ni-s1-w"
      "ds-7104ni-s2-wx"
      "ds-7108ni-k1-w-m"
      "ds-7604ni-k1-4p-4g"
      "ds-7604ni-l1-w"
      "ds-7604ni-q1-w"
      "ds-7608ni-k1-8p-4g"
      "ds-7608ni-k2-8p-4g"
      "ds-7608ni-l1-w"
      "ds-7608ni-q1-w"
      "ds-7616ni-k2-16p-4g"
      "ds-7616ni-k2-4g"
      "ds-9000ai-s16-d"
      "ds-9604lni-v-b02"
      "ds-e04ni-q1"
      "ds-e04ni-q1-4p"
      "14 more models"