mindmap
  root(("Solar Powered Security Camera Setup"))
    "Models: 23"
    "Models"
      "ds-2de5425iwg-k-4g"
      "ds-2se7c432iwg-k-4g-14-f0-"
      "ds-2xs3q47g1-ld-4g"
      "ds-2xs3q47g1-ldh-4g"
      "ds-2xs3q47g1-ldw-h--c18s40"
      "ds-2xs6a25g0-i-ch20s40-no-battery"
      "ds-2xs6a46g1-izs-4g"
      "ds-2xs6a46g1-izs-c36s80"
      "ds-2xs6a46g1-lizs-4g"
      "ds-2xs6a46g1-p-izs-4g"
      "ds-2xs6a46g1-p-izs-c36s80"
      "ds-2xs6a46g1e-lizs-c36s80"
      "ds-2xs6a47g1-ls-4g"
      "ds-2xs6a47g1-ls-c36s80"
      "ds-2xs6a87g1-l-c32s80-no-battery-"
      "ds-2xs6a87g1-ls-4g"
      "ds-2xs6a87g1-ls-c36s80"
      "ds-2xs6f45g0-i--4g-"
      "5 more models"