mindmap
  root(("Special Series"))
    "Models: 31"
    "Models"
      "ds-2cd2d25g1-d-nf"
      "ds-2cd2d25g1-m-d-nf"
      "ds-2cd2d45g1-m-d-nf"
      "ds-2cd2d45g2-u"
      "ds-2cd6045g0-sc-izrs"
      "ds-2cd6085g0-sc-izrs"
      "ds-2cd6425g1-xx"
      "ds-2cd6425g2-c1"
      "ds-2cd6425g2-c2"
      "ds-2cd6445g1-xx"
      "ds-2cd6445g2-c1-hdmi"
      "ds-2cd6825g0-c-i-s--b-"
      "ds-2cd6825g0-c-i-v--s-"
      "ds-2cd6825g0-c-iv-s-"
      "ds-2cd6825g0-c-iv-s--b-"
      "ds-2cd6b25g0-plwc03"
      "ds-2cd6b35g0-plw"
      "ds-2cd6b55g0-pl--t1-"
      "13 more models"