mindmap
  root(("General Purpose Server"))
    "Category: IP Products"
    "Subcategory: Data Center"
    "Models: 61"
    "Models"
      "ds-vd22d-d-hw15e"
      "ds-vd22d-d-hw2"
      "ds-vd22d-d-hw2e"
      "ds-vd22d-d-hw3e"
      "ds-vd22d-d-hw40e"
      "ds-vd22d-d-hw48e"
      "ds-vd22d-d-hw50e"
      "ds-vd22d-d-hw6e"
      "53 more models"
    "No specification comparison yet"