mindmap
  root(("Explosion Proof Series"))
    "Models: 48"
    "Models"
      "ds-2db4223i-cx-t5-316l-"
      "ds-2db4236i-cwx-t5-316l-"
      "ds-2df4220-dx-s6-316l-"
      "ds-2df4220-dx-s6-316l--c-"
      "ds-2df4420-dx-304--e-"
      "ds-2df4420-dx-316l--e-"
      "ds-2df4420-dx-s6--c--304-"
      "ds-2df4420-dx-s6-316l--c-"
      "ds-2df4420wg-xey"
      "ds-2df4420wg-xey-adc--e-"
      "ds-2df6223-cx--w316l-"
      "ds-2df6223-cx-t5-316l-"
      "ds-2df6231-cx-t5-316l-"
      "ds-2df6c431-cx-t5-316l-"
      "ds-2df8432iwg-cxf-316l-"
      "ds-2dy4425mxg0-wex-adc-"
      "ds-2dy5425mxg0-cwex-316l-"
      "ds-2dy7432ixg-xy"
      "30 more models"