mindmap
  root(("Checkpoint Capture Cameras"))
    "Models: 19"
    "Models"
      "ids-tcv500-b-i--im"
      "ids-tcv500-he"
      "ids-tcv500-hi"
      "ids-tcv507-her"
      "ids-tcv507-hir"
      "ids-tcv900-he"
      "ids-tcv900-hi"
      "ids-tcv907-her"
      "ids-tcv907-hir"
      "ids-tcv991-her"
      "ids-tcv991-hir"
      "ids-tcvc00-he"
      "ids-tcvc00-hi"
      "ids-tcvc07-her"
      "ids-tcvc07-hir"
      "ids-tcvk00-he"
      "ids-tcvk00-hi"
      "ids-tcvk07-her"
      "1 more models"