mindmap
  root(("Pro Series EasyIP"))
    "Models: 489"
    "Models"
      "Ds 2cd2127g2 Su"
      "ds-2cd1343g2-i-uf-"
      "ds-2cd20123g2-li-u-y"
      "ds-2cd20123g2-liuy-s-l--rb-"
      "ds-2cd20126g3-i-u-y"
      "ds-2cd20126g3-iuy-s-l--rb-"
      "ds-2cd20166g3-i-u-y"
      "ds-2cd20166g3-iuy-s-l--rb-"
      "DS-2CD2021G1-I-W-"
      "DS-2CD2023G0-I"
      "ds-2cd2023g2-i-u-"
      "ds-2cd2023g2-li-2u-"
      "ds-2cd2023g2-li2u-s-l--rb-"
      "DS-2CD2025FHWD-I"
      "DS-2CD2025FWD-I"
      "ds-2cd2026g2-i-u-"
      "ds-2cd2026g2-iu-sl"
      "ds-2cd2027g2-l-u-"
      "471 more models"
    "Top diff fields"
      "Camera > Min. Illumination"
      "Video > Main Stream"
      "Event > Smart Event"
      "Network > Web Browser"
      "Video > Video Compression"
      "Network > API"
      "General > General Function"
      "Camera > Image Sensor"
      "Network > Network Storage"
      "Image > Image Enhancement"