mindmap
  root(("Mobile Analog Cameras"))
    "Models: 16"
    "Models"
      "Ae Vc124t It"
      "Ae Vc136t"
      "Ae Vc143t Its"
      "Ae Vc153a It"
      "Ae Vc153t It"
      "Ae Vc154t It"
      "Ae Vc159t S"
      "Ae Vc163t Its"
      "Ae Vc222t S"
      "Ae Vc224t It"
      "Ae Vc236t"
      "Ae Vc236t I"
      "Ae Vc243t Its"
      "Ae Vc2521t Its"
      "Ae Vc255t"
      "Ae Vc259t"