mindmap
  root(("Mobile Network Cameras"))
    "Models: 10"
    "Models"
      "Ae Vc215i Isf"
      "ds-2xm6122g1-i-d--m---nd-"
      "ds-2xm6222g1-i-d--m---nd-"
      "ds-2xm6365g0-iv-s--m---nd---c-"
      "ds-2xm6522g1-i-d--m---nd-"
      "ds-2xm6542g1-i-d--m---nd-"
      "ds-2xm6726g1-i-d--m---nd-"
      "ds-2xm6736g0-im-nd-c-"
      "ds-2xm6746g1-i-d--m---nd-"
      "ds-2xm6756g1-i-d--m---nd-"