mindmap
  root(("English"))
    "Access Control Products"
      "2 0 Access Control"
      "Card Terminals"
      "Controllers"
      "Electrical Locks"
      "Face Recognition Terminals"
      "FingerPrint Terminals"
      "KITS"
      "Payment Terminals"
    "Accessories"
      "Access Control Accessories"
      "CCTV Accessories"
      "Entrance Exit And Parking Accessories"
      "Mobile Accessories"
      "Traffic Accessories"
      "Video Intercom Accessories"
    "Accessory Selector"
    "Alarm Products"
      "Intrusion Accessory"
      "Wired Intrusion Alarm"
      "Wireless Intrusion Alarm"
    "Audio And Sensing"
      "Audio Products"
    "Audio Products"
      "Audio Accessories"
      "Professional Audio"
      "Public Address"
      "Security Audio"
    "Discontinued Products"
    "Display And Control"
      "Controllers"
      "Lcd Video Walls"
      "Monitors"
    "Fire Products"
      "Fire Alarm System"
      "Fusion Detection Camera"
      "Standalone Detector"
    "HiLook"
      "HiLook IP Products"
      "HiLook Transmission Products"
      "HiLook Turbo HD Product"
      "Hilook Video Intercom"
    "HiLook IP Products"
      "Cable Free"
      "IP KIT"
      "Network Cameras"
      "Network Video Recorders"
      "PTZ Cameras"
    "HiLook Transmission Products"
      "Network Switches"