mindmap
  root(("Mobile Ai Network Cameras"))
    "Models: 5"
    "Models"
      "Ae Vc1b11 Isf"
      "Ae Vc583i Isf"
      "ds-2xm6726g1-im-nd-x"
      "ds-2xm6825g0-c-iv-s--m---nd---c-"
      "ds-2xm6825g1-c-iv-s--m---nd-"