mindmap
  root(("Online Ups"))
    "Models: 31"
    "Models"
      "ds-ups01k24-r-tjs"
      "ds-ups01k24-r-tjs-x"
      "ds-ups01k24-r-ts"
      "ds-ups01k24-r-ts-x"
      "ds-ups02k48-r-tjs"
      "ds-ups02k48-r-tjs-x"
      "ds-ups02k48-r-ts"
      "ds-ups02k48-r-ts-x"
      "ds-ups03k72-r-tjs"
      "ds-ups03k72-r-tjs-x"
      "ds-ups03k72-r-ts"
      "ds-ups03k72-r-ts-x"
      "ds-ups06k-r-tjl"
      "ds-ups10k-r-tjl"
      "ds-upsb09192a-r-tj"
      "ds-upsb09240a-r-tj"
      "ds-upsb0924b-r-t"
      "ds-upsb0924b-r-tc"
      "13 more models"