mindmap
  root(("Back Up Type Ups"))
    "Models: 17"
    "Models"
      "ds-ups1000"
      "ds-ups1000-r"
      "ds-ups1000-r-x"
      "ds-ups1000-x"
      "ds-ups1200-r"
      "ds-ups1200-r-x"
      "ds-ups2000"
      "ds-ups2000-r"
      "ds-ups2000-r-x"
      "ds-ups2000-x"
      "ds-ups3000"
      "ds-ups3000-r"
      "ds-ups3000-x"
      "ds-ups600"
      "ds-ups600-r"
      "ds-ups600-r-x"
      "ds-ups600-x"