mindmap
  root(("Alarm Cables"))
    "Models: 14"
    "Models"
      "ds-1ac2a2bpl1"
      "ds-1ac2b4apl1"
      "ds-1ac2b6apl1"
      "ds-1ac2c4apl1"
      "ds-1ac2c6apl1"
      "ds-1ac4apl1"
      "ds-1ac4auc0m"
      "ds-1ac4auc1"
      "ds-1ac6apl1"
      "ds-1ac6auc0m"
      "ds-1ac6auc1"
      "ds-1ac8apl1"
      "ds-1ac8auc0m"
      "ds-1ac8auc1"