mindmap
  root(("Copper Cables"))
    "Models: 30"
    "Models"
      "ds-1ln5e-e-e"
      "ds-1ln5e-s"
      "ds-1ln5eo-uu-e"
      "ds-1ln5eofpspe"
      "ds-1ln5epsl3"
      "ds-1ln5euec0"
      "ds-1ln5euec7"
      "ds-1ln5eusl5"
      "ds-1ln6-ue-w"
      "ds-1ln6-uu"
      "ds-1ln6afpsl4"
      "ds-1ln6apsl3"
      "ds-1ln6apsl4"
      "ds-1ln6auec0"
      "ds-1ln6ausl5"
      "ds-1ln6auspe"
      "ds-1ln6auuc0"
      "ds-1ln6ofpupe"
      "12 more models"