mindmap
  root(("Parking Guidance Cameras"))
    "Models: 7"
    "Models"
      "ds-tcp440-b"
      "ds-tcp440-b-es-"
      "ds-tcp440-db"
      "ds-tcp440-db-es-"
      "ds-tcp440-dbh"
      "ds-tcp506"
      "ds-tcpc06"