mindmap
  root(("Barrier Gates"))
    "Models: 16"
    "Models"
      "ds-tmg320"
      "ds-tmg320-b"
      "ds-tmg420"
      "ds-tmg420-a"
      "ds-tmg420-a-b"
      "ds-tmg421"
      "ds-tmg421-b"
      "ds-tmg423"
      "ds-tmg423-b"
      "ds-tmg520"
      "ds-tmg520-a-b"
      "ds-tmg520-b"
      "ds-tmg521"
      "ds-tmg521-b"
      "ds-tmg523"
      "ds-tmg523-b"