mindmap
  root(("Body Worn Camera Series"))
    "Models: 35"
    "Models"
      "ds-mcc206"
      "ds-mcc20d"
      "ds-mcc216"
      "ds-mcc21d"
      "ds-mch508d"
      "ds-mcw405"
      "ds-mcw406"
      "ds-mcw407"
      "ds-mcw407-a-"
      "ds-mcw407-d-"
      "ds-mcw409"
      "ds-mcw40b"
      "ds-mcw40c"
      "ds-mcw417"
      "ds-mds001"
      "ds-mds001-b-"
      "ds-mds003"
      "ds-mds003-e"
      "17 more models"