mindmap
  root(("Cabinets"))
    "Models: 27"
    "Models"
      "Cabinet Fan For E Series"
      "Cabinet Tray For E Series"
      "ds-xs6604-s-br"
      "ds-xs6606-s-b"
      "ds-xs6606-s-br"
      "ds-xs6609-s-b"
      "ds-xs6609-s-br"
      "ds-xs6612-s-b"
      "ds-xs6612-s-br"
      "ds-xs6618-e-dg"
      "ds-xs6618-e-dw"
      "ds-xs6622-e-dg"
      "ds-xs6622-e-dw"
      "ds-xs6627-e-dg"
      "ds-xs6627-e-dw"
      "ds-xs6632-e-dg"
      "ds-xs6632-e-dw"
      "ds-xs6637-e-dg"
      "9 more models"