mindmap
  root(("Swing Gates"))
    "Models: 7"
    "Models"
      "ds-k3bc411x"
      "ds-k3bc430lx"
      "ds-k3bc430lx-power-box"
      "ds-k6bc402lx"
      "ds-k6bc402tx"
      "ds-k6bc402x"
      "ds-k6bc402x-rs"