mindmap
  root(("Swing Barriers"))
    "Models: 22"
    "Models"
      "ds-k3b211lx"
      "ds-k3b220lx"
      "ds-k3b220x"
      "ds-k3b411blx"
      "ds-k3b411bx"
      "ds-k3b501sx"
      "ds-k3b530lx"
      "ds-k3b530x"
      "ds-k3b530x-modular"
      "ds-k3b601sx"
      "ds-k3b631tx"
      "ds-k3b801bx"
      "ds-k3b802bx"
      "ds-k3b961tx"
      "ds-k6b411tx"
      "ds-k6b411tx-modular"
      "ds-k6b530tx"
      "ds-k6b530tx-modular"
      "4 more models"