mindmap
  root(("Fiber Optic Sensing"))
    "Models: 14"
    "Models"
      "ds-qft0304h"
      "ds-qft0308h"
      "ds-qft0312h"
      "ds-qft1004"
      "ds-qft1008"
      "ds-qft1012"
      "ds-qfv-cks4l"
      "ds-qfv-cks4l-3000m"
      "ds-qfv0102w"
      "ds-qfv0202"
      "ds-qfv0202w"
      "ds-qfv0502"
      "ds-qfv1002"
      "ds-qfv5002"