mindmap
  root(("Tripod Turnstile"))
    "Models: 25"
    "Models"
      "ds-k3g200bx"
      "ds-k3g200lx"
      "ds-k3g200x"
      "ds-k3g225x"
      "ds-k3g225x-s"
      "ds-k3g301bx"
      "ds-k3g301lx"
      "ds-k3g301x"
      "ds-k3g411bx"
      "ds-k3g411cx"
      "ds-k3g411cx-modular"
      "ds-k3g411lx"
      "ds-k3g411x"
      "ds-k3g501blx"
      "ds-k3g501bx"
      "ds-k3g501cx"
      "ds-k3g501cx-modular"
      "ds-k3g501cx-s"
      "7 more models"