mindmap
  root(("Series View With Differences"))
    "IP Products"
      "Pro Series EasyIP | models 504"
        "24 models compared"
        "Camera / Min. Illumination"
        "Video / Main Stream"
        "Event / Smart Event"
      "Ultra Series SmartIP | models 392"
        "23 models compared"
        "General / With Package Weight"
        "Camera / Min. Illumination"
        "DORI / DORI"
      "Ultra Series | models 253"
        "20 models compared"
        "Lens / Focal Length"
        "Lens / FOV"
        "Lens / Zoom Speed"
      "Value Series | models 191"
        "No diff data yet"
      "Pro Series | models 144"
        "No diff data yet"
      "DeepinView Series | models 139"
        "No diff data yet"
      "Deepinmind Edge | models 105"
        "No diff data yet"
      "Pro Series | models 92"
        "No diff data yet"
    "Turbo HD Products"
      "Value Series | models 275"
        "25 models compared"
        "General / Operating Condition"
        "Camera / Angle Adjustment"
        "Camera / Image Sensor"
      "ColorVu Series | models 165"
        "25 models compared"
        "Image / Image Settings"
        "Lens / Focal Length & FOV"
        "General / Dimension"
      "Pro Series | models 65"
        "No diff data yet"
      "AcuSense Series | models 38"
        "No diff data yet"
      "Value Series | models 32"
        "No diff data yet"
      "IOT Series | models 30"
        "No diff data yet"
      "Pro Series | models 29"
        "No diff data yet"
      "Edvr Series | models 24"
        "No diff data yet"
    "Accessories"
      "Bracket | models 237"
        "24 models compared"
        "Parameters / Dimension"
        "Parameters / Material"
        "Parameters / Appearance"
      "Junction | models 54"
        "No diff data yet"
      "Brackets | models 34"
        "No diff data yet"
      "Entrance Accessories | models 19"
        "No diff data yet"
      "Brackets | models 15"
        "No diff data yet"
      "Housing | models 13"
        "No diff data yet"
      "Power Adapter | models 13"
        "No diff data yet"
      "Others | models 12"
        "No diff data yet"
    "Thermal Products"
      "Bullet Series | models 188"
        "22 models compared"
        "Thermal Module / Field of View"
        "Thermal Module / Min. Focusing Distance"
        "Thermal Module / NETD"
      "PT Series | models 67"
        "No diff data yet"
      "Heatpro Series | models 61"
        "No diff data yet"
      "Bullet Series | models 28"
        "No diff data yet"
      "PT Series | models 23"
        "No diff data yet"
      "Speed Dome Series | models 21"
        "No diff data yet"
      "Special Industry Series | models 16"
        "No diff data yet"
      "Special Industry Series | models 13"
        "No diff data yet"
    "HiLook IP Products"
      "Value Camera | models 174"
        "25 models compared"
        "Lens / Focal Length & FOV"
        "General / Power"
        "General / With Package Weight"
      "Value NVR | models 39"
        "No diff data yet"
      "Wi Fi Cameras | models 19"
        "No diff data yet"
      "Network Dome HiLook Series | models 11"
        "No diff data yet"
      "Wi Fi KIT | models 6"
        "No diff data yet"
      "Wi Fi NVR | models 5"
        "No diff data yet"
      "PoE KIT | models 3"
        "No diff data yet"
    "Alarm Products"
      "Ax Pro | models 167"
        "No diff data yet"
      "Ax Home | models 42"
        "No diff data yet"
      "Ax Hybrid Pro | models 33"
        "No diff data yet"
      "Detector Accessory | models 29"
        "No diff data yet"
      "General Wired Detectors | models 29"
        "No diff data yet"
      "Ax Hybrid Pro G2 | models 22"
        "No diff data yet"
      "Common Accessory | models 15"
        "No diff data yet"
      "General Wired Sounders | models 6"
        "No diff data yet"
    "Transmission"
      "Smart Managed Series | models 83"
        "No diff data yet"
      "Unmanaged Switch | models 57"
        "No diff data yet"
      "Enterprise Campus Switch | models 24"
        "No diff data yet"
      "Outdoor Wireless Bridge | models 23"
        "No diff data yet"
      "Industrial Switch | models 16"
        "No diff data yet"
      "Wi Fi Router | models 15"
        "No diff data yet"
      "Mesh Wi Fi System | models 12"
        "No diff data yet"
      "Soho Switch | models 11"
        "No diff data yet"
    "Access Control Products"
      "Value Series | models 78"
        "No diff data yet"
      "Pro Series | models 38"
        "No diff data yet"
      "Pro Series | models 28"
        "No diff data yet"
      "Pro Series | models 27"
        "No diff data yet"
      "Ultra Series | models 27"
        "No diff data yet"
      "Pro Series | models 18"
        "No diff data yet"
      "Value Series | models 16"
        "No diff data yet"
      "Pro Series | models 13"
        "No diff data yet"
    "Video Intercom Products"
      "Pro Series | models 75"
        "No diff data yet"
      "2 Wire Hd | models 39"
        "No diff data yet"
      "IP Kits | models 25"
        "No diff data yet"
      "Ultra Series | models 25"
        "No diff data yet"
      "2 Wire Kits | models 16"
        "No diff data yet"
      "Panic Alarm Panel | models 13"
        "No diff data yet"
      "Sip Server | models 10"
        "No diff data yet"
      "2 Wire Ip | models 9"
        "No diff data yet"
    "HiLook Turbo HD Product"
      "1080P | models 68"
        "No diff data yet"
      "3k | models 21"
        "No diff data yet"
      "1080P Lite | models 18"
        "No diff data yet"
      "4MP | models 13"
        "No diff data yet"
      "1080P | models 11"
        "No diff data yet"
      "4MP | models 9"
        "No diff data yet"
      "720P | models 9"
        "No diff data yet"
      "Turbo Hd Ptz | models 5"
        "No diff data yet"