mindmap
  root(("IOT Series"))
    "Models: 30"
    "Models"
      "ds-2ce11d0t-pirl"
      "ds-2ce11d0t-pirlo"
      "ds-2ce11d0t-pirlp"
      "ds-2ce11d8t-pirl"
      "ds-2ce11d8t-pirlo"
      "ds-2ce11h0t-pirl"
      "ds-2ce11h0t-pirlo"
      "ds-2ce12d0t-pirlo-"
      "ds-2ce12d0t-pirxf"
      "ds-2ce12d8t-pirl"
      "ds-2ce12d8t-pirlo"
      "ds-2ce12df3t-pirxos"
      "ds-2ce12dft-pirxof"
      "ds-2ce12dft-pirxof28"
      "ds-2ce12h0t-pirl"
      "ds-2ce12h0t-pirlo"
      "ds-2ce12kf3t-pirxo"
      "ds-2ce12uf3t-pirxo"
      "12 more models"