mindmap
  root(("Enterprise Campus Switch"))
    "Models: 17"
    "Models"
      "ds-3e2510p"
      "ds-3e2510p-h"
      "ds-3e2528"
      "ds-3e2528-h"
      "ds-3e2528p"
      "ds-3e2528p-h"
      "ds-3e2552-h"
      "ds-3e3728-h"
      "ds-3e3728f-h"
      "ds-3e3730"
      "DS-3E3740"
      "ds-3e3752-h"
      "ds-3e3752f-h"
      "ds-3e3754tf"
      "ds-3e7800-card"
      "ds-3e7803m"
      "ds-3e7806"