mindmap
  root(("Wi Fi Router"))
    "Models: 27"
    "Models"
      "ds-3wp12c"
      "ds-3wp1g"
      "ds-3wr12c"
      "ds-3wr12c-e"
      "ds-3wr12c-h"
      "ds-3wr12gc"
      "ds-3wr12gc-e"
      "ds-3wr12gc-h"
      "ds-3wr15x"
      "ds-3wr15x-h"
      "ds-3wr18x"
      "ds-3wr30x"
      "ds-3wr30x-v"
      "ds-3wr3n"
      "ds-3wr60x"
      "ds-3wrm12c"
      "ds-3wrm12c-2"
      "ds-3wrm12c-3"
      "9 more models"