mindmap
  root(("Unmanaged Switch"))
    "Models: 54"
    "Models"
      "ds-3e0105d-e"
      "ds-3e0105p-e-m-b-"
      "ds-3e0105p-e-m-c-"
      "ds-3e0106p-e-m"
      "ds-3e0106p-e-m-b-"
      "ds-3e0108d-e"
      "ds-3e0109p-e-m-c-"
      "ds-3e0310hp-e"
      "ds-3e0310hp-e-c-"
      "ds-3e0310p-e-m-b-"
      "DS-3E0318P-E-B-"
      "ds-3e0318p-e-c-"
      "ds-3e0318p-e-m"
      "ds-3e0318p-e-m-b-"
      "ds-3e0318p-e-m-c-"
      "DS-3E0326P-E-B-"
      "ds-3e0326p-e-c-"
      "ds-3e0326p-e-m-b-"
      "36 more models"