mindmap
  root(("Bullet Series"))
    "Category: Thermal Products"
    "Subcategory: Security Thermal Cameras"
    "Models: 187"
    "Models"
      "ds-2td2117-10-p"
      "ds-2td2117-10-pai"
      "ds-2td2117-10-pi"
      "ds-2td2117-3-p"
      "ds-2td2117-3-pai"
      "ds-2td2117-3-pi"
      "ds-2td2117-3-v1"
      "ds-2td2117-6-p"
      "179 more models"
    "Comparison Summary"
      "22 / 187 models compared"
      "40 differing fields found"
    "Key Differences"
      "Thermal Module / Field of View: 15.96° × 12° (H × V) / 50° × 37.2° (H × V) / 25.0° × 18.7° (H × V)"
      "Thermal Module / Min. Focusing Distance: 1.2 m / 0.2 m / 0.6 m"
      "Thermal Module / NETD: Less than 40 mK (@ 25 °C,F#=1.1) / less than 40mk (@25°C,F#=1.1) / less than 40mk (@25°C,F#=1.0)"
      "General / Power Consumption: PoE (802.3af, class 3): 42.5 V to 57 V, 0.14 A to 0.22 A, max. 5 W 12 VDC ± 20%: 0.4 A, max. 4.5 W / 12 VDC ± 20%: 1.7 A, max. 8W, PoE (802.3af) / 24 VAC± 25%: 0.84 A, 12 VDC ± 20%: 1.7 A, max. 8W (20W with De-icing Heater On), PoE (802.3at, class 4): 42.5 V to 57 V, 0.4 A to 0.5 A"
      "General / Work Temperature/Humidity: From -40°C to 65°C (-40°F to 149°F); Humidity: 95% or Less / -40 °C to 65 °C (-40 °F to 149 °F), 90% or less / From -40°C to 65°C (-40°F to 149°F); Humidity: 90% or Less"
      "Thermal Module / Aperture: F1.1 / F 1.1 / F 1.0"