mindmap
  root(("Industrial Switch"))
    "Models: 16"
    "Models"
      "ds-3t0306hp-e-hs"
      "ds-3t0310hp-e-hs"
      "ds-3t0506hp-e-hs"
      "ds-3t0506p"
      "ds-3t0510hp-e-hs"
      "ds-3t0510p"
      "ds-3t1306p-si-hs"
      "ds-3t1310p-si-hs"
      "ds-3t1506hp-ei-ups"
      "ds-3t1506hp-si-4p2f"
      "ds-3t1510p-si-flt"
      "ds-3t1512hp-si-8p4f"
      "ds-3t1528hp-si-24p4f"
      "ds-3t2506p"
      "ds-3t2510p"
      "ds-3t3512p"