mindmap
  root(("Soho Switch"))
    "Models: 11"
    "Models"
      "ds-3e0105-o"
      "ds-3e0105d-o"
      "ds-3e0108-o"
      "ds-3e0108d-o"
      "ds-3e0116r-o"
      "ds-3e0505d-o"
      "ds-3e0508d-o"
      "ds-3e0508p-o"
      "ds-3e0516p-o"
      "ds-3e0516r-o"
      "ds-3e0524r-o"