mindmap
  root(("Special Series"))
    "Models: 9"
    "Models"
      "ds-6701hfhi-v"
      "ds-6701hthi-4k-b-"
      "ds-6701huhi"
      "ds-6704huhi"
      "DS-8104AHGH-L-I-E4"
      "ids-6704huhi-m"
      "ids-6708huhi-m"
      "ids-6716huhi-m"
      "ids-8104ahqxli-e4"