mindmap
  root(("Fixed Series"))
    "Models: 8"
    "Models"
      "ds-2ta03-15svi"
      "ds-2ta06-25svi"
      "ds-2ta21-2avf"
      "ds-2ta21-3avf"
      "ds-2td3017t-2-v"
      "ds-2td3017t-3-v"
      "Hm Td3028t 2 Q B"
      "Hm Td3028t 3 Q B"