mindmap
  root(("Value Series"))
    "Category: Turbo HD Products"
    "Subcategory: DVR"
    "Models: 30"
    "Models"
      "ds-7104hghi-m1-t"
      "ds-7108hghi-m1-t"
      "ds-7116hghi-m1-t"
      "ds-7204hghi-m1-t"
      "ds-7208hghi-m1-t"
      "ds-7216hghi-m1-t"
      "ds-7232hghi-m2"
      "ids-7104hghi-m1"
      "22 more models"
    "No specification comparison yet"