mindmap
  root(("Special Industry Series"))
    "Models: 13"
    "Models"
      "ds-2td2137-7-py"
      "ds-2td2466-25y"
      "ds-2td2466-50y"
      "ds-2td4137-25-wy"
      "ds-2td4137-50-wy"
      "ds-2td4167-25-wy"
      "ds-2td4167-50-wy"
      "ds-2td6267-100c4l-wy"
      "ds-2td6267-75c4l-wy"
      "ds-2td6537t-25h4lx-w"
      "ds-2td6537t-50h4lx-w"
      "ds-2td6567t-25h4lx-w"
      "ds-2td6567t-50h4lx-w"