mindmap
  root(("Outdoor Wireless Bridge"))
    "Models: 23"
    "Models"
      "ds-3wf01c-2n-o"
      "ds-3wf02-5ac-d"
      "ds-3wf02c-5ac-o"
      "ds-3wf03c-5ac-o"
      "ds-3wf0fa-2n-o"
      "ds-3wf0fa-5ac-o"
      "ds-3wf0fc-2n-o"
      "ds-3wf1000-ei-2n"
      "ds-3wf1000-ei-2n-p"
      "ds-3wf1000s-ei-2n"
      "ds-3wf1000s-ei-2n-p"
      "ds-3wf2000a-360"
      "ds-3wf20ks-s-5acg"
      "ds-3wf3000-ei-5ac-p"
      "ds-3wf3000s-ei-5ac-p"
      "ds-3wf5000-ei-5acg-3p"
      "ds-3wf5000-si-5acg-2p"
      "ds-3wf5000a-120"
      "5 more models"