mindmap
  root(("Edvr Series"))
    "Models: 23"
    "Models"
      "ds-e04hghi-b"
      "ds-e04hghi-d"
      "ds-e04hghi-e"
      "ds-e04hghi-xb"
      "ds-e04hghi-xd"
      "ds-e04hghi-xe"
      "ds-e04hqhi-b"
      "ds-e08hghi-b"
      "ds-e08hghi-d"
      "ds-e08hghi-xb"
      "ds-e08hghi-xd"
      "ds-e16hghi-b"
      "ds-e16hghi-xb"
      "ds-e16hghi-xd"
      "Ids E08hqhi B"
      "ids-e04hqhi-b"
      "ids-e04hqhi-d"
      "ids-e04hqhi-xb"
      "5 more models"