mindmap
  root(("ColorVu Series"))
    "Category: Turbo HD Products"
    "Subcategory: Turbo HD Cameras"
    "Models: 165"
    "Models"
      "ds-2ce10df0t-f"
      "ds-2ce10df0t-fs"
      "ds-2ce10df0t-lfs"
      "ds-2ce10df0t-lpfs"
      "ds-2ce10df0t-lpts"
      "ds-2ce10df0t-lpxts"
      "ds-2ce10df0t-lts"
      "ds-2ce10df0t-lxts"
      "157 more models"
    "Comparison Summary"
      "25 / 164 models compared"
      "26 differing fields found"
    "Key Differences"
      "Image / Image Settings: Brightness, Mirror, Sharpness, Anti-Banding, AGC / Brightness, Sharpness, Anti-banding, AGC / Anti-banding, Brightness, Sharpness, Smart IR"
      "Lens / Focal Length & FOV: 2.8 mm, horizontal FOV: 98°, vertical FOV: 51°, diagonal FOV: 115° 3.6 mm, horizontal FOV: 76°, vertical FOV: 41°, diagonal FOV: 90° 6 mm, horizontal FOV: 50°, vertical FOV: 27°, diagonal FOV: 58° / 2.8 mm, horizontal FOV: 105°, vertical FOV: 55°, diagonal FOV: 125° 3.6 mm, horizontal FOV: 84°, vertical FOV: 45°, diagonal FOV: 99° / 2.8 mm, horizontal FOV: 105°, vertical FOV: 56°, diagonal FOV: 126° 3.6 mm, horizontal FOV: 84°, vertical FOV: 46°, diagonal FOV: 98°"
      "General / Dimension: 161.1 mm × 70 mm × 70 mm (6.34\" × 2.76\" × 2.76\") / 161.1 mm × 68.4 mm (6.34\" × 2.69\") / 161.1 mm × 68.4 mm × 65.2 mm (6.34\" × 2.69\" × 2.57\")"
      "General / Operating Condition: -40°C to 60°C (-40°F to140°F), Humidity: 90% or less (non-condensing) / -40 °C to 60 °C (-40 °F to 140 °F). Humidity: 90% or less (non-condensing) / -40 °C to 60 °C (-40 °F to 140 °F). Humidity 90% or less (non-condensing)"
      "Camera / Min. Illumination: 0.001 Lux @ (F1.0, AGC ON), 0 Lux with white light / 0.0005 Lux@(F1.0, AGC ON), 0 Lux with white light ON / 0.0005 Lux @ (F1.0, AGC ON), 0 Lux with white light"
      "Image / Frame Rate: TVI: 1080p@25fps/30fps CVI: 1080p@25fps/30fps AHD: 1080p@25fps/30fps CVBS: PAL/NTSC / TVI: 1080p @25 fps/30 fps CVI: 1080p @25 fps/30 fps AHD: 1080p @25 fps/30 fps CVBS: PAL/NTSC / TVI: 1080p @25 fps/30 fps"