mindmap
  root(("PT Series"))
    "Models: 23"
    "Models"
      "Ds 2td5537t 7 W"
      "ds-2td4136t-25"
      "DS-2TD4136T-9"
      "ds-2td4137t-25-w"
      "ds-2td4137t-9-w"
      "ds-2td4166t-25"
      "ds-2td4167t-25-w"
      "ds-2td4167t-9-w"
      "ds-2td4228t-10-s2"
      "ds-2td4228t-10-w"
      "ds-2td4228t-7-s2"
      "ds-2td5537t-15-w"
      "DS-2TD6236T-50H2L"
      "DS-2TD6266T-25H2L"
      "DS-2TD6266T-50H2L"
      "Hm Td5528t 10 W"
      "Hm Td5528t 15 W"
      "Hm Td5537t 15 W"
      "5 more models"