mindmap
  root(("ColorVu Series"))
    "Models: 164"
    "Models"
      "ds-2ce10df0t-f"
      "ds-2ce10df0t-fs"
      "ds-2ce10df0t-lfs"
      "ds-2ce10df0t-lpfs"
      "ds-2ce10df0t-lpts"
      "ds-2ce10df0t-lpxts"
      "ds-2ce10df0t-lts"
      "ds-2ce10df0t-lxts"
      "ds-2ce10df0t-pf"
      "ds-2ce10df0t-pfs"
      "ds-2ce10df3t-f"
      "ds-2ce10df3t-fs"
      "ds-2ce10df3t-lfs"
      "ds-2ce10df3t-lpfs"
      "ds-2ce10df3t-lpxts"
      "ds-2ce10df3t-lse"
      "ds-2ce10df3t-lxts"
      "ds-2ce10df3t-pf"
      "146 more models"
    "Top diff fields"
      "Image > Image Settings"
      "Lens > Focal Length & FOV"
      "General > Dimension"
      "General > Operating Condition"
      "Camera > Min. Illumination"
      "Image > Frame Rate"
      "Image > Image Enhancement"
      "Lens > Lens Type"
      "Camera > Angle Adjustment"
      "Image > White Balance"