mindmap
  root(("Bullet Series"))
    "Models: 28"
    "Models"
      "ds-2td2136t-10"
      "ds-2td2136t-15"
      "ds-2td2136t-25"
      "ds-2td2137t-4-p"
      "ds-2td2137t-4-qy"
      "ds-2td2137t-4-qy0"
      "ds-2td2137t-7-p"
      "ds-2td2137t-7-qy"
      "ds-2td2137t-7-qy0"
      "ds-2td2166t-15"
      "ds-2td2166t-25"
      "ds-2td2167t-7-p"
      "ds-2td2637t-10-p"
      "ds-2td2637t-10-qy"
      "ds-2td2637t-15-p"
      "ds-2td2637t-15-qy"
      "ds-2td2637t-7-qy"
      "ds-2td2667t-15-p"
      "10 more models"