mindmap
  root(("AcuSense Series"))
    "Models: 37"
    "Models"
      "iDS-7204HQHI-M1-S"
      "ids-7204hqhi-m1-xt"
      "ids-7204hthi-m1-s"
      "ids-7204hthi-m1-xt"
      "ids-7204hthi-m2-s"
      "ids-7204hthi-m2-xt"
      "ids-7204huhi-m1-p"
      "ids-7204huhi-m1-pxt"
      "iDS-7204HUHI-M1-S"
      "ids-7204huhi-m1-x"
      "ids-7204huhi-m1-xt"
      "ids-7204huhi-m2-x"
      "ids-7204huhi-m2-xt"
      "iDS-7208HQHI-M1-S"
      "ids-7208hqhi-m1-xt"
      "ids-7208hqhi-m2-s"
      "ids-7208hqhi-m2-xt"
      "ids-7208hthi-m2-s"
      "19 more models"