mindmap
  root(("Value Series"))
    "Models: 275"
    "Models"
      "ds-2ce16c0t-ir"
      "ds-2ce16c0t-irf"
      "ds-2ce16c0t-irp"
      "ds-2ce16c0t-irpf"
      "ds-2ce16c0t-it1"
      "ds-2ce16c0t-it1f"
      "ds-2ce16c0t-it3f"
      "ds-2ce16c0t-it5"
      "ds-2ce16c0t-it5f"
      "ds-2ce16c2t-ir"
      "ds-2ce16c2t-it5"
      "ds-2ce16d0t-exif"
      "ds-2ce16d0t-exip"
      "ds-2ce16d0t-exipf"
      "ds-2ce16d0t-exlf"
      "ds-2ce16d0t-exlpf"
      "ds-2ce16d0t-i2fb"
      "ds-2ce16d0t-i2pfb"
      "257 more models"
    "Top diff fields"
      "General > Operating Condition"
      "Camera > Angle Adjustment"
      "Camera > Image Sensor"
      "Camera > Shutter Time"
      "Interface > Video Output"
      "Camera > Day & Night"
      "General > Dimension"
      "Lens > Lens Type"
      "Image > Frame Rate"
      "Camera > Min. Illumination"