mindmap
  root(("Pro Series"))
    "Models: 29"
    "Models"
      "ds-2ae4215itg"
      "ds-2ae4215t-d"
      "ds-2ae4215t-d3"
      "ds-2ae4215tg"
      "ds-2ae4215tg-3"
      "ds-2ae4215ti-a"
      "ds-2ae4215ti-d"
      "ds-2ae4225itg"
      "ds-2ae4225t-a"
      "ds-2ae4225t-d"
      "ds-2ae4225t-d3"
      "ds-2ae4225tg"
      "ds-2ae4225tg-3"
      "ds-2ae4225ti-d"
      "ds-2ae4425itg"
      "ds-2ae5225itg"
      "ds-2ae5225t-a"
      "ds-2ae5225t-a3"
      "11 more models"