mindmap
  root(("Ultra Series"))
    "Models: 18"
    "Models"
      "DS-2CC12D9T"
      "DS-2CC12D9T-A"
      "ds-2cc12d9t-ait3ze"
      "ds-2cc12d9t-e"
      "DS-2CC12D9T-IT3E"
      "DS-2CC12D9T-IT5E"
      "DS-2CC52D9T-AITZE"
      "DS-2CC52D9T-AVPIT3ZE"
      "DS-2CC52D9T-IT3E"
      "ds-2ce16d9t-airazh"
      "ds-2ce17u8t-it"
      "ds-2ce18u8t-it3"
      "ds-2ce19u8t-ait3z"
      "ds-2ce37u8t-a"
      "ds-2ce57u8t-vpit"
      "ds-2ce59u8t-avpit3z"
      "ds-2ce78u8t-it3"
      "ds-2ce79u8t-it3z"