mindmap
  root(("Bullet Series"))
    "Models: 187"
    "Models"
      "ds-2td2117-10-p"
      "ds-2td2117-10-pai"
      "ds-2td2117-10-pi"
      "ds-2td2117-3-p"
      "ds-2td2117-3-pai"
      "ds-2td2117-3-pi"
      "ds-2td2117-3-v1"
      "ds-2td2117-6-p"
      "ds-2td2117-6-pai"
      "ds-2td2117-6-pi"
      "ds-2td2117-6-v1"
      "ds-2td2136-10-v1"
      "DS-2TD2136-10-VP"
      "ds-2td2136-15-v1"
      "DS-2TD2136-15-VP"
      "ds-2td2136-25-v1"
      "DS-2TD2136-25-VP"
      "ds-2td2136-35-v1"
      "169 more models"
    "Top diff fields"
      "Thermal Module > Field of View"
      "Thermal Module > Min. Focusing Distance"
      "Thermal Module > NETD"
      "General > Power Consumption"
      "General > Work Temperature/Humidity"
      "Thermal Module > Aperture"
      "General > Protection Level"
      "Network > Protocols"
      "Smart Function > Fire Detection"
      "Smart Function > Temperature Accuracy"