mindmap
  root(("Heatpro Series"))
    "Models: 61"
    "Models"
      "ds-2td1117-2-pa"
      "ds-2td1117-3-pa"
      "ds-2td1117-6-pa"
      "ds-2td1217-2-pa"
      "ds-2td1217-2-qa"
      "ds-2td1217-3-pa"
      "ds-2td1217-3-qa"
      "ds-2td1217-6-pa"
      "ds-2td1217-6-qa"
      "ds-2td1217t-2-pa"
      "ds-2td1217t-3-pa"
      "ds-2td1228-2-qa"
      "ds-2td1228-3-qa"
      "ds-2td1228-7-qa"
      "ds-2td1228t-2-qa"
      "ds-2td1228t-2-qa-b-"
      "ds-2td1228t-3-qa"
      "ds-2td1228t-3-qa-b-"
      "43 more models"