mindmap
  root(("Pro Series"))
    "Models: 52"
    "Models"
      "ds-2ce16d8t-ait3zf"
      "ds-2ce16d8t-it1e"
      "ds-2ce16d8t-it1f"
      "ds-2ce16d8t-it3e"
      "ds-2ce16d8t-it3f"
      "ds-2ce16d8t-it3ze"
      "ds-2ce16d8t-it3zf"
      "ds-2ce16d8t-it5e"
      "ds-2ce16d8t-it5f"
      "ds-2ce16d8t-ite"
      "ds-2ce16d8t-itf"
      "ds-2ce16d8t-itpf"
      "ds-2ce16h8t-it1f"
      "ds-2ce16h8t-it3f"
      "ds-2ce16h8t-it5f"
      "ds-2ce16h8t-itf"
      "ds-2ce16u7t-it3f"
      "ds-2ce16u7t-itf"
      "34 more models"