mindmap
  root(("Value Series"))
    "Models: 30"
    "Models"
      "ds-7104hghi-m1-t"
      "ds-7108hghi-m1-t"
      "ds-7116hghi-m1-t"
      "ds-7204hghi-m1-t"
      "ds-7208hghi-m1-t"
      "ds-7216hghi-m1-t"
      "ds-7232hghi-m2"
      "ids-7104hghi-m1"
      "ids-7104hqhi-m1-s"
      "ids-7104hqhi-m1-t"
      "ids-7104huhi-m1-s"
      "ids-7108hghi-m1"
      "ids-7108hqhi-m1-s"
      "ids-7108hqhi-m1-t"
      "ids-7108huhi-m1-s"
      "ids-7116hghi-m1"
      "ids-7116hqhi-m1-s"
      "ids-7116hqhi-m1-t"
      "12 more models"