mindmap
  root(("AcuSense Series"))
    "Category: Turbo HD Products"
    "Subcategory: DVR"
    "Models: 38"
    "Models"
      "iDS-7204HQHI-M1-S"
      "ids-7204hqhi-m1-xt"
      "ids-7204hthi-m1-s"
      "ids-7204hthi-m1-xt"
      "ids-7204hthi-m2-s"
      "ids-7204hthi-m2-xt"
      "ids-7204huhi-m1-p"
      "ids-7204huhi-m1-pxt"
      "30 more models"
    "No specification comparison yet"