mindmap
  root(("2 Wire Hd"))
    "Category: Video Intercom Products"
    "Subcategory: 2 Wire Series"
    "Models: 39"
    "Models"
      "ds-ka-rl1e2"
      "ds-kad-e2-e1"
      "ds-kad7040ey"
      "ds-kad7042ey"
      "ds-kad7060ey"
      "ds-kad7060ey-s"
      "ds-kad7061ey"
      "ds-kad7062ey"
      "31 more models"
    "No specification comparison yet"