mindmap
  root(("2 Wire Kits"))
    "Models: 15"
    "Models"
      "ds-kis101-p-flush"
      "ds-kis101-p-surface"
      "ds-kis102-p-surface"
      "ds-kis103"
      "ds-kis702ey"
      "ds-kis702y"
      "ds-kis702y-p"
      "ds-kis703y-p"
      "ds-kis704ey"
      "ds-kis704ey-aluminum"
      "ds-kis705ey"
      "ds-kis705ey-2monitors"
      "ds-kis706ey"
      "ds-kis707ey"
      "ds-kis708ey"