mindmap
  root(("Panic Alarm Panel"))
    "Models: 13"
    "Models"
      "ds-pea1-21"
      "ds-pea1-n1"
      "ds-pea101-v1-r"
      "ds-pea103-ck1"
      "ds-pea103-ck1-e1"
      "ds-pea22-f-b-"
      "ds-peap-cv1-b-"
      "ds-peap-cv1e-b-"
      "ds-peap-cv2e-b-"
      "ds-peap-cvs1-b-"
      "ds-peap-cvs1e-b-"
      "ds-peap-cvsa1-b-"
      "ds-peap-cvsa1e-b-"