mindmap
  root(("2 Wire Hd"))
    "Models: 39"
    "Models"
      "ds-ka-rl1e2"
      "ds-kad-e2-e1"
      "ds-kad7040ey"
      "ds-kad7042ey"
      "ds-kad7060ey"
      "ds-kad7060ey-s"
      "ds-kad7061ey"
      "ds-kad7062ey"
      "ds-kaw150-4n"
      "ds-kaw36-4n"
      "ds-kaw92-4n"
      "ds-kd7000ey-me2"
      "ds-kd7000ey-me2-aluminum"
      "ds-kd7003ey-ime2"
      "ds-kd7003ey-ime2-aluminum"
      "ds-kd7003ey-s2"
      "ds-kh7000ey-e2"
      "ds-kh7000ey-e2-white"
      "21 more models"