mindmap
  root(("2 Wire Ip"))
    "Models: 9"
    "Models"
      "ds-kad704y"
      "ds-kad706"
      "ds-kad706-p"
      "ds-kad706y"
      "ds-kad706y-s"
      "ds-kd8003y-ime2"
      "ds-kd8003y-ime2-ns"
      "ds-kd8003y-ime2-s"
      "ds-kh6320y-wte2"