mindmap
  root(("IP Kits"))
    "Models: 16"
    "Models"
      "DS-KIS602"
      "ds-kis602-b-"
      "ds-kis603-p-b-"
      "ds-kis603-p-c-"
      "ds-kis604-p-c-"
      "ds-kis604-s-c-"
      "ds-kis605-p-c-"
      "ds-kis606-p"
      "ds-kis607-s"
      "ds-kis608-p"
      "ds-kis610-p"
      "ds-kis611-s"
      "ds-kis612-p"
      "ds-kis613-s"
      "ds-kis901-p"
      "ds-kis902-s"