mindmap
  root(("Sip Server"))
    "Models: 10"
    "Models"
      "ds-ks6150"
      "ds-ks6160"
      "ds-ks6170"
      "ds-ksme100"
      "ds-ksmet08"
      "ds-ksmete1"
      "ds-ksmxb2"
      "ds-ksmxo2"
      "ds-ksmxos2"
      "ds-ksmxs2"