mindmap
  root(("Pro Series"))
    "Models: 70"
    "Models"
      "ds-kb8113-ime1"
      "ds-kd-al8"
      "DS-KD-DIS"
      "ds-kd-e-ac"
      "DS-KD-IN"
      "ds-kd-info"
      "ds-kd-k12"
      "ds-kd-k12-s"
      "DS-KD-KK"
      "ds-kd-kk-s"
      "DS-KD-KP"
      "ds-kd-kp-s"
      "DS-KD-M"
      "ds-kd-mfb-s"
      "ds-kd-pmr"
      "ds-kd-tde"
      "ds-kd-tdm"
      "DS-KD8003-IME1"
      "52 more models"