mindmap
  root(("Ultra Series"))
    "Models: 23"
    "Models"
      "ds-kd9203-e6"
      "ds-kd9203-fe6"
      "ds-kd9203-fte6"
      "ds-kd9203-me6"
      "ds-kd9203-mfe6"
      "ds-kd9203-mfte6"
      "ds-kd9203-mte6"
      "ds-kd9403-e6"
      "ds-kd9613-e6"
      "ds-kd9613-fe6"
      "ds-kd9633-e6"
      "ds-kd9633-wbe6"
      "ds-kdm9403-fkp"
      "ds-kdm9403-kp"
      "ds-kdm9633-fkp"
      "ds-kdm9633-kp"
      "ds-kh9310-wte1"
      "ds-kh9310-wte1-b-"
      "5 more models"